package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// workspace lays out a directory holding requests, and returns its path.
func workspace(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("creating %s: %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("writing %s: %v", path, err)
		}
	}
	return dir
}

const listMailboxes = `{
  "_doc": "ListMailboxes returns every mailbox in the account.",
  "methodCalls": [["Mailbox/get", {"ids": null, "properties": ["id", "name", "role"]}, "all"]],
  "_returns": "all"
}`

func TestGenerate(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/ListMailboxes.jmap.json": listMailboxes,
	})
	out := filepath.Join(dir, "client")

	if err := run([]string{"generate", "-requests", filepath.Join(dir, "requests"), "-out", out}); err != nil {
		t.Fatalf("generate: %v", err)
	}
	src, err := os.ReadFile(filepath.Join(out, "listmailboxes_gen.go"))
	if err != nil {
		t.Fatalf("reading the generated client: %v", err)
	}
	for _, want := range []string{"package client", "func ListMailboxes(", "ListMailboxesAllResponse"} {
		if !strings.Contains(string(src), want) {
			t.Errorf("the generated client does not contain %q:\n%s", want, src)
		}
	}
}

func TestGenerateRust(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/ListMailboxes.jmap.json": listMailboxes,
	})
	out := filepath.Join(dir, "client")

	args := []string{"generate", "-requests", filepath.Join(dir, "requests"), "-out", out, "-lang", "rust"}
	if err := run(args); err != nil {
		t.Fatalf("generate: %v", err)
	}
	// The runtime comes with the requests, since there is no crate to depend
	// on, and the mod.rs is what makes the directory a module.
	for _, name := range []string{"list_mailboxes.rs", "types.rs", "client.rs", "mod.rs"} {
		if _, err := os.Stat(filepath.Join(out, name)); err != nil {
			t.Errorf("the generated client has no %s: %v", name, err)
		}
	}
	src, err := os.ReadFile(filepath.Join(out, "list_mailboxes.rs"))
	if err != nil {
		t.Fatalf("reading the generated client: %v", err)
	}
	for _, want := range []string{
		"pub async fn list_mailboxes<T: Transport>(",
		"pub struct ListMailboxesAllResponse",
		"use super::client::{",
	} {
		if !strings.Contains(string(src), want) {
			t.Errorf("the generated client does not contain %q:\n%s", want, src)
		}
	}
}

func TestUnknownLanguage(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/ListMailboxes.jmap.json": listMailboxes,
	})
	err := run([]string{"generate", "-requests", filepath.Join(dir, "requests"), "-lang", "cobol"})
	if err == nil {
		t.Fatal("generating a language jmapc does not write should have failed")
	}
	if !strings.Contains(err.Error(), "rust") {
		t.Errorf("the error should say what the languages are, and it says: %v", err)
	}
}

func TestCheck(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/ListMailboxes.jmap.json": listMailboxes,
	})
	if err := run([]string{"check", "-requests", filepath.Join(dir, "requests")}); err != nil {
		t.Fatalf("check: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "client")); !os.IsNotExist(err) {
		t.Error("check wrote something, and it should not have")
	}
}

// TestCheckReportsBadQueries checks that a request that does not hold up stops the
// run rather than producing a client that cannot work.
func TestCheckReportsBadQueries(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/Broken.jmap.json": `{"methodCalls": [["Mailbox/git", {}, "c0"]]}`,
	})
	err := run([]string{"check", "-requests", filepath.Join(dir, "requests")})
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(err.Error(), "did not check out") {
		t.Errorf("error = %v", err)
	}
}

// TestConfigFile checks that settings are read from jmapc.json in the working
// directory, which is how go:generate invokes the tool.
func TestConfigFile(t *testing.T) {
	dir := workspace(t, map[string]string{
		"jmapc.json":                `{"requests": "q", "out": "client", "package": "mailq"}`,
		"q/ListMailboxes.jmap.json": listMailboxes,
	})
	t.Chdir(dir)

	if err := run([]string{"generate"}); err != nil {
		t.Fatalf("generate: %v", err)
	}
	src, err := os.ReadFile(filepath.Join(dir, "client", "listmailboxes_gen.go"))
	if err != nil {
		t.Fatalf("reading the generated client: %v", err)
	}
	if !strings.HasPrefix(string(src), "// Code generated by jmapc. DO NOT EDIT.") {
		t.Errorf("the generated file does not say it is generated:\n%s", src)
	}
	if !strings.Contains(string(src), "package mailq") {
		t.Errorf("the generated file is not in the configured package:\n%s", src)
	}
}

// TestConfigFileRejectsUnknownSettings checks that a misspelled setting is
// reported rather than silently ignored.
func TestConfigFileRejectsUnknownSettings(t *testing.T) {
	dir := workspace(t, map[string]string{
		"jmapc.json":                `{"request": "q"}`,
		"q/ListMailboxes.jmap.json": listMailboxes,
	})
	t.Chdir(dir)

	err := run([]string{"generate"})
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(err.Error(), `unknown field "request"`) {
		t.Errorf("error = %v", err)
	}
}

const notesSchema = `{
  "capability": "urn:example:params:jmap:notes",
  "types": [
    {
      "name": "Note",
      "doc": "Note is a scrap of text the user keeps.",
      "properties": [
        {"name": "id", "type": "Id", "serverSet": true, "immutable": true, "doc": "The id of the note."},
        {"name": "title", "type": "String", "doc": "The note's title."}
      ],
      "methods": ["get", "query"]
    },
    {
      "name": "NoteFilterCondition",
      "doc": "NoteFilterCondition is a condition a note must satisfy to match a Note/query.",
      "properties": [{"name": "text", "type": "String", "doc": "Matches notes containing this text."}]
    }
  ]
}`

// TestSchemaExtendsTheModel checks that a request against a vendor capability is
// generated, and checked, just as one against a standard type is.
func TestSchemaExtendsTheModel(t *testing.T) {
	dir := workspace(t, map[string]string{
		"schema/notes.json": notesSchema,
		"requests/FindNotes.jmap.json": `{
		  "methodCalls": [
		    ["Note/query", {"filter": {"text": "{{phrase}}"}}, "search"],
		    ["Note/get", {
		      "#ids": {"resultOf": "search", "name": "Note/query", "path": "/ids"},
		      "properties": ["id", "title"]
		    }, "fetch"]
		  ],
		  "_returns": "fetch"
		}`,
	})
	out := filepath.Join(dir, "client")

	err := run([]string{"generate",
		"-schema", filepath.Join(dir, "schema", "notes.json"),
		"-requests", filepath.Join(dir, "requests"),
		"-out", out,
	})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	src, err := os.ReadFile(filepath.Join(out, "findnotes_gen.go"))
	if err != nil {
		t.Fatalf("reading the generated client: %v", err)
	}
	for _, want := range []string{
		`"urn:example:params:jmap:notes"`,
		"type FindNotesFetchNote struct",
		`Title string ` + "`json:\"title\"`",
	} {
		if !strings.Contains(string(src), want) {
			t.Errorf("the generated client does not contain %q:\n%s", want, src)
		}
	}
}

// TestSchemaIsChecked checks that a request using a vendor type wrongly fails, so
// that an extension is no less checked than the built-in model.
func TestSchemaIsChecked(t *testing.T) {
	dir := workspace(t, map[string]string{
		"schema/notes.json": notesSchema,
		"requests/FindNotes.jmap.json": `{
		  "methodCalls": [["Note/get", {"properties": ["id", "titel"]}, "c0"]]
		}`,
	})
	err := run([]string{"check",
		"-schema", filepath.Join(dir, "schema", "notes.json"),
		"-requests", filepath.Join(dir, "requests"),
	})
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(err.Error(), "did not check out") {
		t.Errorf("error = %v", err)
	}
}

// TestSchemaErrorsAreReported checks that a broken schema is reported against
// the file it came from.
func TestSchemaErrorsAreReported(t *testing.T) {
	dir := workspace(t, map[string]string{
		"schema/broken.json":        `{"capability": "urn:x:y", "types": [{"name": "Email", "properties": []}]}`,
		"q/ListMailboxes.jmap.json": listMailboxes,
	})
	err := run([]string{"check",
		"-schema", filepath.Join(dir, "schema", "broken.json"),
		"-requests", filepath.Join(dir, "q"),
	})
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(err.Error(), "broken.json") || !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error = %v", err)
	}
}

func TestNoQueries(t *testing.T) {
	dir := workspace(t, map[string]string{"requests/README.md": "nothing here"})
	err := run([]string{"check", "-requests", filepath.Join(dir, "requests")})
	if err == nil || !strings.Contains(err.Error(), "no .jmap.json files") {
		t.Errorf("error = %v, want it to say there are no requests", err)
	}
}

func TestUnknownCommand(t *testing.T) {
	if err := run([]string{"frobnicate"}); err == nil {
		t.Error("expected an error for an unknown command")
	}
	if err := run(nil); err == nil {
		t.Error("expected an error when given no command")
	}
	if err := run([]string{"help"}); err != nil {
		t.Errorf("help: %v", err)
	}
}

// TestSameRequestUnderTwoNames covers two request files holding one request. They
// differ only in what they call their parameters and their calls, so they make
// the same request, and each brings a set of generated types along with it.
func TestSameRequestUnderTwoNames(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/ListInbox.jmap.json": `{
		  "_doc": "ListInbox reads the inbox.",
		  "methodCalls": [["Email/query", {"filter": {"inMailbox": "{{mailboxId}}"}, "limit": "{{limit}}"}, "search"]],
		  "_returns": "search"
		}`,
		// The same request: other names for the parameters and the call, other
		// documentation, and the members written in another order.
		"requests/ListArchive.jmap.json": `{
		  "_returns": "c0",
		  "methodCalls": [["Email/query", {"limit": "{{howMany}}", "filter": {"inMailbox": "{{folderId}}"}}, "c0"]]
		}`,
		// Not the same request: it asks the server for something else.
		"requests/ListThreads.jmap.json": `{
		  "methodCalls": [["Email/query", {"filter": {"inMailbox": "{{mailboxId}}"}, "limit": "{{limit}}",
		                   "collapseThreads": true}, "search"]],
		  "_returns": "search"
		}`,
	})

	_, errOut, err := capture(t, []string{"check", "-requests", filepath.Join(dir, "requests")})
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	want := "ListArchive, ListInbox are the same request under different names"
	if !strings.Contains(errOut, want) {
		t.Errorf("the note does not say %q:\n%s", want, errOut)
	}
	if strings.Contains(errOut, "ListThreads") {
		t.Errorf("a request asking for something else was reported as the same:\n%s", errOut)
	}
}

// TestSameRequestIsANoteRatherThanAnError checks that two names for one request
// still generate: a project may want both, and jmapc is not the one to say it
// may not.
func TestSameRequestIsANoteRatherThanAnError(t *testing.T) {
	dir := workspace(t, map[string]string{
		"requests/ListMailboxes.jmap.json": listMailboxes,
		"requests/AllMailboxes.jmap.json": `{
		  "methodCalls": [["Mailbox/get", {"ids": null, "properties": ["id", "name", "role"]}, "every"]],
		  "_returns": "every"
		}`,
	})
	out := filepath.Join(dir, "client")
	if _, _, err := capture(t, []string{"generate", "-requests", filepath.Join(dir, "requests"), "-out", out}); err != nil {
		t.Fatalf("generate: %v", err)
	}
	for _, name := range []string{"listmailboxes_gen.go", "allmailboxes_gen.go"} {
		if _, err := os.Stat(filepath.Join(out, name)); err != nil {
			t.Errorf("%s was not generated: %v", name, err)
		}
	}
}
