// Code generated by jmapc. DO NOT EDIT.
// Source: requests/properties.json

package client

import (
	"github.com/linyows/jmapc"
)

// EmailSummary is what a list of messages shows: enough to draw a row and to
// group the rows into threads, and none of the body.
//
// EmailSummary holds the properties of Email that a call asking for
// @EmailSummary receives.
type EmailSummary struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The id of the thread the email belongs to.
	ThreadID jmapc.ID `json:"threadId"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// The From header field value.
	From []jmapc.EmailAddress `json:"from"`

	// When the email was received, which is what the mailbox sorts on by
	// default.
	ReceivedAt jmapc.UTCDate `json:"receivedAt"`

	// A short plain-text excerpt of the message body.
	Preview string `json:"preview"`

	// Whether the message has at least one part the server considers an
	// attachment.
	HasAttachment bool `json:"hasAttachment"`
}

// EmailWithFlags is a summary and where the message sits: which mailboxes
// hold it, and which keywords it carries. A cache catching up needs both.
//
// EmailWithFlags holds the properties of Email that a call asking for
// @EmailWithFlags receives.
type EmailWithFlags struct {
	// The properties of EmailSummary, which this set adds to.
	EmailSummary

	// The mailboxes the email is in, as a set of ids mapped to true.
	MailboxIDs map[jmapc.ID]bool `json:"mailboxIds"`

	// The keywords set on the email, such as "$seen" or "$flagged", mapped to
	// true.
	Keywords map[string]bool `json:"keywords"`
}
