// Code generated by jmapc. DO NOT EDIT.
// Source: requests/ReadAttachedMessage.jmap.json

package client

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// ReadAttachedMessageParams holds the values ReadAttachedMessage leaves open.
type ReadAttachedMessageParams struct {
	// One of the ids in the list.
	//
	// The ids of the blobs to parse as messages.
	BlobID jmapc.ID
}

// ReadAttachedMessageParseEmailBodyPart holds the properties of EmailBodyPart
// that the Email/parse call in ReadAttachedMessage asks for.
type ReadAttachedMessageParseEmailBodyPart struct {
	// Identifies the part's content within the bodyValues map, or null if the
	// part has no body of its own.
	PartID *string `json:"partId"`

	// The media type of the part.
	Type string `json:"type"`

	// The size of the decoded content in octets.
	Size jmapc.UnsignedInt `json:"size"`
}

// ReadAttachedMessageParseEmail holds the properties of Email that the
// Email/parse call in ReadAttachedMessage asks for.
type ReadAttachedMessageParseEmail struct {
	// The Subject header field value.
	Subject *string `json:"subject"`

	// The From header field value.
	From []jmapc.EmailAddress `json:"from"`

	// The Date header field value.
	SentAt *jmapc.Date `json:"sentAt"`

	// The parts to display as the plain-text body of the message.
	TextBody []ReadAttachedMessageParseEmailBodyPart `json:"textBody"`

	// The decoded content of the body parts that were fetched, keyed by partId.
	BodyValues map[string]jmapc.EmailBodyValue `json:"bodyValues"`
}

// ReadAttachedMessageParseResponse holds the response to the Email/parse call
// in ReadAttachedMessage.
type ReadAttachedMessageParseResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A map of blob id to the email parsed from it. The email has no id,
	// mailboxIds, keywords, or receivedAt, because it is not a record in the
	// account.
	Parsed map[jmapc.ID]ReadAttachedMessageParseEmail `json:"parsed"`

	// The ids of the blobs that exist but do not hold a message the server could
	// parse.
	NotParsable []jmapc.ID `json:"notParsable"`

	// The ids of the blobs that do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// ReadAttachedMessage reads a message sent as an attachment, for display,
// without filing it in the account. The parsed messages come back keyed by
// the blob they were read from, each typed down to the properties asked for.
//
// It makes one Email/parse call in a single request, so that the server is
// asked once. It returns the response to the Email/parse call.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func ReadAttachedMessage(ctx context.Context, c *jmapc.Client, p ReadAttachedMessageParams) (*ReadAttachedMessageParseResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/parse", CallID: "parse", Args: map[string]any{
				"accountId": mailAccountID,
				"blobIds": []any{
					p.BlobID,
				},
				"properties":          json.RawMessage(`["subject","from","sentAt","textBody","bodyValues"]`),
				"bodyProperties":      json.RawMessage(`["partId","type","size"]`),
				"fetchTextBodyValues": true,
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out ReadAttachedMessageParseResponse
	if e := resp.Decode("parse", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}
	return &out, err
}
