// Code generated by jmapc. DO NOT EDIT.
// Source: requests

package client

import (
	"context"

	"github.com/linyows/jmapc"
)

// Verify checks every request in this package against the session, and
// reports everything that would stop one of them from being sent. Call it as
// the program starts, to learn then rather than when a request is first sent.
// See jmapc.Client.Verify for what it checks.
func Verify(ctx context.Context, c *jmapc.Client) error {
	return c.Verify(ctx, []jmapc.RequestNeeds{
		{
			Name:            "Agenda",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityCalendars},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityCalendars},
		},
		{
			Name:            "AttachNote",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityBlob, jmapc.CapabilityMail},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityBlob, jmapc.CapabilityMail},
		},
		{
			Name:            "CheckSieveScript",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityBlob, jmapc.CapabilitySieve},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityBlob, jmapc.CapabilitySieve},
		},
		{
			Name:  "ConfirmPush",
			Using: []string{jmapc.CapabilityCore},
			Calls: 1,
		},
		{
			Name:            "CreateContact",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityContacts},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityContacts},
		},
		{
			Name:            "CreateEvent",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityCalendars},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityCalendars},
		},
		{
			Name:            "CreateMailbox",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "FileIntoNewMailbox",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "FindPeople",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityPrincipals},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityPrincipals},
		},
		{
			Name:            "InstallSieveScript",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityBlob, jmapc.CapabilitySieve},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityBlob, jmapc.CapabilitySieve},
		},
		{
			Name:            "ListInboxEmails",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "MailQuota",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityQuota},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityQuota},
		},
		{
			Name:            "MarkEmailRead",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "ReadMessage",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "RecentlyShared",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityPrincipals},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityPrincipals},
		},
		{
			Name:  "RegisterPush",
			Using: []string{jmapc.CapabilityCore},
			Calls: 1,
		},
		{
			Name:            "RescheduleOccurrence",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityCalendars},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityCalendars},
		},
		{
			Name:            "SearchContacts",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityContacts},
			Calls:           3,
			PrimaryAccounts: []string{jmapc.CapabilityContacts},
		},
		{
			Name:            "SearchEmails",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "SendEmail",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail, jmapc.CapabilitySubmission},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityMail, jmapc.CapabilitySubmission},
		},
		{
			Name:            "SendReadReceipt",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMDN},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityMDN},
		},
		{
			Name:            "SyncEmails",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
			Calls:           3,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "UpdateContactEmail",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityContacts},
			Calls:           1,
			PrimaryAccounts: []string{jmapc.CapabilityContacts},
		},
		{
			Name:            "VerifiedSignatures",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail, jmapc.CapabilitySMIMEVerify},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityMail},
		},
		{
			Name:            "WhatUsesBlob",
			Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityBlob},
			Calls:           2,
			PrimaryAccounts: []string{jmapc.CapabilityBlob},
		},
	}...)
}
