// Code generated by jmapc. DO NOT EDIT.
// Source: requests/FindMailboxByRole.jmap.json

package client

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// FindMailboxByRoleParams holds the values FindMailboxByRole leaves open.
type FindMailboxByRoleParams struct {
	// Matches mailboxes with this role, or with no role if null.
	Role string
}

// FindMailboxByRoleFetchMailbox holds the properties of Mailbox that the
// Mailbox/get call in FindMailboxByRole asks for.
type FindMailboxByRoleFetchMailbox struct {
	// The id of the mailbox.
	ID jmapc.ID `json:"id"`

	// The user-visible name of the mailbox, unique among its siblings.
	Name string `json:"name"`

	// The IANA-registered role of the mailbox, such as "inbox" or "trash", or
	// null if it has none.
	Role *string `json:"role"`
}

// FindMailboxByRoleFetchResponse holds the response to the Mailbox/get call
// in FindMailboxByRole.
type FindMailboxByRoleFetchResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Mailbox/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []FindMailboxByRoleFetchMailbox `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// FindMailboxByRole returns the mailbox that has a role, such as the inbox.
//
// It makes Mailbox/query and Mailbox/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Mailbox/get call.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func FindMailboxByRole(ctx context.Context, c *jmapc.Client, p FindMailboxByRoleParams) (*FindMailboxByRoleFetchResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Mailbox/query", CallID: "search", Args: map[string]any{
				"accountId": mailAccountID,
				"filter": map[string]any{
					"role": p.Role,
				},
			}},
			{Name: "Mailbox/get", CallID: "fetch", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "Mailbox/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","name","role"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out FindMailboxByRoleFetchResponse
	if e := resp.Decode("fetch", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}
	return &out, err
}
