// Code generated by jmapc. DO NOT EDIT.
// Source: requests/FindEmailsBySubject.jmap.json

package client

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// FindEmailsBySubjectParams holds the values FindEmailsBySubject leaves open.
type FindEmailsBySubjectParams struct {
	// Matches emails where this text appears in the Subject header field.
	Subject string
}

// FindEmailsBySubjectFetchEmail holds the properties of Email that the
// Email/get call in FindEmailsBySubject asks for.
type FindEmailsBySubjectFetchEmail struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// The From header field value.
	From []jmapc.EmailAddress `json:"from"`

	// The To header field value.
	To []jmapc.EmailAddress `json:"to"`

	// When the email was received, which is what the mailbox sorts on by
	// default.
	ReceivedAt jmapc.UTCDate `json:"receivedAt"`

	// The mailboxes the email is in, as a set of ids mapped to true.
	MailboxIDs map[jmapc.ID]bool `json:"mailboxIds"`

	// The keywords set on the email, such as "$seen" or "$flagged", mapped to
	// true.
	Keywords map[string]bool `json:"keywords"`
}

// FindEmailsBySubjectFetchResponse holds the response to the Email/get call
// in FindEmailsBySubject.
type FindEmailsBySubjectFetchResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []FindEmailsBySubjectFetchEmail `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// FindEmailsBySubject returns the most recent emails whose subject contains a
// phrase, newest first.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Email/get call.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func FindEmailsBySubject(ctx context.Context, c *jmapc.Client, p FindEmailsBySubjectParams) (*FindEmailsBySubjectFetchResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/query", CallID: "search", Args: map[string]any{
				"accountId": mailAccountID,
				"filter": map[string]any{
					"subject": p.Subject,
				},
				"sort":  json.RawMessage(`[{"property":"receivedAt","isAscending":false}]`),
				"limit": 10,
			}},
			{Name: "Email/get", CallID: "fetch", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "Email/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","subject","from","to","receivedAt","mailboxIds","keywords"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out FindEmailsBySubjectFetchResponse
	if e := resp.Decode("fetch", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}
	return &out, err
}
