// Code generated by jmapc. DO NOT EDIT.
// Source: requests/ImportEmail.jmap.json

package client

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/linyows/jmapc"
)

// ImportEmailParams holds the values ImportEmail leaves open.
type ImportEmailParams struct {
	// The id of the blob holding the raw RFC 5322 message.
	BlobID jmapc.ID

	// An id that is a key of mailboxIds: the mailboxes to file the imported
	// email in.
	MailboxID jmapc.ID
}

// ImportEmailImported is the creation id ImportEmail gives a record it
// creates, which the response reports it under.
const ImportEmailImported jmapc.ID = "imported"

// ImportEmailResult holds the response to each method call ImportEmail makes.
type ImportEmailResult struct {
	// The response to the Email/import call, made as "import".
	Import jmapc.EmailImportResponse
}

// ImportEmail adds a message, uploaded beforehand as a blob, to a mailbox,
// flagged and not yet read.
//
// It makes one Email/import call in a single request, so that the server is
// asked once.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func ImportEmail(ctx context.Context, c *jmapc.Client, p ImportEmailParams) (*ImportEmailResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/import", CallID: "import", Args: map[string]any{
				"accountId": mailAccountID,
				"emails": map[string]any{
					"imported": map[string]any{
						"blobId": p.BlobID,
						"mailboxIds": map[string]any{
							string(p.MailboxID): true,
						},
						"keywords": json.RawMessage(`{"$flagged":true}`),
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out ImportEmailResult
	if e := resp.Decode("import", &out.Import); e != nil && err == nil {
		return nil, e
	}

	var failures jmapc.SetErrors
	failures.Collect("Email/import", "import", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated": out.Import.NotCreated,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
