// Code generated by jmapc. DO NOT EDIT.
// Source: requests/SendReadReceipt.jmap.json

package client

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/linyows/jmapc"
)

// SendReadReceiptParams holds the values SendReadReceipt leaves open.
type SendReadReceiptParams struct {
	// The identity to send from, which decides both the sender and the address
	// the notification is issued for.
	IdentityID jmapc.ID

	// The id of the email this is about. It is required when sending, and may be
	// null in one that was parsed, where the message it refers to may not be in
	// the account.
	EmailID jmapc.ID
}

// SendReadReceipt tells the sender of a message that it was displayed. It is
// here for Verify, not to be sent: it uses MDN, and Verify has to report it
// where the session does not advertise MDN, as Stalwart 0.16 does not.
//
// It makes one MDN/send call in a single request, so that the server is asked
// once. It returns the response to the MDN/send call.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mdn is used, which costs a session lookup
// on first use.
func SendReadReceipt(ctx context.Context, c *jmapc.Client, p SendReadReceiptParams) (*jmapc.MDNSendResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mdnAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMDN)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMDN},
		MethodCalls: []jmapc.Invocation{
			{Name: "MDN/send", CallID: "send", Args: map[string]any{
				"accountId":  mdnAccountID,
				"identityId": p.IdentityID,
				"send": map[string]any{
					"receipt": map[string]any{
						"forEmailId":  p.EmailID,
						"disposition": json.RawMessage(`{"actionMode":"manual-action","sendingMode":"mdn-sent-manually","type":"displayed"}`),
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out jmapc.MDNSendResponse
	if e := resp.Decode("send", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}

	var failures jmapc.SetErrors
	failures.Collect("MDN/send", "send", map[string]map[jmapc.ID]jmapc.SetError{
		"notSent": out.NotSent,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
