// Code generated by jmapc. DO NOT EDIT.
// Source: requests/SyncEmails.jmap.json

package client

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// SyncEmailsParams holds the values SyncEmails leaves open.
type SyncEmailsParams struct {
	// The state string the client already has, as returned by an earlier
	// Email/get or Email/changes.
	SinceState string

	// The maximum number of ids to return across the three change lists.
	MaxChanges jmapc.UnsignedInt
}

// SyncEmailsCreatedEmail holds the properties of Email that the Email/get
// call in SyncEmails asks for.
type SyncEmailsCreatedEmail struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// The keywords set on the email, such as "$seen" or "$flagged", mapped to
	// true.
	Keywords map[string]bool `json:"keywords"`
}

// SyncEmailsCreatedResponse holds the response to the Email/get call in
// SyncEmails.
type SyncEmailsCreatedResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []SyncEmailsCreatedEmail `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// SyncEmailsResult holds the response to each method call SyncEmails makes.
type SyncEmailsResult struct {
	// The response to the Email/changes call, made as "changes".
	Changes jmapc.EmailChangesResponse

	// The response to the Email/get call, made as "created".
	Created SyncEmailsCreatedResponse
}

// SyncEmails returns the emails created since a state, at most a given number
// of changes at a time, and is watched so that a push runs it again.
//
// It makes Email/changes and Email/get calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func SyncEmails(ctx context.Context, c *jmapc.Client, p SyncEmailsParams) (*SyncEmailsResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/changes", CallID: "changes", Args: map[string]any{
				"accountId":  mailAccountID,
				"sinceState": p.SinceState,
				"maxChanges": p.MaxChanges,
			}},
			{Name: "Email/get", CallID: "created", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "changes", Name: "Email/changes", Path: "/created"},
				"properties": json.RawMessage(`["id","subject","keywords"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out SyncEmailsResult
	if e := resp.Decode("changes", &out.Changes); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("created", &out.Created); e != nil && err == nil {
		return nil, e
	}
	return &out, err
}

// SyncEmailsWatch follows the changes to Email, calling SyncEmails whenever
// the server reports any and passing the result to fn.
//
// It starts from the sinceState the parameters carry, which is the state a
// previous answer reported, and it continues from the state each answer
// reports. A server that returns only part of what changed is called again
// until it reports no more.
//
// It runs until the context ends, which is the error it returns; an error
// from fn stops it and is returned unchanged. A dropped connection is not an
// error: the loop opens another, resuming from the last event delivered, and
// requests the changes made while no connection was open.
//
// A server that can no longer say what changed since the state it is given
// answers cannotCalculateChanges, which stops the loop. jmapc.WithResync,
// passed among the options, gives it a way back: read the records again and
// report the state they were read at.
func SyncEmailsWatch(ctx context.Context, c *jmapc.Client, p SyncEmailsParams, fn func(context.Context, *SyncEmailsResult) error, opts ...jmapc.WatchOption) error {
	session, err := c.Session(ctx)
	if err != nil {
		return err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return err
	}

	return c.Watch(ctx, mailAccountID, "Email", p.SinceState, func(ctx context.Context, sinceState string) (string, bool, error) {
		p.SinceState = sinceState
		res, err := SyncEmails(ctx, c, p)
		if err != nil {
			return "", false, err
		}
		if err := fn(ctx, res); err != nil {
			return "", false, err
		}
		return res.Changes.NewState, res.Changes.HasMoreChanges, nil
	}, opts...)
}
