// Code generated by jmapc. DO NOT EDIT.
// Source: requests

package client

import (
	"context"

	"github.com/linyows/jmapc"
)

// Verify checks every request in this package against the session, and
// reports everything that would stop one of them from being sent. Call it as
// the program starts, to learn then rather than when a request is first sent.
// See jmapc.Client.Verify for what it checks.
func Verify(ctx context.Context, c *jmapc.Client) error {
	return c.Verify(ctx, requestNeeds...)
}

// requestNeeds is what each request in this package needs of the server.
var requestNeeds = []jmapc.RequestNeeds{
	{
		Name:            "CurrentEmailState",
		Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		Calls:           1,
		PrimaryAccounts: []string{jmapc.CapabilityMail},
	},
	{
		Name:            "FindEmailsBySubject",
		Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		Calls:           2,
		PrimaryAccounts: []string{jmapc.CapabilityMail},
	},
	{
		Name:            "FindMailboxByRole",
		Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		Calls:           2,
		PrimaryAccounts: []string{jmapc.CapabilityMail},
	},
	{
		Name:            "ImportEmail",
		Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		Calls:           1,
		PrimaryAccounts: []string{jmapc.CapabilityMail},
	},
	{
		Name:            "SyncEmails",
		Using:           []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		Calls:           2,
		PrimaryAccounts: []string{jmapc.CapabilityMail},
	},
}
