// Code generated by jmapc. DO NOT EDIT.
// Source: queries/AttachNote.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { BlobUploadResponse, EmailSetResponse, Id } from "./types.js"

// AttachNoteParams holds the values AttachNote leaves open.
export interface AttachNoteParams {
  // The octets as text, which the server encodes as UTF-8.
  note: string

  // The id of the record this entry applies to.
  //
  // The mailboxes the email is in, as a set of ids mapped to true.
  draftsMailboxId: Id

  // The Subject header field value.
  subject: string
}

// attachNoteNote is the creation id AttachNote gives a record it creates,
// which the response reports it under.
export const attachNoteNote: Id = "note"

// attachNoteDraft is the creation id AttachNote gives a record it creates,
// which the response reports it under.
export const attachNoteDraft: Id = "draft"

// AttachNoteResult holds the response to each method call AttachNote makes.
export interface AttachNoteResult {
  // The response to the Blob/upload call, made as "upload".
  blobUpload: BlobUploadResponse

  // The response to the Email/set call, made as "draft".
  emailSet: EmailSetResponse
}

// AttachNote writes a note into a blob and attaches it to a draft in the same
// request. The upload endpoint of RFC 8620 cannot do this: it is a separate
// HTTP call, so the blob id has to come back to the client before the draft
// can refer to it.
//
// It makes Blob/upload and Email/set calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function attachNote(client: Client, p: AttachNoteParams): Promise<AttachNoteResult> {
  const blobAccountId = await client.primaryAccountId("urn:ietf:params:jmap:blob")
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Blob/upload", {
        "accountId": blobAccountId,
        "create": {
          "note": {
            "data": [
              {
                "data:asText": p.note,
              },
            ],
            "type": "text/plain",
          },
        },
      }, "upload"],
      // "#note" is the blob the call above creates, before the server has
      // given it an id.
      ["Email/set", {
        "accountId": mailAccountId,
        "create": {
          "draft": {
            "mailboxIds": {
              [p.draftsMailboxId]: true,
            },
            "keywords": {"$draft":true},
            "subject": p.subject,
            "attachments": [{"blobId":"#note","type":"text/plain","name":"note.txt","disposition":"attachment"}],
          },
        },
      }, "draft"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  const out = {
    ...(answered(res, "upload") ? { blobUpload: decode<BlobUploadResponse>(req, res, "upload") } : {}),
    ...(answered(res, "draft") ? { emailSet: decode<EmailSetResponse>(req, res, "draft") } : {}),
  } as AttachNoteResult
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("Blob/upload", "upload", {
    notCreated: out.blobUpload.notCreated,
  }, failures)
  collectSetErrors("Email/set", "draft", {
    notCreated: out.emailSet.notCreated,
    notUpdated: out.emailSet.notUpdated,
    notDestroyed: out.emailSet.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
