// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CheckSieveScript.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { BlobUploadResponse, SieveScriptValidateResponse } from "./types.js"

// CheckSieveScriptParams holds the values CheckSieveScript leaves open.
export interface CheckSieveScriptParams {
  // The octets as text, which the server encodes as UTF-8.
  script: string
}

// CheckSieveScript reports whether a script would parse and whether the
// server supports what it asks for, without storing it. It is what an editor
// calls while the user is still typing.
//
// It makes Blob/upload and SieveScript/validate calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// SieveScript/validate call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function checkSieveScript(client: Client, p: CheckSieveScriptParams): Promise<SieveScriptValidateResponse> {
  const blobAccountId = await client.primaryAccountId("urn:ietf:params:jmap:blob")
  const sieveAccountId = await client.primaryAccountId("urn:ietf:params:jmap:sieve")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    methodCalls: [
      ["Blob/upload", {
        "accountId": blobAccountId,
        "create": {
          "draft": {
            "data": [
              {
                "data:asText": p.script,
              },
            ],
            "type": "application/sieve",
          },
        },
      }, "upload"],
      ["SieveScript/validate", {
        "accountId": sieveAccountId,
        "#blobId": { resultOf: "upload", name: "Blob/upload", path: "/created/draft/id" },
      }, "check"],
    ],
  }

  const res = await client.request(req)

  return decode<SieveScriptValidateResponse>(req, res, "check")
}
