// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CheckSieveScript.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { BlobUploadResponse, SieveScriptValidateResponse } from "./types.js"

// CheckSieveScriptParams holds the values CheckSieveScript leaves open.
export interface CheckSieveScriptParams {
  // The octets as text, which the server encodes as UTF-8.
  script: string
}

// CheckSieveScript reports whether a script would parse and whether the
// server supports what it asks for, without storing it. It is what an editor
// calls while the user is still typing.
//
// It makes Blob/upload and SieveScript/validate calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// SieveScript/validate call.
//
// The query does not say which account to use, so the session's primary
// account is used for each of urn:ietf:params:jmap:blob and
// urn:ietf:params:jmap:sieve, which costs a session lookup on first use. They
// need not be the same account.
export async function checkSieveScript(client: Client, p: CheckSieveScriptParams): Promise<SieveScriptValidateResponse> {
  const blobAccountId = await client.primaryAccountId("urn:ietf:params:jmap:blob")
  const sieveAccountId = await client.primaryAccountId("urn:ietf:params:jmap:sieve")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    methodCalls: [
      ["Blob/upload", {
        "accountId": blobAccountId,
        "create": {
          "draft": {
            "data": [
              {
                "data:asText": p.script,
              },
            ],
            "type": "application/sieve",
          },
        },
      }, "upload"],
      ["SieveScript/validate", {
        "accountId": sieveAccountId,
        "#blobId": { resultOf: "upload", name: "Blob/upload", path: "/created/draft/id" },
      }, "check"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "check")) throw failed
  const out = decode<SieveScriptValidateResponse>(req, res, "check")
  if (failed) {
    failed.result = out
    throw failed
  }

  const refused0 = decode<BlobUploadResponse>(req, res, "upload")
  const failures: SetFailure[] = []
  collectSetErrors("Blob/upload", "upload", {
    notCreated: refused0.notCreated,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
