// Code generated by jmapc. DO NOT EDIT.
// Source: the jmapc runtime

import type { Account, Id } from "./types.js"

// A JMAP request: the capabilities it depends on, and the calls to make.
export interface Request {
  using: string[]
  methodCalls: Invocation[]
  createdIds?: { [creationId: Id]: Id }
}

// One method call or method response, which the wire format writes as the
// three-element array [name, arguments, callId].
export type Invocation = [string, unknown, string]

// A JMAP response: one entry per executed call, in the order the server ran
// them.
export interface Response {
  methodResponses: Invocation[]
  createdIds?: { [creationId: Id]: Id }
  sessionState: string
}

// A reference to a value in the response to an earlier call in the same
// request, which is what lets a chain of dependent calls cost one round trip.
export interface ResultReference {
  resultOf: string
  name: string
  path: string
}

// The session object: where to send requests, and what the server supports.
export interface Session {
  capabilities: { [uri: string]: unknown }
  accounts: { [id: Id]: Account }
  primaryAccounts: { [uri: string]: Id }
  username: string
  apiUrl: string
  downloadUrl: string
  uploadUrl: string
  eventSourceUrl: string
  state: string
}

// A request-level failure, where the server rejected the request whole. It
// carries the problem type of RFC 8620, Section 3.6.1.
export class RequestError extends Error {
  readonly status: number
  readonly type: string
  readonly detail?: string
  readonly limit?: string

  constructor(status: number, body: { type?: string; detail?: string; limit?: string; title?: string }) {
    const type = body.type ?? "about:blank"
    super(`jmapc: request failed with status ${status}: ${type}${body.detail ? ": " + body.detail : ""}`)
    this.name = "RequestError"
    this.status = status
    this.type = type
    this.detail = body.detail ?? body.title
    this.limit = body.limit
  }
}

// A method-level failure. JMAP runs the calls it can, so some of the response
// may still be usable; this names the method and call that failed rather than
// the bare "error" the wire format carries.
export class MethodError extends Error {
  readonly callId: string
  readonly methodName: string
  readonly type: string
  readonly description?: string
  readonly raw: Record<string, unknown>

  constructor(callId: string, methodName: string, raw: Record<string, unknown>) {
    const type = (raw.type as string) ?? "serverFail"
    super(`jmapc: ${methodName} (call "${callId}") failed: ${type}`)
    this.name = "MethodError"
    this.callId = callId
    this.methodName = methodName
    this.type = type
    this.description = raw.description as string | undefined
    this.raw = raw
  }
}

// Several method-level failures from one response.
export class MethodErrors extends Error {
  readonly errors: MethodError[]

  constructor(errors: MethodError[]) {
    super(errors.length === 1 ? errors[0].message : `jmapc: ${errors.length} method calls failed`)
    this.name = "MethodErrors"
    this.errors = errors
  }
}

// How to authenticate. Given a token, the client sends it as a bearer token;
// given a function, it calls it for each request, which covers the schemes a
// token does not.
export type Auth = string | ((headers: Headers) => void | Promise<void>)

export interface ClientOptions {
  // How to authenticate.
  auth?: Auth
  // Where to POST requests, if the session's apiUrl should not be used.
  apiUrl?: string
  // What to fetch with, for a runtime whose fetch is not the global one, or
  // for a test.
  fetch?: typeof fetch
  // Stop checking a request against the session before sending it. The checks
  // turn a wasted round trip into a local error, so leave them on unless a
  // server under-reports what it supports.
  skipPreflight?: boolean
}

// A client for one JMAP server. It caches the session, so a query costs one
// round trip rather than two.
export class Client {
  private readonly sessionUrl: string
  private readonly options: ClientOptions
  private cached?: Session

  constructor(sessionUrl: string, options: ClientOptions = {}) {
    this.sessionUrl = sessionUrl
    this.options = options
  }

  // The session, fetched on first use and cached afterwards.
  async session(): Promise<Session> {
    if (this.cached) return this.cached
    return this.refreshSession()
  }

  // Fetch the session again, replacing the cached copy. Call it when a
  // response reports a sessionState different from the one you hold.
  async refreshSession(): Promise<Session> {
    const res = await this.send(this.sessionUrl, { method: "GET" })
    if (!res.ok) throw await requestError(res)
    const session = (await res.json()) as Session
    if (!session.apiUrl) {
      throw new Error(`jmapc: session from ${this.sessionUrl} has no apiUrl`)
    }
    this.cached = session
    return session
  }

  // The account to use by default for a capability.
  async primaryAccountId(capability: string): Promise<Id> {
    const session = await this.session()
    const id = session.primaryAccounts[capability]
    if (!id) {
      throw new Error(`jmapc: session has no primary account for ${capability}`)
    }
    return id
  }

  // Send one request. A method-level failure throws MethodErrors; the response
  // is attached to it, since the calls that did run still have results.
  async request(req: Request): Promise<Response> {
    const apiUrl = this.options.apiUrl ?? (await this.session()).apiUrl
    if (!this.options.skipPreflight && !this.options.apiUrl) {
      await this.preflight(req)
    }
    const res = await this.send(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=utf-8" },
      body: JSON.stringify(req),
    })
    if (!res.ok) throw await requestError(res)

    const response = (await res.json()) as Response
    const errors = methodErrors(req, response)
    if (errors.length > 0) {
      const err = new MethodErrors(errors)
      ;(err as MethodErrors & { response: Response }).response = response
      throw err
    }
    return response
  }

  // Reject a request the session already shows the server will not accept, so
  // that a missing capability surfaces without a round trip.
  private async preflight(req: Request): Promise<void> {
    const session = await this.session()
    for (const uri of req.using) {
      if (!(uri in session.capabilities)) {
        throw new RequestError(0, {
          type: "urn:ietf:params:jmap:error:unknownCapability",
          detail: `server does not support ${uri}`,
        })
      }
    }
    const core = session.capabilities["urn:ietf:params:jmap:core"] as
      | { maxCallsInRequest?: number }
      | undefined
    const max = core?.maxCallsInRequest
    if (max && req.methodCalls.length > max) {
      throw new RequestError(0, {
        type: "urn:ietf:params:jmap:error:limit",
        limit: "maxCallsInRequest",
        detail: `request has ${req.methodCalls.length} method calls, server allows ${max}`,
      })
    }
  }

  private async send(url: string, init: RequestInit): Promise<globalThis.Response> {
    const headers = new Headers(init.headers)
    headers.set("Accept", "application/json")
    const auth = this.options.auth
    if (typeof auth === "string") {
      headers.set("Authorization", `Bearer ${auth}`)
    } else if (auth) {
      await auth(headers)
    }
    const f = this.options.fetch ?? fetch
    return f(url, { ...init, headers })
  }
}

// Decode the response to one method call, throwing where the server reported
// an error for it.
export function decode<T>(req: Request, res: Response, callId: string): T {
  for (const [name, args, id] of res.methodResponses) {
    if (id !== callId) continue
    if (name === "error") {
      throw new MethodError(callId, requestedMethod(req, callId), args as Record<string, unknown>)
    }
    return args as T
  }
  throw new Error(`jmapc: response has no result for call "${callId}"`)
}

// Every method-level error in a response.
function methodErrors(req: Request, res: Response): MethodError[] {
  const errors: MethodError[] = []
  for (const [name, args, id] of res.methodResponses) {
    if (name === "error") {
      errors.push(new MethodError(id, requestedMethod(req, id), args as Record<string, unknown>))
    }
  }
  return errors
}

// The method the client asked for under a call id, which the wire format
// replaces with the literal name "error" when it fails.
function requestedMethod(req: Request, callId: string): string {
  for (const [name, , id] of req.methodCalls) {
    if (id === callId) return name
  }
  return "error"
}

// Turn a non-2xx response into a RequestError, decoding the RFC 7807 problem
// details document where the server sent one.
async function requestError(res: globalThis.Response): Promise<RequestError> {
  const type = res.headers.get("Content-Type") ?? ""
  if (type.startsWith("application/problem+json") || type.startsWith("application/json")) {
    try {
      return new RequestError(res.status, await res.json())
    } catch {
      // Fall through to the plain-text form.
    }
  }
  return new RequestError(res.status, { detail: (await res.text()).trim() })
}
