// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateEvent.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { CalendarEventSetResponse, Duration, Id, LocalDateTime, TimeZoneId } from "./types.js"

// CreateEventParams holds the values CreateEvent leaves open.
export interface CreateEventParams {
  // A globally unique identifier for the event, shared by every copy of it.
  uid: string

  // The id of the record this entry applies to.
  //
  // The calendars the event is in, as a set of ids mapped to true.
  calendarId: Id

  // A short summary of the event.
  title: string

  // When the event starts, in the event's own time zone.
  start: LocalDateTime

  // How long the event lasts.
  duration: Duration

  // The time zone the start is in. Null means the event is floating, and
  // happens at that local time wherever the user is.
  timeZone: TimeZoneId

  // The participant's email address.
  organiserAddress: string

  // Where to send scheduling messages, keyed by method, such as "imip" mapped
  // to a mailto: URI.
  organiserSendTo: string
}

// CreateEvent puts a weekly meeting in a calendar, with a reminder a quarter
// of an hour beforehand. An event's time is local, and the time zone is a
// property of its own, so that the meeting stays at nine when the clocks
// change.
//
// It makes one CalendarEvent/set call in a single request, so that the server
// is asked once. It returns the response to the CalendarEvent/set call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:calendars is used, which costs a session
// lookup on first use.
export async function createEvent(client: Client, p: CreateEventParams): Promise<CalendarEventSetResponse> {
  const calendarsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:calendars")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:calendars"],
    methodCalls: [
      ["CalendarEvent/set", {
        "accountId": calendarsAccountId,
        "create": {
          "meeting": {
            "@type": "Event",
            "uid": p.uid,
            "calendarIds": {
              [p.calendarId]: true,
            },
            "title": p.title,
            "start": p.start,
            "duration": p.duration,
            "timeZone": p.timeZone,
            "recurrenceRules": [{"frequency":"weekly","byDay":[{"day":"mo"}]}],
            "alerts": {"reminder":{"trigger":{"@type":"OffsetTrigger","offset":"-PT15M"},"action":"display"}},
            "participants": {
              "organiser": {
                "email": p.organiserAddress,
                "roles": {"owner":true,"attendee":true},
                "participationStatus": "accepted",
                "sendTo": {
                  "imip": p.organiserSendTo,
                },
              },
            },
          },
        },
      }, "create"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "create")) throw failed
  const out = decode<CalendarEventSetResponse>(req, res, "create")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("CalendarEvent/set", "create", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
