// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateMailbox.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { Id, MailboxSetResponse } from "./types.js"

// CreateMailboxParams holds the values CreateMailbox leaves open.
export interface CreateMailboxParams {
  // The user-visible name of the mailbox, unique among its siblings.
  name: string
}

// createMailboxNew is the creation id CreateMailbox gives a record it
// creates, which the response reports it under.
export const createMailboxNew: Id = "new"

// CreateMailbox creates a top-level mailbox and subscribes to it.
//
// It makes one Mailbox/set call in a single request, so that the server is
// asked once. It returns the response to the Mailbox/set call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
export async function createMailbox(client: Client, p: CreateMailboxParams): Promise<MailboxSetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Mailbox/set", {
        "accountId": mailAccountId,
        "create": {
          "new": {
            "name": p.name,
            "parentId": null,
            "isSubscribed": true,
          },
        },
      }, "create"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "create")) throw failed
  const out = decode<MailboxSetResponse>(req, res, "create")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("Mailbox/set", "create", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
