// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateMailbox.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { MailboxSetResponse } from "./types.js"

// CreateMailboxParams holds the values CreateMailbox leaves open.
export interface CreateMailboxParams {
  // The user-visible name of the mailbox, unique among its siblings.
  name: string
}

// CreateMailbox creates a top-level mailbox and subscribes to it.
//
// It makes one Mailbox/set call in a single request, so that the server is
// asked once. It returns the response to the Mailbox/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function createMailbox(client: Client, p: CreateMailboxParams): Promise<MailboxSetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Mailbox/set", {
        "accountId": mailAccountId,
        "create": {
          "new": {
            "name": p.name,
            "parentId": null,
            "isSubscribed": true,
          },
        },
      }, "create"],
    ],
  }

  const res = await client.request(req)

  return decode<MailboxSetResponse>(req, res, "create")
}
