// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateContact.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { ContactCardSetResponse, Id } from "./types.js"

// CreateContactParams holds the values CreateContact leaves open.
export interface CreateContactParams {
  // A globally unique identifier for the entity, which survives being copied
  // between address books.
  uid: string

  // The id of the record this entry applies to.
  //
  // The address books the card is in, as a set of ids mapped to true.
  addressBookId: Id

  // The value of this part of the name.
  givenName: string

  // The value of this part of the name.
  surname: string

  // The address itself, as an addr-spec.
  emailAddress: string

  // The number, either as a URI or as free text.
  phoneNumber: string

  // The name of the organization.
  organization: string
}

// createContactCard is the creation id CreateContact gives a record it
// creates, which the response reports it under.
export const createContactCard: Id = "card"

// CreateContact adds a person to an address book. A contact card is a
// JSContact object, so a name is a list of parts rather than a string, and
// each address or number is an entry the card can refer to later.
//
// It makes one ContactCard/set call in a single request, so that the server
// is asked once. It returns the response to the ContactCard/set call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:contacts is used, which costs a session
// lookup on first use.
export async function createContact(client: Client, p: CreateContactParams): Promise<ContactCardSetResponse> {
  const contactsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:contacts")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
    methodCalls: [
      ["ContactCard/set", {
        "accountId": contactsAccountId,
        "create": {
          "card": {
            "@type": "Card",
            "version": "1.0",
            "uid": p.uid,
            "kind": "individual",
            "addressBookIds": {
              [p.addressBookId]: true,
            },
            "name": {
              "isOrdered": true,
              "components": [
                {
                  "kind": "given",
                  "value": p.givenName,
                },
                {
                  "kind": "surname",
                  "value": p.surname,
                },
              ],
            },
            "emails": {
              "work": {
                "address": p.emailAddress,
                "contexts": {"work":true},
                "pref": 1,
              },
            },
            "phones": {
              "mobile": {
                "number": p.phoneNumber,
                "features": {"mobile":true,"voice":true},
                "contexts": {"work":true},
              },
            },
            "organizations": {
              "employer": {
                "name": p.organization,
              },
            },
          },
        },
      }, "create"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "create")) throw failed
  const out = decode<ContactCardSetResponse>(req, res, "create")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("ContactCard/set", "create", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
