// Code generated by jmapc. DO NOT EDIT.
// Source: queries/FindPeople.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { Id, PrincipalQueryResponse } from "./types.js"

// FindPeopleParams holds the values FindPeople leaves open.
export interface FindPeopleParams {
  // Matches principals where this text appears in the name, email, or
  // description.
  phrase: string

  // The maximum number of ids to return.
  limit: number
}

// FindPeoplePrincipal holds the properties of Principal that the
// Principal/get call in FindPeople asks for.
export interface FindPeoplePrincipal {
  // The id of the principal.
  id: Id

  // What the principal is: "individual", "group", "resource", "location", or
  // "other".
  type: string

  // The user-visible name of the principal.
  name: string

  // An email address for the principal, or null for one that has none.
  email: string | null

  // The time zone the principal is normally in, named as in the IANA Time
  // Zone Database.
  timeZone: string | null
}

// FindPeoplePrincipalGetResponse holds the response to the Principal/get call
// in FindPeople.
export interface FindPeoplePrincipalGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Principal/changes.
  state: string

  // The records that were found, in an undefined order.
  list: FindPeoplePrincipal[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// FindPeople looks for the people and things an account can be shared with,
// which is what a sharing dialogue needs before it can offer anything.
//
// It makes Principal/query and Principal/get calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// Principal/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function findPeople(client: Client, p: FindPeopleParams): Promise<FindPeoplePrincipalGetResponse> {
  const principalsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:principals")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:principals"],
    methodCalls: [
      ["Principal/query", {
        "accountId": principalsAccountId,
        "filter": {
          "operator": "AND",
          "conditions": [
            {
              "text": p.phrase,
            },
            {"type":"individual"},
          ],
        },
        "limit": p.limit,
      }, "search"],
      ["Principal/get", {
        "accountId": principalsAccountId,
        "#ids": { resultOf: "search", name: "Principal/query", path: "/ids" },
        "properties": ["id","type","name","email","timeZone"],
      }, "fetch"],
    ],
  }

  const res = await client.request(req)

  return decode<FindPeoplePrincipalGetResponse>(req, res, "fetch")
}
