// Code generated by jmapc. DO NOT EDIT.
// Source: queries/InstallSieveScript.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { BlobUploadResponse, SieveScriptSetResponse } from "./types.js"

// InstallSieveScriptParams holds the values InstallSieveScript leaves open.
export interface InstallSieveScriptParams {
  // The octets as text, which the server encodes as UTF-8.
  script: string

  // The user-visible name of the script, which is unique within the account.
  // Null asks the server to choose one.
  name: string
}

// InstallSieveScript uploads a filtering script, stores it, and puts it into
// service, in one request. If the script does not parse, nothing is stored
// and whatever was running keeps running: the activation only happens once
// the rest of the call has succeeded.
//
// It makes Blob/upload and SieveScript/set calls in a single request, so that
// 2 dependent calls cost one round trip. It returns the response to the
// SieveScript/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function installSieveScript(client: Client, p: InstallSieveScriptParams): Promise<SieveScriptSetResponse> {
  const blobAccountId = await client.primaryAccountId("urn:ietf:params:jmap:blob")
  const sieveAccountId = await client.primaryAccountId("urn:ietf:params:jmap:sieve")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    methodCalls: [
      // A script's text is a blob, not a property, so it goes up first. The
      // blob extension lets that happen here rather than as a separate
      // upload.
      ["Blob/upload", {
        "accountId": blobAccountId,
        "create": {
          "text": {
            "data": [
              {
                "data:asText": p.script,
              },
            ],
            "type": "application/sieve",
          },
        },
      }, "upload"],
      // Both onSuccess arguments refer to the script created here, before the
      // server has given it an id. Deactivation happens first, so there is no
      // moment with two active scripts.
      ["SieveScript/set", {
        "accountId": sieveAccountId,
        "create": {
          "filter": {
            "name": p.name,
            "blobId": "#text",
          },
        },
        "onSuccessDeactivateScript": true,
        "onSuccessActivateScript": "#filter",
      }, "install"],
    ],
  }

  const res = await client.request(req)

  return decode<SieveScriptSetResponse>(req, res, "install")
}
