// Code generated by jmapc. DO NOT EDIT.
// Source: queries/InstallSieveScript.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { BlobUploadResponse, Id, SieveScriptSetResponse } from "./types.js"

// InstallSieveScriptParams holds the values InstallSieveScript leaves open.
export interface InstallSieveScriptParams {
  // The octets as text, which the server encodes as UTF-8.
  script: string

  // The user-visible name of the script, which is unique within the account.
  // Null asks the server to choose one.
  name: string
}

// installSieveScriptText is the creation id InstallSieveScript gives a record
// it creates, which the response reports it under.
export const installSieveScriptText: Id = "text"

// installSieveScriptFilter is the creation id InstallSieveScript gives a
// record it creates, which the response reports it under.
export const installSieveScriptFilter: Id = "filter"

// InstallSieveScript uploads a filtering script, stores it, and puts it into
// service, in one request. If the script does not parse, nothing is stored
// and whatever was running keeps running: the activation only happens once
// the rest of the call has succeeded.
//
// It makes Blob/upload and SieveScript/set calls in a single request, so that
// 2 dependent calls cost one round trip. It returns the response to the
// SieveScript/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function installSieveScript(client: Client, p: InstallSieveScriptParams): Promise<SieveScriptSetResponse> {
  const blobAccountId = await client.primaryAccountId("urn:ietf:params:jmap:blob")
  const sieveAccountId = await client.primaryAccountId("urn:ietf:params:jmap:sieve")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    methodCalls: [
      // A script's text is a blob, not a property, so it goes up first. The
      // blob extension lets that happen here rather than as a separate
      // upload.
      ["Blob/upload", {
        "accountId": blobAccountId,
        "create": {
          "text": {
            "data": [
              {
                "data:asText": p.script,
              },
            ],
            "type": "application/sieve",
          },
        },
      }, "upload"],
      // Both onSuccess arguments refer to the script created here, before the
      // server has given it an id. Deactivation happens first, so there is no
      // moment with two active scripts.
      ["SieveScript/set", {
        "accountId": sieveAccountId,
        "create": {
          "filter": {
            "name": p.name,
            "blobId": "#text",
          },
        },
        "onSuccessDeactivateScript": true,
        "onSuccessActivateScript": "#filter",
      }, "install"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "install")) throw failed
  const out = decode<SieveScriptSetResponse>(req, res, "install")
  if (failed) {
    failed.result = out
    throw failed
  }

  const refused0 = decode<BlobUploadResponse>(req, res, "upload")
  const failures: SetFailure[] = []
  collectSetErrors("Blob/upload", "upload", {
    notCreated: refused0.notCreated,
  }, failures)
  collectSetErrors("SieveScript/set", "install", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
