// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ListInboxEmails.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { EmailAddress, EmailQueryResponse, Id, UTCDate } from "./types.js"

// ListInboxEmailsParams holds the values ListInboxEmails leaves open.
export interface ListInboxEmailsParams {
  // Matches emails in this mailbox.
  mailboxId: Id

  // The maximum number of ids to return.
  limit: number
}

// ListInboxEmailsEmail holds the properties of Email that the Email/get call
// in ListInboxEmails asks for.
export interface ListInboxEmailsEmail {
  // The id of the email.
  id: Id

  // The id of the thread the email belongs to.
  threadId: Id

  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate

  // A short plain-text excerpt of the message body.
  preview: string

  // Whether the message has at least one part the server considers an
  // attachment.
  hasAttachment: boolean
}

// ListInboxEmailsEmailGetResponse holds the response to the Email/get call in
// ListInboxEmails.
export interface ListInboxEmailsEmailGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: ListInboxEmailsEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// ListInboxEmails returns the most recent emails in one mailbox, newest
// first.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Email/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function listInboxEmails(client: Client, p: ListInboxEmailsParams): Promise<ListInboxEmailsEmailGetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      // Find the ids of the matching emails.
      ["Email/query", {
        "accountId": mailAccountId,
        "filter": {
          "inMailbox": p.mailboxId,
        },
        "sort": [{"property":"receivedAt","isAscending":false}],
        "limit": p.limit,
      }, "search"],
      // Fetch them in the same request, so the ids never make a round trip.
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "search", name: "Email/query", path: "/ids" },
        "properties": ["id","threadId","subject","from","receivedAt","preview","hasAttachment"],
      }, "fetch"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "fetch")) throw failed
  const out = decode<ListInboxEmailsEmailGetResponse>(req, res, "fetch")
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
