// Code generated by jmapc. DO NOT EDIT.
// Source: queries/MailQuota.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { Id, QuotaQueryResponse } from "./types.js"

// MailQuotaQuota holds the properties of Quota that the Quota/get call in
// MailQuota asks for.
export interface MailQuotaQuota {
  // The id of the quota.
  id: Id

  // The name of the quota, which is unique within its scope and resourceType.
  name: string

  // Who the limit applies to: "account" for this account alone, "domain" for
  // everyone in the domain, or "global" for the whole server.
  scope: string

  // How much of the resource is in use, in whatever the resourceType counts.
  used: number

  // The point beyond which the server refuses to store more.
  hardLimit: number

  // The point at which the server would like the client to warn the user,
  // which it sets below the hard limit so that there is time to do something
  // about it.
  warnLimit: number | null

  // The point beyond which the server starts refusing some operations while
  // still allowing others, such as accepting mail but not letting the user
  // send any.
  softLimit: number | null

  // A description of the quota, meant to be shown to the user.
  description: string | null
}

// MailQuotaQuotaGetResponse holds the response to the Quota/get call in
// MailQuota.
export interface MailQuotaQuotaGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Quota/changes.
  state: string

  // The records that were found, in an undefined order.
  list: MailQuotaQuota[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// MailQuota reports how much of the account's mail storage is used. An
// account may be under several quotas at once, so the filter narrows it to
// the one a mail client would show: the octets it is allowed for mail.
//
// It makes Quota/query and Quota/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Quota/get call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:quota is used, which costs a session
// lookup on first use.
export async function mailQuota(client: Client): Promise<MailQuotaQuotaGetResponse> {
  const quotaAccountId = await client.primaryAccountId("urn:ietf:params:jmap:quota")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:quota"],
    methodCalls: [
      ["Quota/query", {
        "accountId": quotaAccountId,
        "filter": {"operator":"AND","conditions":[{"resourceType":"octets"},{"type":"Mail"}]},
        "sort": [{"property":"used","isAscending":false}],
      }, "search"],
      ["Quota/get", {
        "accountId": quotaAccountId,
        "#ids": { resultOf: "search", name: "Quota/query", path: "/ids" },
        "properties": ["id","name","scope","used","hardLimit","warnLimit","softLimit","description"],
      }, "fetch"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "fetch")) throw failed
  const out = decode<MailQuotaQuotaGetResponse>(req, res, "fetch")
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
