// Code generated by jmapc. DO NOT EDIT.
// Source: queries/MarkEmailRead.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { EmailSetResponse, Id } from "./types.js"

// MarkEmailReadParams holds the values MarkEmailRead leaves open.
export interface MarkEmailReadParams {
  // The id of the record this entry applies to.
  //
  // A map of record id to the patch to apply to it.
  emailId: Id
}

// MarkEmailRead sets the $seen keyword on one email.
//
// It makes one Email/set call in a single request, so that the server is
// asked once. It returns the response to the Email/set call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
export async function markEmailRead(client: Client, p: MarkEmailReadParams): Promise<EmailSetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Email/set", {
        "accountId": mailAccountId,
        "update": {
          [p.emailId]: {"keywords/$seen":true},
        },
      }, "mark"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "mark")) throw failed
  const out = decode<EmailSetResponse>(req, res, "mark")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("Email/set", "mark", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
