// Code generated by jmapc. DO NOT EDIT.
// Source: requests/properties.json

import type { EmailAddress, Id, UTCDate } from "./types.js"

// EmailSummary is what a list of messages shows: enough to draw a row and to
// group the rows into threads, and none of the body.
//
// EmailSummary holds the properties of Email that a call asking for
// @EmailSummary receives.
export interface EmailSummary {
  // The id of the email.
  id: Id

  // The id of the thread the email belongs to.
  threadId: Id

  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate

  // A short plain-text excerpt of the message body.
  preview: string

  // Whether the message has at least one part the server considers an
  // attachment.
  hasAttachment: boolean
}

// EmailWithFlags is a summary and where the message sits: which mailboxes
// hold it, and which keywords it carries. A cache catching up needs both.
//
// EmailWithFlags holds the properties of Email that a call asking for
// @EmailWithFlags receives.
export interface EmailWithFlags extends EmailSummary {
  // The mailboxes the email is in, as a set of ids mapped to true.
  mailboxIds: { [key: Id]: boolean }

  // The keywords set on the email, such as "$seen" or "$flagged", mapped to
  // true.
  keywords: { [key: string]: boolean }
}

