// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ReadMessage.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { EmailAddress, EmailBodyValue, Id, UTCDate } from "./types.js"

// ReadMessageParams holds the values ReadMessage leaves open.
export interface ReadMessageParams {
  // One of the ids in the list.
  //
  // The ids of the records to fetch, or null to fetch all of them.
  emailId: Id
}

// ReadMessageEmailBodyPart holds the properties of EmailBodyPart that the
// Email/get call in ReadMessage asks for.
export interface ReadMessageEmailBodyPart {
  // Identifies the part's content within the bodyValues map, or null if the
  // part has no body of its own.
  partId: string | null

  // The id of the blob holding the raw content, or null for a multipart part.
  blobId: Id | null

  // The media type of the part.
  type: string

  // The character set of the part, for textual media types.
  charset: string | null

  // The size of the decoded content in octets.
  size: number

  // The filename the part should be saved as, if it names one.
  name: string | null

  // The Content-Disposition of the part, such as "inline" or "attachment".
  disposition: string | null

  // The Content-ID of the part, which inline images are referenced by.
  cid: string | null

  // The parts of a multipart part, or null if this part is not multipart.
  subParts: ReadMessageEmailBodyPart[] | null
}

// ReadMessageEmail holds the properties of Email that the Email/get call in
// ReadMessage asks for.
export interface ReadMessageEmail {
  // The id of the email.
  id: Id

  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // The To header field value.
  to: EmailAddress[] | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate

  // The full MIME structure of the message body.
  bodyStructure: ReadMessageEmailBodyPart

  // The parts to display as the plain-text body of the message.
  textBody: ReadMessageEmailBodyPart[]

  // The parts to display as the HTML body of the message.
  htmlBody: ReadMessageEmailBodyPart[]

  // The parts to present as attachments rather than as body content.
  attachments: ReadMessageEmailBodyPart[]

  // The decoded content of the body parts that were fetched, keyed by partId.
  bodyValues: { [key: string]: EmailBodyValue }

  // The List-Id header field, or the last of them where the message has
  // several, decoded and unfolded into text.
  "header:List-Id:asText": string | null

  // The List-Post header field, or the last of them where the message has
  // several, parsed as a list of URLs.
  "header:List-Post:asURLs": string[] | null

  // The Delivery-Date header field, or the last of them where the message has
  // several, parsed as a date.
  "header:Delivery-Date:asDate": Date | null
}

// ReadMessageEmailGetResponse holds the response to the Email/get call in
// ReadMessage.
export interface ReadMessageEmailGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: ReadMessageEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// ReadMessage fetches one message for display: its text, the parts a viewer
// needs to lay out, and the header fields a mailing list adds. What comes
// back is typed down to the header field: a List-Id is a string and a
// Resent-To is a list of addresses, because the form asked for decides it.
//
// It makes one Email/get call in a single request, so that the server is
// asked once. It returns the response to the Email/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function readMessage(client: Client, p: ReadMessageParams): Promise<ReadMessageEmailGetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      // bodyProperties narrows the parts themselves, all the way down through
      // subParts, which properties alone cannot reach.
      ["Email/get", {
        "accountId": mailAccountId,
        "ids": [
          p.emailId,
        ],
        "properties": ["id","subject","from","to","receivedAt","bodyStructure","textBody","htmlBody","attachments","bodyValues","header:List-Id:asText","header:List-Post:asURLs","header:Delivery-Date:asDate"],
        "bodyProperties": ["partId","blobId","type","charset","size","name","disposition","cid","subParts"],
        "fetchTextBodyValues": true,
        "maxBodyValueBytes": 262144,
      }, "fetch"],
    ],
  }

  const res = await client.request(req)

  return decode<ReadMessageEmailGetResponse>(req, res, "fetch")
}
