// Code generated by jmapc. DO NOT EDIT.
// Source: requests/ReadAttachedMessage.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { EmailAddress, EmailBodyValue, Id } from "./types.js"

// ReadAttachedMessageParams holds the values ReadAttachedMessage leaves open.
export interface ReadAttachedMessageParams {
  // One of the ids in the list.
  //
  // The ids of the blobs to parse as messages.
  blobId: Id
}

// ReadAttachedMessageParseEmailBodyPart holds the properties of EmailBodyPart
// that the Email/parse call in ReadAttachedMessage asks for.
export interface ReadAttachedMessageParseEmailBodyPart {
  // Identifies the part's content within the bodyValues map, or null if the
  // part has no body of its own.
  partId: string | null

  // The media type of the part.
  type: string

  // The size of the decoded content in octets.
  size: number
}

// ReadAttachedMessageParseEmail holds the properties of Email that the
// Email/parse call in ReadAttachedMessage asks for.
export interface ReadAttachedMessageParseEmail {
  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // The Date header field value.
  sentAt: Date | null

  // The parts to display as the plain-text body of the message.
  textBody: ReadAttachedMessageParseEmailBodyPart[]

  // The decoded content of the body parts that were fetched, keyed by partId.
  bodyValues: { [key: string]: EmailBodyValue }
}

// ReadAttachedMessageParseResponse holds the response to the Email/parse call
// in ReadAttachedMessage.
export interface ReadAttachedMessageParseResponse {
  // The id of the account to operate on.
  accountId: Id

  // A map of blob id to the email parsed from it. The email has no id,
  // mailboxIds, keywords, or receivedAt, because it is not a record in the
  // account.
  parsed: { [key: Id]: ReadAttachedMessageParseEmail } | null

  // The ids of the blobs that exist but do not hold a message the server
  // could parse.
  notParsable: Id[] | null

  // The ids of the blobs that do not exist.
  notFound: Id[] | null
}

// ReadAttachedMessage reads a message sent as an attachment, for display,
// without filing it in the account. The parsed messages come back keyed by
// the blob they were read from, each typed down to the properties asked for.
//
// It makes one Email/parse call in a single request, so that the server is
// asked once. It returns the response to the Email/parse call.
//
// The request does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
export async function readAttachedMessage(client: Client, p: ReadAttachedMessageParams): Promise<ReadAttachedMessageParseResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Email/parse", {
        "accountId": mailAccountId,
        "blobIds": [
          p.blobId,
        ],
        "properties": ["subject","from","sentAt","textBody","bodyValues"],
        "bodyProperties": ["partId","type","size"],
        "fetchTextBodyValues": true,
      }, "parse"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "parse")) throw failed
  const out = decode<ReadAttachedMessageParseResponse>(req, res, "parse")
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
