// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RecentlyShared.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { ShareNotificationGetResponse, ShareNotificationQueryResponse, UTCDate } from "./types.js"

// RecentlySharedParams holds the values RecentlyShared leaves open.
export interface RecentlySharedParams {
  // Matches notifications created at or after this time.
  since: UTCDate

  // The maximum number of ids to return.
  limit: number
}

// RecentlyShared reports what other people have shared with the user since a
// known point. Nothing else tells them: a shared mailbox simply appears in an
// account they can see, with no message to say so.
//
// It makes ShareNotification/query and ShareNotification/get calls in a
// single request, so that 2 dependent calls cost one round trip. It returns
// the response to the ShareNotification/get call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:principals is used, which costs a session
// lookup on first use.
export async function recentlyShared(client: Client, p: RecentlySharedParams): Promise<ShareNotificationGetResponse> {
  const principalsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:principals")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:principals"],
    methodCalls: [
      ["ShareNotification/query", {
        "accountId": principalsAccountId,
        "filter": {
          "after": p.since,
        },
        "sort": [{"property":"created","isAscending":false}],
        "limit": p.limit,
      }, "search"],
      ["ShareNotification/get", {
        "accountId": principalsAccountId,
        "#ids": { resultOf: "search", name: "ShareNotification/query", path: "/ids" },
      }, "fetch"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "fetch")) throw failed
  const out = decode<ShareNotificationGetResponse>(req, res, "fetch")
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
