// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RegisterPush.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { Id, PushSubscriptionSetResponse } from "./types.js"

// RegisterPushParams holds the values RegisterPush leaves open.
export interface RegisterPushParams {
  // An id identifying the client and the device it runs on, so that a client
  // which has lost its local state can still find the subscriptions it made.
  // It must not carry an unobfuscated device id: the recommendation is a hash
  // of the device's identifier together with the vendor's own.
  deviceClientId: string

  // The absolute URL the server posts to, which must begin with "https://". A
  // /get never returns it, since it may be private to one device.
  url: string

  // The P-256 ECDH public key, in URL-safe base64.
  publicKey: string

  // The authentication secret, in URL-safe base64.
  authSecret: string
}

// registerPushDevice is the creation id RegisterPush gives a record it
// creates, which the response reports it under.
export const registerPushDevice: Id = "device"

// RegisterPush asks the server to post to a URL when something changes, which
// is how a client that cannot hold a connection open — an app on a phone,
// say — hears about changes at all. The subscription is not live yet: the
// server pushes a verification code to the URL first, and ConfirmPush writes
// it back.
//
// It makes one PushSubscription/set call in a single request, so that the
// server is asked once. It returns the response to the PushSubscription/set
// call.
export async function registerPush(client: Client, p: RegisterPushParams): Promise<PushSubscriptionSetResponse> {
  const req: Request = {
    using: ["urn:ietf:params:jmap:core"],
    methodCalls: [
      // There is no accountId here. A subscription belongs to the credentials
      // that made it, not to an account, so it hears about every account
      // those credentials can see.
      ["PushSubscription/set", {
        "create": {
          "device": {
            "deviceClientId": p.deviceClientId,
            "url": p.url,
            "keys": {
              "p256dh": p.publicKey,
              "auth": p.authSecret,
            },
            "types": ["Email","EmailDelivery"],
          },
        },
      }, "register"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "register")) throw failed
  const out = decode<PushSubscriptionSetResponse>(req, res, "register")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("PushSubscription/set", "register", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
