// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RescheduleOccurrence.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { CalendarEventSetResponse, Id, LocalDateTime } from "./types.js"

// RescheduleOccurrenceParams holds the values RescheduleOccurrence leaves
// open.
export interface RescheduleOccurrenceParams {
  // The id of the record this entry applies to.
  //
  // A map of record id to the patch to apply to it.
  eventId: Id

  // The key this entry is stored under.
  occurrence: LocalDateTime

  // When the event starts, in the event's own time zone.
  newStart: LocalDateTime

  // A short summary of the event.
  newTitle: string
}

// RescheduleOccurrence moves one occurrence of a recurring event without
// touching the rest of the series. The override is keyed by the start the
// recurrence rules gave that occurrence, and its value is a patch to the
// event.
//
// It makes one CalendarEvent/set call in a single request, so that the server
// is asked once. It returns the response to the CalendarEvent/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function rescheduleOccurrence(client: Client, p: RescheduleOccurrenceParams): Promise<CalendarEventSetResponse> {
  const calendarsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:calendars")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:calendars"],
    methodCalls: [
      ["CalendarEvent/set", {
        "accountId": calendarsAccountId,
        "update": {
          [p.eventId]: {
            ["recurrenceOverrides/" + p.occurrence + "/start"]: p.newStart,
            ["recurrenceOverrides/" + p.occurrence + "/title"]: p.newTitle,
          },
        },
        "sendSchedulingMessages": true,
      }, "reschedule"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "reschedule")) throw failed
  const out = decode<CalendarEventSetResponse>(req, res, "reschedule")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("CalendarEvent/set", "reschedule", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
