// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchContacts.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { ContactCardQueryResponse, ContactEmailAddress, ContactName, ContactOrganization, ContactPhone, Id } from "./types.js"

// SearchContactsParams holds the values SearchContacts leaves open.
export interface SearchContactsParams {
  // Matches cards in this address book.
  addressBookId: Id

  // Matches cards where this text appears in any of the properties the other
  // conditions search individually.
  phrase: string

  // The maximum number of ids to return.
  limit: number
}

// SearchContactsAddressBook holds the properties of AddressBook that the
// AddressBook/get call in SearchContacts asks for.
export interface SearchContactsAddressBook {
  // The id of the address book.
  id: Id

  // The user-visible name of the address book, at most 255 octets of UTF-8.
  name: string

  // Whether this is the address book a card goes into when the client does
  // not say. Exactly one address book in an account has this set.
  isDefault: boolean
}

// SearchContactsContactCard holds the properties of ContactCard that the
// ContactCard/get call in SearchContacts asks for.
export interface SearchContactsContactCard {
  // The id of the card.
  id: Id

  // A globally unique identifier for the entity, which survives being copied
  // between address books.
  uid: string

  // The name of the entity.
  name: ContactName

  // The addresses the entity receives mail at, keyed by an id local to the
  // card.
  emails: { [key: Id]: ContactEmailAddress }

  // The numbers the entity can be reached on, keyed by an id local to the
  // card.
  phones: { [key: Id]: ContactPhone }

  // The organizations the entity belongs to, keyed by an id local to the
  // card.
  organizations: { [key: Id]: ContactOrganization }
}

// SearchContactsAddressBookGetResponse holds the response to the
// AddressBook/get call in SearchContacts.
export interface SearchContactsAddressBookGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with AddressBook/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SearchContactsAddressBook[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SearchContactsContactCardGetResponse holds the response to the
// ContactCard/get call in SearchContacts.
export interface SearchContactsContactCardGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with ContactCard/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SearchContactsContactCard[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SearchContactsResult holds the response to each method call SearchContacts
// makes.
export interface SearchContactsResult {
  // The response to the AddressBook/get call, made as "books".
  addressBookGet: SearchContactsAddressBookGetResponse

  // The response to the ContactCard/query call, made as "search".
  contactCardQuery: ContactCardQueryResponse

  // The response to the ContactCard/get call, made as "fetch".
  contactCardGet: SearchContactsContactCardGetResponse
}

// SearchContacts lists the address books and searches one of them in the same
// request, so a contact picker can be filled in with one round trip.
//
// It makes AddressBook/get, ContactCard/query, and ContactCard/get calls in a
// single request, so that 3 dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:contacts is used, which costs a session
// lookup on first use.
export async function searchContacts(client: Client, p: SearchContactsParams): Promise<SearchContactsResult> {
  const contactsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:contacts")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
    methodCalls: [
      // Which address books exist. A picker needs this whether or not the
      // search finds anything.
      ["AddressBook/get", {
        "accountId": contactsAccountId,
        "ids": null,
        "properties": ["id","name","isDefault"],
      }, "books"],
      // The cards matching the phrase, surname first.
      ["ContactCard/query", {
        "accountId": contactsAccountId,
        "filter": {
          "operator": "AND",
          "conditions": [
            {
              "inAddressBook": p.addressBookId,
            },
            {
              "text": p.phrase,
            },
            {"kind":"individual"},
          ],
        },
        "sort": [{"property":"name/surname"},{"property":"name/given"}],
        "limit": p.limit,
      }, "search"],
      // Only the parts a list view shows. A card holds far more than this.
      ["ContactCard/get", {
        "accountId": contactsAccountId,
        "#ids": { resultOf: "search", name: "ContactCard/query", path: "/ids" },
        "properties": ["id","uid","name","emails","phones","organizations"],
      }, "fetch"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  const out = {
    ...(answered(res, "books") ? { addressBookGet: decode<SearchContactsAddressBookGetResponse>(req, res, "books") } : {}),
    ...(answered(res, "search") ? { contactCardQuery: decode<ContactCardQueryResponse>(req, res, "search") } : {}),
    ...(answered(res, "fetch") ? { contactCardGet: decode<SearchContactsContactCardGetResponse>(req, res, "fetch") } : {}),
  } as SearchContactsResult
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
