// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchEmails.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { EmailAddress, EmailQueryResponse, Id, UTCDate } from "./types.js"

// SearchEmailsParams holds the values SearchEmails leaves open.
export interface SearchEmailsParams {
  // Matches emails where this text appears in the body, subject, or any
  // address header field.
  phrase: string

  // Matches emails in this mailbox.
  firstMailboxId: Id

  // Matches emails in this mailbox.
  secondMailboxId: Id

  // The zero-based index of the first result to return. A negative value
  // counts back from the end.
  position: number
}

// SearchEmailsEmail holds the properties of Email that the Email/get call in
// SearchEmails asks for.
export interface SearchEmailsEmail {
  // The id of the email.
  id: Id

  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate
}

// SearchEmailsEmailGetResponse holds the response to the Email/get call in
// SearchEmails.
export interface SearchEmailsEmailGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SearchEmailsEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SearchEmailsResult holds the response to each method call SearchEmails
// makes.
export interface SearchEmailsResult {
  // The response to the Email/query call, made as "search".
  emailQuery: EmailQueryResponse

  // The response to the Email/get call, made as "fetch".
  emailGet: SearchEmailsEmailGetResponse
}

// SearchEmails finds emails matching a phrase in one of two mailboxes, and
// returns both the ids that matched and the emails themselves.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
export async function searchEmails(client: Client, p: SearchEmailsParams): Promise<SearchEmailsResult> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Email/query", {
        "accountId": mailAccountId,
        "filter": {
          "operator": "AND",
          "conditions": [
            {
              "text": p.phrase,
            },
            {
              "operator": "OR",
              "conditions": [
                {
                  "inMailbox": p.firstMailboxId,
                },
                {
                  "inMailbox": p.secondMailboxId,
                },
              ],
            },
            {"hasAttachment":true},
          ],
        },
        "sort": [{"property":"receivedAt","isAscending":false}],
        "collapseThreads": true,
        "position": p.position,
        "limit": 50,
        "calculateTotal": true,
      }, "search"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "search", name: "Email/query", path: "/ids" },
        "properties": ["id","subject","from","receivedAt"],
      }, "fetch"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  const out = {
    ...(answered(res, "search") ? { emailQuery: decode<EmailQueryResponse>(req, res, "search") } : {}),
    ...(answered(res, "fetch") ? { emailGet: decode<SearchEmailsEmailGetResponse>(req, res, "fetch") } : {}),
  } as SearchEmailsResult
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}

// searchEmailsPages walks the whole of what searchEmails returns one part of,
// calling it again for each part until there is none left.
//
// It starts from the position the parameters carry and works the next one out
// from each answer. A window with nothing in it ends the walk rather than
// being yielded, so everything it yields holds something; where the call
// asked for the total, the walk ends without asking for a window that is not
// there.
//
// A failure throws, as it does from the query itself, and leaving the loop
// early sends no further request.
export async function* searchEmailsPages(client: Client, p: SearchEmailsParams): AsyncGenerator<SearchEmailsResult> {
  let start = p.position
  for (;;) {
    p.position = start
    const res = await searchEmails(client, p)
    const window = res.emailQuery
    if (window.ids.length === 0) {
      return
    }
    yield res
    start = window.position + window.ids.length
    if (window.total > 0 && start >= window.total) {
      return
    }
  }
}
