// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchEmails.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { EmailAddress, EmailQueryResponse, Id, UTCDate } from "./types.js"

// SearchEmailsParams holds the values SearchEmails leaves open.
export interface SearchEmailsParams {
  // Matches emails where this text appears in the body, subject, or any
  // address header field.
  phrase: string

  // Matches emails in this mailbox.
  firstMailboxId: Id

  // Matches emails in this mailbox.
  secondMailboxId: Id
}

// SearchEmailsEmail holds the properties of Email that the Email/get call in
// SearchEmails asks for.
export interface SearchEmailsEmail {
  // The id of the email.
  id: Id

  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate
}

// SearchEmailsEmailGetResponse holds the response to the Email/get call in
// SearchEmails.
export interface SearchEmailsEmailGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SearchEmailsEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SearchEmailsResult holds the response to each method call SearchEmails
// makes.
export interface SearchEmailsResult {
  // The response to the Email/query call, made as "search".
  emailQuery: EmailQueryResponse

  // The response to the Email/get call, made as "fetch".
  emailGet: SearchEmailsEmailGetResponse
}

// SearchEmails finds emails matching a phrase in one of two mailboxes, and
// returns both the ids that matched and the emails themselves.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function searchEmails(client: Client, p: SearchEmailsParams): Promise<SearchEmailsResult> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Email/query", {
        "accountId": mailAccountId,
        "filter": {
          "operator": "AND",
          "conditions": [
            {
              "text": p.phrase,
            },
            {
              "operator": "OR",
              "conditions": [
                {
                  "inMailbox": p.firstMailboxId,
                },
                {
                  "inMailbox": p.secondMailboxId,
                },
              ],
            },
            {"hasAttachment":true},
          ],
        },
        "sort": [{"property":"receivedAt","isAscending":false}],
        "collapseThreads": true,
        "limit": 50,
        "calculateTotal": true,
      }, "search"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "search", name: "Email/query", path: "/ids" },
        "properties": ["id","subject","from","receivedAt"],
      }, "fetch"],
    ],
  }

  const res = await client.request(req)

  return {
    emailQuery: decode<EmailQueryResponse>(req, res, "search"),
    emailGet: decode<SearchEmailsEmailGetResponse>(req, res, "fetch"),
  }
}
