// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SendEmail.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { EmailSetResponse, EmailSubmissionSetResponse, Id } from "./types.js"

// SendEmailParams holds the values SendEmail leaves open.
export interface SendEmailParams {
  // The id of the record this entry applies to.
  //
  // The mailboxes the email is in, as a set of ids mapped to true.
  draftsMailboxId: Id

  // The addr-spec of the address.
  fromAddress: string

  // The addr-spec of the address.
  toAddress: string

  // The Subject header field value.
  subject: string

  // The decoded content of the body part.
  body: string

  // The id of the identity to send from.
  identityId: Id

  // The id of the record this entry applies to.
  sentMailboxId: Id
}

// SendEmail writes a message, hands it to the submission server, and files it
// under Sent once the send succeeds — all in one request, so the draft can
// never be left behind in Drafts by a call that failed halfway.
//
// It makes Email/set and EmailSubmission/set calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// EmailSubmission/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function sendEmail(client: Client, p: SendEmailParams): Promise<EmailSubmissionSetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")
  const submissionAccountId = await client.primaryAccountId("urn:ietf:params:jmap:submission")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
    methodCalls: [
      // Create the message. The creation id "draft" names it for the rest of
      // the request, before the server has assigned it a real one.
      ["Email/set", {
        "accountId": mailAccountId,
        "create": {
          "draft": {
            "mailboxIds": {
              [p.draftsMailboxId]: true,
            },
            "keywords": {"$draft":true},
            "from": [
              {
                "email": p.fromAddress,
              },
            ],
            "to": [
              {
                "email": p.toAddress,
              },
            ],
            "subject": p.subject,
            "bodyStructure": {"partId":"text","type":"text/plain"},
            "bodyValues": {
              "text": {
                "value": p.body,
              },
            },
          },
        },
      }, "write"],
      // Submit it for delivery, referring to the email by its creation id. On
      // success, move it out of Drafts and into Sent and drop the $draft
      // keyword, which the submission server does as part of the same call.
      ["EmailSubmission/set", {
        "accountId": submissionAccountId,
        "create": {
          "send": {
            "emailId": "#draft",
            "identityId": p.identityId,
          },
        },
        "onSuccessUpdateEmail": {
          "#send": {
            ["mailboxIds/" + p.draftsMailboxId]: null,
            ["mailboxIds/" + p.sentMailboxId]: true,
            "keywords/$draft": null,
          },
        },
      }, "send"],
    ],
  }

  const res = await client.request(req)

  return decode<EmailSubmissionSetResponse>(req, res, "send")
}
