// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SyncEmails.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { EmailChangesResponse, Id, UTCDate } from "./types.js"

// SyncEmailsParams holds the values SyncEmails leaves open.
export interface SyncEmailsParams {
  // The state string the client already has, as returned by an earlier
  // Email/get or Email/changes.
  sinceState: string
}

// SyncEmailsEmail holds the properties of Email that the Email/get call in
// SyncEmails asks for.
export interface SyncEmailsEmail {
  // The id of the email.
  id: Id

  // The id of the thread the email belongs to.
  threadId: Id

  // The mailboxes the email is in, as a set of ids mapped to true.
  mailboxIds: { [key: Id]: boolean }

  // The keywords set on the email, such as "$seen" or "$flagged", mapped to
  // true.
  keywords: { [key: string]: boolean }

  // The Subject header field value.
  subject: string | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate
}

// SyncEmailsEmail2 holds the properties of Email that the Email/get call in
// SyncEmails asks for.
export interface SyncEmailsEmail2 {
  // The id of the email.
  id: Id

  // The mailboxes the email is in, as a set of ids mapped to true.
  mailboxIds: { [key: Id]: boolean }

  // The keywords set on the email, such as "$seen" or "$flagged", mapped to
  // true.
  keywords: { [key: string]: boolean }
}

// SyncEmailsCreatedResponse holds the response to the Email/get call in
// SyncEmails.
export interface SyncEmailsCreatedResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SyncEmailsEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SyncEmailsUpdatedResponse holds the response to the Email/get call in
// SyncEmails.
export interface SyncEmailsUpdatedResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SyncEmailsEmail2[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SyncEmailsResult holds the response to each method call SyncEmails makes.
export interface SyncEmailsResult {
  // The response to the Email/changes call, made as "changes".
  changes: EmailChangesResponse

  // The response to the Email/get call, made as "created".
  created: SyncEmailsCreatedResponse

  // The response to the Email/get call, made as "updated".
  updated: SyncEmailsUpdatedResponse
}

// SyncEmails fetches the emails that have changed since a known state, so a
// local cache can catch up without refetching everything.
//
// It makes Email/changes, Email/get, and Email/get calls in a single request,
// so that 3 dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
export async function syncEmails(client: Client, p: SyncEmailsParams): Promise<SyncEmailsResult> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Email/changes", {
        "accountId": mailAccountId,
        "sinceState": p.sinceState,
        "maxChanges": 128,
      }, "changes"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "changes", name: "Email/changes", path: "/created" },
        "properties": ["id","threadId","mailboxIds","keywords","subject","receivedAt"],
      }, "created"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "changes", name: "Email/changes", path: "/updated" },
        "properties": ["id","mailboxIds","keywords"],
      }, "updated"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  const out = {
    ...(answered(res, "changes") ? { changes: decode<EmailChangesResponse>(req, res, "changes") } : {}),
    ...(answered(res, "created") ? { created: decode<SyncEmailsCreatedResponse>(req, res, "created") } : {}),
    ...(answered(res, "updated") ? { updated: decode<SyncEmailsUpdatedResponse>(req, res, "updated") } : {}),
  } as SyncEmailsResult
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
