// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SyncEmails.jmap.json

import { type Client, type Request, decode } from "./client.js"
import type { EmailChangesResponse, Id, UTCDate } from "./types.js"

// SyncEmailsParams holds the values SyncEmails leaves open.
export interface SyncEmailsParams {
  // The state string the client already has, as returned by an earlier
  // Email/get or Email/changes.
  sinceState: string
}

// SyncEmailsEmail holds the properties of Email that the Email/get call in
// SyncEmails asks for.
export interface SyncEmailsEmail {
  // The id of the email.
  id: Id

  // The id of the thread the email belongs to.
  threadId: Id

  // The mailboxes the email is in, as a set of ids mapped to true.
  mailboxIds: { [key: Id]: boolean }

  // The keywords set on the email, such as "$seen" or "$flagged", mapped to
  // true.
  keywords: { [key: string]: boolean }

  // The Subject header field value.
  subject: string | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate
}

// SyncEmailsEmail2 holds the properties of Email that the Email/get call in
// SyncEmails asks for.
export interface SyncEmailsEmail2 {
  // The id of the email.
  id: Id

  // The mailboxes the email is in, as a set of ids mapped to true.
  mailboxIds: { [key: Id]: boolean }

  // The keywords set on the email, such as "$seen" or "$flagged", mapped to
  // true.
  keywords: { [key: string]: boolean }
}

// SyncEmailsEmailGetResponse holds the response to the Email/get call in
// SyncEmails.
export interface SyncEmailsEmailGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SyncEmailsEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SyncEmailsEmailGet2Response holds the response to the Email/get call in
// SyncEmails.
export interface SyncEmailsEmailGet2Response {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: SyncEmailsEmail2[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// SyncEmailsResult holds the response to each method call SyncEmails makes.
export interface SyncEmailsResult {
  // The response to the Email/changes call, made as "changes".
  emailChanges: EmailChangesResponse

  // The response to the Email/get call, made as "created".
  emailGet: SyncEmailsEmailGetResponse

  // The response to the Email/get call, made as "updated".
  emailGet2: SyncEmailsEmailGet2Response
}

// SyncEmails fetches the emails that have been created since a known state,
// so a local cache can catch up without refetching everything.
//
// It makes Email/changes, Email/get, and Email/get calls in a single request,
// so that 3 dependent calls cost one round trip.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function syncEmails(client: Client, p: SyncEmailsParams): Promise<SyncEmailsResult> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
    methodCalls: [
      ["Email/changes", {
        "accountId": mailAccountId,
        "sinceState": p.sinceState,
        "maxChanges": 128,
      }, "changes"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "changes", name: "Email/changes", path: "/created" },
        "properties": ["id","threadId","mailboxIds","keywords","subject","receivedAt"],
      }, "created"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "changes", name: "Email/changes", path: "/updated" },
        "properties": ["id","mailboxIds","keywords"],
      }, "updated"],
    ],
  }

  const res = await client.request(req)

  return {
    emailChanges: decode<EmailChangesResponse>(req, res, "changes"),
    emailGet: decode<SyncEmailsEmailGetResponse>(req, res, "created"),
    emailGet2: decode<SyncEmailsEmailGet2Response>(req, res, "updated"),
  }
}
