// Code generated by jmapc. DO NOT EDIT.
// Source: queries/UpdateContactEmail.jmap.json

import { type Client, type Request, type Response, type SetFailure, MethodErrors, answered, decode, SetErrors, collectSetErrors } from "./client.js"
import type { ContactCardSetResponse, Id } from "./types.js"

// UpdateContactEmailParams holds the values UpdateContactEmail leaves open.
export interface UpdateContactEmailParams {
  // The id of the record this entry applies to.
  //
  // A map of record id to the patch to apply to it.
  cardId: Id

  // The id of the record this entry applies to.
  emailKey: Id

  // The address itself, as an addr-spec.
  address: string
}

// UpdateContactEmail changes one address on a card and makes it the preferred
// one, sending the two values that changed rather than the whole card.
//
// It makes one ContactCard/set call in a single request, so that the server
// is asked once. It returns the response to the ContactCard/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
export async function updateContactEmail(client: Client, p: UpdateContactEmailParams): Promise<ContactCardSetResponse> {
  const contactsAccountId = await client.primaryAccountId("urn:ietf:params:jmap:contacts")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
    methodCalls: [
      ["ContactCard/set", {
        "accountId": contactsAccountId,
        "update": {
          [p.cardId]: {
            ["emails/" + p.emailKey + "/address"]: p.address,
            ["emails/" + p.emailKey + "/pref"]: 1,
          },
        },
      }, "update"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "update")) throw failed
  const out = decode<ContactCardSetResponse>(req, res, "update")
  if (failed) {
    failed.result = out
    throw failed
  }

  const failures: SetFailure[] = []
  collectSetErrors("ContactCard/set", "update", {
    notCreated: out.notCreated,
    notUpdated: out.notUpdated,
    notDestroyed: out.notDestroyed,
  }, failures)
  if (failures.length > 0) throw new SetErrors(failures, out)

  return out
}
