// Code generated by jmapc. DO NOT EDIT.
// Source: queries/VerifiedSignatures.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { EmailAddress, EmailQueryResponse, Id, UTCDate } from "./types.js"

// VerifiedSignaturesParams holds the values VerifiedSignatures leaves open.
export interface VerifiedSignaturesParams {
  // Matches emails in this mailbox.
  mailboxId: Id

  // The maximum number of ids to return.
  limit: number
}

// VerifiedSignaturesEmail holds the properties of Email that the Email/get
// call in VerifiedSignatures asks for.
export interface VerifiedSignaturesEmail {
  // The id of the email.
  id: Id

  // The Subject header field value.
  subject: string | null

  // The From header field value.
  from: EmailAddress[] | null

  // When the email was received, which is what the mailbox sorts on by
  // default.
  receivedAt: UTCDate

  // What the server made of the message's signature when it last looked:
  // "unknown", "signed", "signed/verified", "signed/failed",
  // "encrypted+signed/verified", or "encrypted+signed/failed". Null for a
  // message with no signature.
  smimeStatus: string | null

  // What the server made of the signature when the message arrived, taking
  // the same values as smimeStatus: "unknown", "signed", "signed/verified",
  // "signed/failed", "encrypted+signed/verified", or
  // "encrypted+signed/failed". It can differ from smimeStatus: a certificate
  // valid on delivery may have expired since, and it is the state at delivery
  // that says whether the message was trustworthy when it was sent.
  smimeStatusAtDelivery: string | null

  // What went wrong with the verification, in terms meant for a person to
  // read.
  smimeErrors: string[] | null

  // When the server last checked the signature.
  smimeVerifiedAt: UTCDate | null
}

// VerifiedSignaturesEmailGetResponse holds the response to the Email/get call
// in VerifiedSignatures.
export interface VerifiedSignaturesEmailGetResponse {
  // The id of the account to operate on.
  accountId: Id

  // A string encoding the current state of the type on the server, for use
  // with Email/changes.
  state: string

  // The records that were found, in an undefined order.
  list: VerifiedSignaturesEmail[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// VerifiedSignatures finds signed messages in a mailbox and reports what
// became of each signature. The server does the cryptography: the signature
// covers the raw message, which a client never sees once the server has taken
// it apart.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Email/get call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
export async function verifiedSignatures(client: Client, p: VerifiedSignaturesParams): Promise<VerifiedSignaturesEmailGetResponse> {
  const mailAccountId = await client.primaryAccountId("urn:ietf:params:jmap:mail")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:smimeverify"],
    methodCalls: [
      ["Email/query", {
        "accountId": mailAccountId,
        "filter": {
          "operator": "AND",
          "conditions": [
            {
              "inMailbox": p.mailboxId,
            },
            {"hasSmime":true},
          ],
        },
        "sort": [{"property":"receivedAt","isAscending":false}],
        "limit": p.limit,
      }, "search"],
      ["Email/get", {
        "accountId": mailAccountId,
        "#ids": { resultOf: "search", name: "Email/query", path: "/ids" },
        "properties": ["id","subject","from","receivedAt","smimeStatus","smimeStatusAtDelivery","smimeErrors","smimeVerifiedAt"],
      }, "fetch"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  if (failed && !answered(res, "fetch")) throw failed
  const out = decode<VerifiedSignaturesEmailGetResponse>(req, res, "fetch")
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
