// Code generated by jmapc. DO NOT EDIT.
// Source: requests

import type { Client } from "./client.js"

// verify checks every request in this directory against the session, and throws
// VerifyErrors with everything that would stop one of them from being sent.
// Call it as the program starts, to learn then rather than when a request is
// first sent. See Client.verify for what it checks.
export async function verify(client: Client): Promise<void> {
  await client.verify([
    {
      name: "Agenda",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:calendars"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:calendars"],
    },
    {
      name: "AttachNote",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:mail"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:mail"],
    },
    {
      name: "CheckSieveScript",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    },
    {
      name: "ConfirmPush",
      using: ["urn:ietf:params:jmap:core"],
      calls: 1,
      primaryAccounts: [],
    },
    {
      name: "CreateContact",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:contacts"],
    },
    {
      name: "CreateEvent",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:calendars"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:calendars"],
    },
    {
      name: "CreateMailbox",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "FileIntoNewMailbox",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "FindPeople",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:principals"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:principals"],
    },
    {
      name: "InstallSieveScript",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    },
    {
      name: "ListInboxEmails",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "MailQuota",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:quota"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:quota"],
    },
    {
      name: "MarkEmailRead",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "ReadAttachedMessage",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "ReadMessage",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "RecentlyShared",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:principals"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:principals"],
    },
    {
      name: "RegisterPush",
      using: ["urn:ietf:params:jmap:core"],
      calls: 1,
      primaryAccounts: [],
    },
    {
      name: "RescheduleOccurrence",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:calendars"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:calendars"],
    },
    {
      name: "SearchContacts",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
      calls: 3,
      primaryAccounts: ["urn:ietf:params:jmap:contacts"],
    },
    {
      name: "SearchEmails",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "SendEmail",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
    },
    {
      name: "SendReadReceipt",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mdn"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:mdn"],
    },
    {
      name: "SyncEmails",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
      calls: 3,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "UpdateContactEmail",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
      calls: 1,
      primaryAccounts: ["urn:ietf:params:jmap:contacts"],
    },
    {
      name: "VerifiedSignatures",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:smimeverify"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:mail"],
    },
    {
      name: "WhatUsesBlob",
      using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob"],
      calls: 2,
      primaryAccounts: ["urn:ietf:params:jmap:blob"],
    },
  ])
}
