// Code generated by jmapc. DO NOT EDIT.
// Source: queries/WhatUsesBlob.jmap.json

import { type Client, type Request, type Response, MethodErrors, answered, decode } from "./client.js"
import type { BlobLookupResponse, Id } from "./types.js"

// WhatUsesBlobParams holds the values WhatUsesBlob leaves open.
export interface WhatUsesBlobParams {
  // One of the ids in the list.
  //
  // The ids of the blobs to look for.
  blobId: Id
}

// WhatUsesBlobBlobData holds the properties of BlobData that the Blob/get
// call in WhatUsesBlob asks for.
export interface WhatUsesBlobBlobData {
  // The id of the blob.
  id: Id

  // The octets as text, or null where they are not valid UTF-8.
  "data:asText": string | null

  // The size of the whole blob in octets, whatever range was asked for.
  size: number

  // The digest of the blob under the sha-256 algorithm, as base64.
  "digest:sha-256": unknown
}

// WhatUsesBlobPeekResponse holds the response to the Blob/get call in
// WhatUsesBlob.
export interface WhatUsesBlobPeekResponse {
  // The id of the account to operate on.
  accountId: Id

  // The blobs that were found.
  list: WhatUsesBlobBlobData[]

  // The ids that were requested but do not exist.
  notFound: Id[]
}

// WhatUsesBlobResult holds the response to each method call WhatUsesBlob
// makes.
export interface WhatUsesBlobResult {
  // The response to the Blob/lookup call, made as "uses".
  uses: BlobLookupResponse

  // The response to the Blob/get call, made as "peek".
  peek: WhatUsesBlobPeekResponse
}

// WhatUsesBlob reports which records refer to a blob and reads a little of
// it, which is how a client answers whether deleting a message would take an
// attachment with it.
//
// It makes Blob/lookup and Blob/get calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:blob is used, which costs a session lookup
// on first use.
export async function whatUsesBlob(client: Client, p: WhatUsesBlobParams): Promise<WhatUsesBlobResult> {
  const blobAccountId = await client.primaryAccountId("urn:ietf:params:jmap:blob")

  const req: Request = {
    using: ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob"],
    methodCalls: [
      ["Blob/lookup", {
        "accountId": blobAccountId,
        "typeNames": ["Email","Mailbox"],
        "ids": [
          p.blobId,
        ],
      }, "uses"],
      ["Blob/get", {
        "accountId": blobAccountId,
        "ids": [
          p.blobId,
        ],
        "properties": ["data:asText","size","digest:sha-256"],
        "length": 4096,
      }, "peek"],
    ],
  }

  let res: Response
  let failed: MethodErrors | undefined
  try {
    res = await client.request(req)
  } catch (e) {
    if (!(e instanceof MethodErrors)) throw e
    res = e.response
    failed = e
  }

  const out = {
    ...(answered(res, "uses") ? { uses: decode<BlobLookupResponse>(req, res, "uses") } : {}),
    ...(answered(res, "peek") ? { peek: decode<WhatUsesBlobPeekResponse>(req, res, "peek") } : {}),
  } as WhatUsesBlobResult
  if (failed) {
    failed.result = out
    throw failed
  }
  return out
}
