// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CheckSieveScript.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{BlobUploadResponse, SieveScriptValidateResponse};

/// CheckSieveScriptParams holds the values CheckSieveScript leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CheckSieveScriptParams {
    /// The octets as text, which the server encodes as UTF-8.
    pub script: String,
}

/// CheckSieveScript reports whether a script would parse and whether the
/// server supports what it asks for, without storing it. It is what an editor
/// calls while the user is still typing.
///
/// It makes Blob/upload and SieveScript/validate calls in a single request,
/// so that 2 dependent calls cost one round trip. It returns the response to
/// the SieveScript/validate call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn check_sieve_script<T: Transport>(
    client: &Client<T>,
    p: CheckSieveScriptParams,
) -> Result<SieveScriptValidateResponse, Error> {
    let blob_account_id = client
        .primary_account_id("urn:ietf:params:jmap:blob")
        .await?;
    let sieve_account_id = client
        .primary_account_id("urn:ietf:params:jmap:sieve")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:blob".to_string(),
            "urn:ietf:params:jmap:sieve".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Blob/upload".to_string(),
                json!({
                    "accountId": blob_account_id,
                    "create": {
                        "draft": {
                            "data": [
                                {
                                    "data:asText": p.script,
                                },
                            ],
                            "type": "application/sieve",
                        },
                    },
                }),
                "upload".to_string(),
            ),
            Invocation(
                "SieveScript/validate".to_string(),
                json!({
                    "accountId": sieve_account_id,
                    "#blobId": {"resultOf": "upload", "name": "Blob/upload", "path": "/created/draft/id"},
                }),
                "check".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    let out = decode::<SieveScriptValidateResponse>(&req, &res, "check")?;

    let refused0 = decode::<BlobUploadResponse>(&req, &res, "upload")?;
    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "Blob/upload",
        "upload",
        &[("notCreated", refused0.not_created.as_ref())],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
