// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ConfirmPush.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{Id, PushSubscriptionSetResponse, UtcDate};

/// ConfirmPushParams holds the values ConfirmPush leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ConfirmPushParams {
    /// The id of the record this entry applies to.
    ///
    /// Patches to apply, keyed by subscription id. This is how the
    /// verification code is written back and how the expiry is extended; the
    /// url and keys cannot be changed, only replaced by destroying the
    /// subscription and creating another.
    pub subscription_id: Id,

    /// The code proving the client controls the URL. It must be null when the
    /// subscription is created; the server then pushes a code to the URL, and
    /// the client writes it back here. Until that happens the server makes no
    /// further requests to the URL, which is what stops a subscription being
    /// used to attack a third party.
    pub verification_code: String,

    /// When the subscription lapses. The server may impose one where the
    /// client gives none, or shorten the one it gives, and a client extends
    /// the lifetime by writing a later time here.
    pub expires: UtcDate,
}

/// ConfirmPush writes back the code the server pushed to the subscription's
/// URL. Until this happens the server sends nothing else, which is what keeps
/// a subscription from being pointed at a third party and used to flood them.
///
/// It makes one PushSubscription/set call in a single request, so that the
/// server is asked once. It returns the response to the PushSubscription/set
/// call.
pub async fn confirm_push<T: Transport>(
    client: &Client<T>,
    p: ConfirmPushParams,
) -> Result<PushSubscriptionSetResponse, Error> {
    let req = Request {
        using: vec!["urn:ietf:params:jmap:core".to_string()],
        method_calls: vec![Invocation(
            "PushSubscription/set".to_string(),
            json!({
                "update": {
                    (p.subscription_id.to_string()): {
                        "verificationCode": p.verification_code,
                        "expires": p.expires,
                    },
                },
            }),
            "confirm".to_string(),
        )],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    let out = decode::<PushSubscriptionSetResponse>(&req, &res, "confirm")?;

    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "PushSubscription/set",
        "confirm",
        &[
            ("notCreated", out.not_created.as_ref()),
            ("notUpdated", out.not_updated.as_ref()),
            ("notDestroyed", out.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
