// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateContact.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{ContactCardSetResponse, Id};

/// CreateContactParams holds the values CreateContact leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateContactParams {
    /// A globally unique identifier for the entity, which survives being
    /// copied between address books.
    pub uid: String,

    /// The id of the record this entry applies to.
    ///
    /// The address books the card is in, as a set of ids mapped to true.
    pub address_book_id: Id,

    /// The value of this part of the name.
    pub given_name: String,

    /// The value of this part of the name.
    pub surname: String,

    /// The address itself, as an addr-spec.
    pub email_address: String,

    /// The number, either as a URI or as free text.
    pub phone_number: String,

    /// The name of the organization.
    pub organization: String,
}

/// CreateContact adds a person to an address book. A contact card is a
/// JSContact object, so a name is a list of parts rather than a string, and
/// each address or number is an entry the card can refer to later.
///
/// It makes one ContactCard/set call in a single request, so that the server
/// is asked once. It returns the response to the ContactCard/set call.
///
/// The query does not say which account to use, so the session's primary
/// account for urn:ietf:params:jmap:contacts is used, which costs a session
/// lookup on first use.
pub async fn create_contact<T: Transport>(
    client: &Client<T>,
    p: CreateContactParams,
) -> Result<ContactCardSetResponse, Error> {
    let contacts_account_id = client
        .primary_account_id("urn:ietf:params:jmap:contacts")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:contacts".to_string(),
        ],
        method_calls: vec![Invocation(
            "ContactCard/set".to_string(),
            json!({
                "accountId": contacts_account_id,
                "create": {
                    "card": {
                        "@type": "Card",
                        "version": "1.0",
                        "uid": p.uid,
                        "kind": "individual",
                        "addressBookIds": {
                            (p.address_book_id.to_string()): true,
                        },
                        "name": {
                            "isOrdered": true,
                            "components": [
                                {
                                    "kind": "given",
                                    "value": p.given_name,
                                },
                                {
                                    "kind": "surname",
                                    "value": p.surname,
                                },
                            ],
                        },
                        "emails": {
                            "work": {
                                "address": p.email_address,
                                "contexts": {"work":true},
                                "pref": 1,
                            },
                        },
                        "phones": {
                            "mobile": {
                                "number": p.phone_number,
                                "features": {"mobile":true,"voice":true},
                                "contexts": {"work":true},
                            },
                        },
                        "organizations": {
                            "employer": {
                                "name": p.organization,
                            },
                        },
                    },
                },
            }),
            "create".to_string(),
        )],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<ContactCardSetResponse>(&req, &res, "create") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "ContactCard/set",
        "create",
        &[
            ("notCreated", out.not_created.as_ref()),
            ("notUpdated", out.not_updated.as_ref()),
            ("notDestroyed", out.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
