// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateMailbox.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::MailboxSetResponse;

/// CreateMailboxParams holds the values CreateMailbox leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateMailboxParams {
    /// The user-visible name of the mailbox, unique among its siblings.
    pub name: String,
}

/// CREATE_MAILBOX_NEW is the creation id CreateMailbox gives a record it
/// creates, which the response reports it under.
pub const CREATE_MAILBOX_NEW: &str = "new";

/// CreateMailbox creates a top-level mailbox and subscribes to it.
///
/// It makes one Mailbox/set call in a single request, so that the server is
/// asked once. It returns the response to the Mailbox/set call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn create_mailbox<T: Transport>(
    client: &Client<T>,
    p: CreateMailboxParams,
) -> Result<MailboxSetResponse, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![Invocation(
            "Mailbox/set".to_string(),
            json!({
                "accountId": mail_account_id,
                "create": {
                    "new": {
                        "name": p.name,
                        "parentId": null,
                        "isSubscribed": true,
                    },
                },
            }),
            "create".to_string(),
        )],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<MailboxSetResponse>(&req, &res, "create") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "Mailbox/set",
        "create",
        &[
            ("notCreated", out.not_created.as_ref()),
            ("notUpdated", out.not_updated.as_ref()),
            ("notDestroyed", out.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
