// Code generated by jmapc. DO NOT EDIT.
// Source: queries/FileIntoNewMailbox.jmap.json

use std::collections::BTreeMap;

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{EmailSetResponse, Id, MailboxSetResponse};

/// FileIntoNewMailboxParams holds the values FileIntoNewMailbox leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct FileIntoNewMailboxParams {
    /// The user-visible name of the mailbox, unique among its siblings.
    pub name: String,

    /// The id of the record this entry applies to.
    ///
    /// A map of record id to the patch to apply to it.
    pub email_id: Id,

    /// The id of the record this entry applies to.
    pub from_mailbox_id: Id,
}

/// FILE_INTO_NEW_MAILBOX_BOX is the creation id FileIntoNewMailbox gives a
/// record it creates, which the response reports it under.
pub const FILE_INTO_NEW_MAILBOX_BOX: &str = "box";

/// FileIntoNewMailboxResult holds the response to each method call
/// FileIntoNewMailbox makes.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct FileIntoNewMailboxResult {
    /// The response to the Mailbox/set call, made as "make".
    pub mailbox_set: MailboxSetResponse,

    /// The response to the Email/set call, made as "file".
    pub email_set: EmailSetResponse,

    /// The creation ids of everything created by this request, together with
    /// those carried in. Pass it to the next request so that a reference to
    /// any of them still resolves.
    pub created_ids: BTreeMap<Id, Id>,
}

/// FileIntoNewMailbox creates a mailbox and moves a message into it,
/// referring to the mailbox by its creation id before the server has assigned
/// a real one. Carrying the creation ids in and out lets a proxy split this
/// across servers, or a client continue in a second request, with the
/// reference still resolving.
///
/// It makes Mailbox/set and Email/set calls in a single request, so that 2
/// dependent calls cost one round trip.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
///
/// It takes the creation ids of an earlier request and reports its own, so
/// that a reference to something created there still resolves here.
pub async fn file_into_new_mailbox<T: Transport>(
    client: &Client<T>,
    p: FileIntoNewMailboxParams,
    created_ids: Option<BTreeMap<Id, Id>>,
) -> Result<FileIntoNewMailboxResult, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Mailbox/set".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "create": {
                        "box": {
                            "name": p.name,
                            "parentId": null,
                        },
                    },
                }),
                "make".to_string(),
            ),
            // "#box" is the mailbox above. Had it been created by an earlier
            // request instead, the creation ids passed in would resolve it
            // just the same.
            Invocation(
                "Email/set".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "update": {
                        (p.email_id.to_string()): {
                            "mailboxIds/#box": true,
                            (format!("mailboxIds/{}", p.from_mailbox_id)): null,
                        },
                    },
                }),
                "file".to_string(),
            ),
        ],
        created_ids,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let mut out = FileIntoNewMailboxResult::default();
    match decode::<MailboxSetResponse>(&req, &res, "make") {
        Ok(v) => out.mailbox_set = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    match decode::<EmailSetResponse>(&req, &res, "file") {
        Ok(v) => out.email_set = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    out.created_ids = res.created_ids.clone().unwrap_or_default();
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "Mailbox/set",
        "make",
        &[
            ("notCreated", out.mailbox_set.not_created.as_ref()),
            ("notUpdated", out.mailbox_set.not_updated.as_ref()),
            ("notDestroyed", out.mailbox_set.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    collect_set_errors(
        "Email/set",
        "file",
        &[
            ("notCreated", out.email_set.not_created.as_ref()),
            ("notUpdated", out.email_set.not_updated.as_ref()),
            ("notDestroyed", out.email_set.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
