// Code generated by jmapc. DO NOT EDIT.
// Source: queries/FindPeople.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::Id;

/// FindPeopleParams holds the values FindPeople leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct FindPeopleParams {
    /// Matches principals where this text appears in the name, email, or
    /// description.
    pub phrase: String,

    /// The maximum number of ids to return.
    pub limit: Option<u64>,
}

/// FindPeoplePrincipal holds the properties of Principal that the
/// Principal/get call in FindPeople asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FindPeoplePrincipal {
    /// The id of the principal.
    pub id: Id,

    /// What the principal is: "individual", "group", "resource", "location",
    /// or "other".
    pub r#type: String,

    /// The user-visible name of the principal.
    pub name: String,

    /// An email address for the principal, or null for one that has none.
    #[serde(default)]
    pub email: Option<String>,

    /// The time zone the principal is normally in, named as in the IANA Time
    /// Zone Database.
    #[serde(default)]
    pub time_zone: Option<String>,
}

/// FindPeoplePrincipalGetResponse holds the response to the Principal/get
/// call in FindPeople.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FindPeoplePrincipalGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Principal/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<FindPeoplePrincipal>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// FindPeople looks for the people and things an account can be shared with,
/// which is what a sharing dialogue needs before it can offer anything. The
/// limit may be left out, and the server then decides how many to answer
/// with.
///
/// It makes Principal/query and Principal/get calls in a single request, so
/// that 2 dependent calls cost one round trip. It returns the response to the
/// Principal/get call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn find_people<T: Transport>(
    client: &Client<T>,
    p: FindPeopleParams,
) -> Result<FindPeoplePrincipalGetResponse, Error> {
    let principals_account_id = client
        .primary_account_id("urn:ietf:params:jmap:principals")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:principals".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Principal/query".to_string(),
                {
                    let mut args = json!({
                        "accountId": principals_account_id,
                        "filter": {
                            "operator": "AND",
                            "conditions": [
                                {
                                    "text": p.phrase,
                                },
                                {"type":"individual"},
                            ],
                        },
                    });
                    if let Some(value) = &p.limit {
                        args["limit"] = json!(value);
                    }
                    args
                },
                "search".to_string(),
            ),
            Invocation(
                "Principal/get".to_string(),
                json!({
                    "accountId": principals_account_id,
                    "#ids": {"resultOf": "search", "name": "Principal/query", "path": "/ids"},
                    "properties": ["id","type","name","email","timeZone"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<FindPeoplePrincipalGetResponse>(&req, &res, "fetch") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    Ok(out)
}
