// Code generated by jmapc. DO NOT EDIT.
// Source: queries/InstallSieveScript.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{BlobUploadResponse, SieveScriptSetResponse};

/// InstallSieveScriptParams holds the values InstallSieveScript leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct InstallSieveScriptParams {
    /// The octets as text, which the server encodes as UTF-8.
    pub script: String,

    /// The user-visible name of the script, which is unique within the
    /// account. Null asks the server to choose one.
    pub name: String,
}

/// InstallSieveScript uploads a filtering script, stores it, and puts it into
/// service, in one request. If the script does not parse, nothing is stored
/// and whatever was running keeps running: the activation only happens once
/// the rest of the call has succeeded.
///
/// It makes Blob/upload and SieveScript/set calls in a single request, so
/// that 2 dependent calls cost one round trip. It returns the response to the
/// SieveScript/set call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn install_sieve_script<T: Transport>(
    client: &Client<T>,
    p: InstallSieveScriptParams,
) -> Result<SieveScriptSetResponse, Error> {
    let blob_account_id = client
        .primary_account_id("urn:ietf:params:jmap:blob")
        .await?;
    let sieve_account_id = client
        .primary_account_id("urn:ietf:params:jmap:sieve")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:blob".to_string(),
            "urn:ietf:params:jmap:sieve".to_string(),
        ],
        method_calls: vec![
            // A script's text is a blob, not a property, so it goes up first.
            // The blob extension lets that happen here rather than as a
            // separate upload.
            Invocation(
                "Blob/upload".to_string(),
                json!({
                    "accountId": blob_account_id,
                    "create": {
                        "text": {
                            "data": [
                                {
                                    "data:asText": p.script,
                                },
                            ],
                            "type": "application/sieve",
                        },
                    },
                }),
                "upload".to_string(),
            ),
            // Both onSuccess arguments refer to the script created here,
            // before the server has given it an id. Deactivation happens
            // first, so there is no moment with two active scripts.
            Invocation(
                "SieveScript/set".to_string(),
                json!({
                    "accountId": sieve_account_id,
                    "create": {
                        "filter": {
                            "name": p.name,
                            "blobId": "#text",
                        },
                    },
                    "onSuccessDeactivateScript": true,
                    "onSuccessActivateScript": "#filter",
                }),
                "install".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    let out = decode::<SieveScriptSetResponse>(&req, &res, "install")?;

    let refused0 = decode::<BlobUploadResponse>(&req, &res, "upload")?;
    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "Blob/upload",
        "upload",
        &[("notCreated", refused0.not_created.as_ref())],
        &mut failures,
    );
    collect_set_errors(
        "SieveScript/set",
        "install",
        &[
            ("notCreated", out.not_created.as_ref()),
            ("notUpdated", out.not_updated.as_ref()),
            ("notDestroyed", out.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
