// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ListInboxEmails.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{EmailAddress, Id, UtcDate};

/// ListInboxEmailsParams holds the values ListInboxEmails leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListInboxEmailsParams {
    /// Matches emails in this mailbox.
    pub mailbox_id: Id,

    /// The maximum number of ids to return.
    pub limit: u64,
}

/// ListInboxEmailsEmail holds the properties of Email that the Email/get call
/// in ListInboxEmails asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListInboxEmailsEmail {
    /// The id of the email.
    pub id: Id,

    /// The id of the thread the email belongs to.
    pub thread_id: Id,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,

    /// A short plain-text excerpt of the message body.
    pub preview: String,

    /// Whether the message has at least one part the server considers an
    /// attachment.
    pub has_attachment: bool,
}

/// ListInboxEmailsEmailGetResponse holds the response to the Email/get call
/// in ListInboxEmails.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListInboxEmailsEmailGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<ListInboxEmailsEmail>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// ListInboxEmails returns the most recent emails in one mailbox, newest
/// first.
///
/// It makes Email/query and Email/get calls in a single request, so that 2
/// dependent calls cost one round trip. It returns the response to the
/// Email/get call.
///
/// The query does not say which account to use, so the session's primary
/// account for urn:ietf:params:jmap:mail is used, which costs a session
/// lookup on first use.
pub async fn list_inbox_emails<T: Transport>(
    client: &Client<T>,
    p: ListInboxEmailsParams,
) -> Result<ListInboxEmailsEmailGetResponse, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![
            // Find the ids of the matching emails.
            Invocation(
                "Email/query".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "filter": {
                        "inMailbox": p.mailbox_id,
                    },
                    "sort": [{"property":"receivedAt","isAscending":false}],
                    "limit": p.limit,
                }),
                "search".to_string(),
            ),
            // Fetch them in the same request, so the ids never make a round
            // trip.
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "#ids": {"resultOf": "search", "name": "Email/query", "path": "/ids"},
                    "properties": ["id","threadId","subject","from","receivedAt","preview","hasAttachment"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<ListInboxEmailsEmailGetResponse>(&req, &res, "fetch") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    Ok(out)
}
