// Code generated by jmapc. DO NOT EDIT.
// Source: queries/MailQuota.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::Id;

/// MailQuotaQuota holds the properties of Quota that the Quota/get call in
/// MailQuota asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MailQuotaQuota {
    /// The id of the quota.
    pub id: Id,

    /// The name of the quota, which is unique within its scope and
    /// resourceType.
    pub name: String,

    /// Who the limit applies to: "account" for this account alone, "domain"
    /// for everyone in the domain, or "global" for the whole server.
    pub scope: String,

    /// How much of the resource is in use, in whatever the resourceType
    /// counts.
    pub used: u64,

    /// The point beyond which the server refuses to store more.
    pub hard_limit: u64,

    /// The point at which the server would like the client to warn the user,
    /// which it sets below the hard limit so that there is time to do
    /// something about it.
    #[serde(default)]
    pub warn_limit: Option<u64>,

    /// The point beyond which the server starts refusing some operations
    /// while still allowing others, such as accepting mail but not letting
    /// the user send any.
    #[serde(default)]
    pub soft_limit: Option<u64>,

    /// A description of the quota, meant to be shown to the user.
    #[serde(default)]
    pub description: Option<String>,
}

/// MailQuotaFetchResponse holds the response to the Quota/get call in
/// MailQuota.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MailQuotaFetchResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Quota/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<MailQuotaQuota>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// MailQuota reports how much of the account's mail storage is used. An
/// account may be under several quotas at once, so the filter narrows it to
/// the one a mail client would show: the octets it is allowed for mail.
///
/// It makes Quota/query and Quota/get calls in a single request, so that 2
/// dependent calls cost one round trip. It returns the response to the
/// Quota/get call.
///
/// The query does not say which account to use, so the session's primary
/// account for urn:ietf:params:jmap:quota is used, which costs a session
/// lookup on first use.
pub async fn mail_quota<T: Transport>(client: &Client<T>) -> Result<MailQuotaFetchResponse, Error> {
    let quota_account_id = client
        .primary_account_id("urn:ietf:params:jmap:quota")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:quota".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Quota/query".to_string(),
                json!({
                    "accountId": quota_account_id,
                    "filter": {"operator":"AND","conditions":[{"resourceType":"octets"},{"type":"Mail"}]},
                    "sort": [{"property":"used","isAscending":false}],
                }),
                "search".to_string(),
            ),
            Invocation(
                "Quota/get".to_string(),
                json!({
                    "accountId": quota_account_id,
                    "#ids": {"resultOf": "search", "name": "Quota/query", "path": "/ids"},
                    "properties": ["id","name","scope","used","hardLimit","warnLimit","softLimit","description"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<MailQuotaFetchResponse>(&req, &res, "fetch") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    Ok(out)
}
