// Code generated by jmapc. DO NOT EDIT.
// Source: the JMAP queries jmapc generated this directory from

pub mod client;
pub mod types;

pub mod agenda;
pub mod attach_note;
pub mod check_sieve_script;
pub mod confirm_push;
pub mod create_contact;
pub mod create_event;
pub mod create_mailbox;
pub mod file_into_new_mailbox;
pub mod find_people;
pub mod install_sieve_script;
pub mod list_inbox_emails;
pub mod mail_quota;
pub mod mark_email_read;
pub mod read_message;
pub mod recently_shared;
pub mod register_push;
pub mod reschedule_occurrence;
pub mod search_contacts;
pub mod search_emails;
pub mod send_email;
pub mod send_read_receipt;
pub mod sync_emails;
pub mod update_contact_email;
pub mod verified_signatures;
pub mod what_uses_blob;

/// The runtime, brought up to the top so that a caller names the client
/// rather than the module it happens to live in. The data model stays where
/// it is: it holds a type for everything JMAP describes, and most programs
/// want a few of them by name.
pub use client::{
    decode, Auth, Client, ClientOptions, Error, HttpRequest, HttpResponse, Invocation, MethodError,
    MethodErrors, Request, RequestError, Response, ResultReference, Session, SetErrors, SetFailure,
    Transport, TransportError,
};

pub use agenda::*;
pub use attach_note::*;
pub use check_sieve_script::*;
pub use confirm_push::*;
pub use create_contact::*;
pub use create_event::*;
pub use create_mailbox::*;
pub use file_into_new_mailbox::*;
pub use find_people::*;
pub use install_sieve_script::*;
pub use list_inbox_emails::*;
pub use mail_quota::*;
pub use mark_email_read::*;
pub use read_message::*;
pub use recently_shared::*;
pub use register_push::*;
pub use reschedule_occurrence::*;
pub use search_contacts::*;
pub use search_emails::*;
pub use send_email::*;
pub use send_read_receipt::*;
pub use sync_emails::*;
pub use update_contact_email::*;
pub use verified_signatures::*;
pub use what_uses_blob::*;
