// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ReadMessage.jmap.json

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{Date, EmailAddress, EmailBodyValue, Id, UtcDate};

/// ReadMessageParams holds the values ReadMessage leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ReadMessageParams {
    /// One of the ids in the list.
    ///
    /// The ids of the records to fetch, or null to fetch all of them.
    pub email_id: Id,
}

/// ReadMessageEmailBodyPart holds the properties of EmailBodyPart that the
/// Email/get call in ReadMessage asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadMessageEmailBodyPart {
    /// Identifies the part's content within the bodyValues map, or null if
    /// the part has no body of its own.
    #[serde(default)]
    pub part_id: Option<String>,

    /// The id of the blob holding the raw content, or null for a multipart
    /// part.
    #[serde(default)]
    pub blob_id: Option<Id>,

    /// The media type of the part.
    pub r#type: String,

    /// The character set of the part, for textual media types.
    #[serde(default)]
    pub charset: Option<String>,

    /// The size of the decoded content in octets.
    pub size: u64,

    /// The filename the part should be saved as, if it names one.
    #[serde(default)]
    pub name: Option<String>,

    /// The Content-Disposition of the part, such as "inline" or "attachment".
    #[serde(default)]
    pub disposition: Option<String>,

    /// The Content-ID of the part, which inline images are referenced by.
    #[serde(default)]
    pub cid: Option<String>,

    /// The parts of a multipart part, or null if this part is not multipart.
    #[serde(default)]
    pub sub_parts: Option<Vec<ReadMessageEmailBodyPart>>,
}

/// ReadMessageEmail holds the properties of Email that the Email/get call in
/// ReadMessage asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadMessageEmail {
    /// The id of the email.
    pub id: Id,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// The To header field value.
    #[serde(default)]
    pub to: Option<Vec<EmailAddress>>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,

    /// The full MIME structure of the message body.
    pub body_structure: ReadMessageEmailBodyPart,

    /// The parts to display as the plain-text body of the message.
    #[serde(default)]
    pub text_body: Vec<ReadMessageEmailBodyPart>,

    /// The parts to display as the HTML body of the message.
    #[serde(default)]
    pub html_body: Vec<ReadMessageEmailBodyPart>,

    /// The parts to present as attachments rather than as body content.
    #[serde(default)]
    pub attachments: Vec<ReadMessageEmailBodyPart>,

    /// The decoded content of the body parts that were fetched, keyed by
    /// partId.
    #[serde(default)]
    pub body_values: BTreeMap<String, EmailBodyValue>,

    /// The List-Id header field, or the last of them where the message has
    /// several, decoded and unfolded into text.
    #[serde(rename = "header:List-Id:asText", default)]
    pub header_list_id_as_text: Option<String>,

    /// The List-Post header field, or the last of them where the message has
    /// several, parsed as a list of URLs.
    #[serde(rename = "header:List-Post:asURLs", default)]
    pub header_list_post_as_urls: Option<Vec<String>>,

    /// The Delivery-Date header field, or the last of them where the message
    /// has several, parsed as a date.
    #[serde(rename = "header:Delivery-Date:asDate", default)]
    pub header_delivery_date_as_date: Option<Date>,
}

/// ReadMessageEmailGetResponse holds the response to the Email/get call in
/// ReadMessage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadMessageEmailGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<ReadMessageEmail>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// ReadMessage fetches one message for display: its text, the parts a viewer
/// needs to lay out, and the header fields a mailing list adds. What comes
/// back is typed down to the header field: a List-Id is a string and a
/// Resent-To is a list of addresses, because the form asked for decides it.
///
/// It makes one Email/get call in a single request, so that the server is
/// asked once. It returns the response to the Email/get call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn read_message<T: Transport>(
    client: &Client<T>,
    p: ReadMessageParams,
) -> Result<ReadMessageEmailGetResponse, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![
            // bodyProperties narrows the parts themselves, all the way down
            // through subParts, which properties alone cannot reach.
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "ids": [
                        p.email_id,
                    ],
                    "properties": ["id","subject","from","to","receivedAt","bodyStructure","textBody","htmlBody","attachments","bodyValues","header:List-Id:asText","header:List-Post:asURLs","header:Delivery-Date:asDate"],
                    "bodyProperties": ["partId","blobId","type","charset","size","name","disposition","cid","subParts"],
                    "fetchTextBodyValues": true,
                    "maxBodyValueBytes": 262144,
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    decode::<ReadMessageEmailGetResponse>(&req, &res, "fetch")
}
