// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RecentlyShared.jmap.json

use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{ShareNotificationGetResponse, UtcDate};

/// RecentlySharedParams holds the values RecentlyShared leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RecentlySharedParams {
    /// Matches notifications created at or after this time.
    pub since: UtcDate,

    /// The maximum number of ids to return.
    pub limit: u64,
}

/// RecentlyShared reports what other people have shared with the user since a
/// known point. Nothing else tells them: a shared mailbox simply appears in
/// an account they can see, with no message to say so.
///
/// It makes ShareNotification/query and ShareNotification/get calls in a
/// single request, so that 2 dependent calls cost one round trip. It returns
/// the response to the ShareNotification/get call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn recently_shared<T: Transport>(
    client: &Client<T>,
    p: RecentlySharedParams,
) -> Result<ShareNotificationGetResponse, Error> {
    let principals_account_id = client
        .primary_account_id("urn:ietf:params:jmap:principals")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:principals".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "ShareNotification/query".to_string(),
                json!({
                    "accountId": principals_account_id,
                    "filter": {
                        "after": p.since,
                    },
                    "sort": [{"property":"created","isAscending":false}],
                    "limit": p.limit,
                }),
                "search".to_string(),
            ),
            Invocation(
                "ShareNotification/get".to_string(),
                json!({
                    "accountId": principals_account_id,
                    "#ids": {"resultOf": "search", "name": "ShareNotification/query", "path": "/ids"},
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    decode::<ShareNotificationGetResponse>(&req, &res, "fetch")
}
