// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RegisterPush.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::PushSubscriptionSetResponse;

/// RegisterPushParams holds the values RegisterPush leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RegisterPushParams {
    /// An id identifying the client and the device it runs on, so that a
    /// client which has lost its local state can still find the subscriptions
    /// it made. It must not carry an unobfuscated device id: the
    /// recommendation is a hash of the device's identifier together with the
    /// vendor's own.
    pub device_client_id: String,

    /// The absolute URL the server posts to, which must begin with
    /// "https://". A /get never returns it, since it may be private to one
    /// device.
    pub url: String,

    /// The P-256 ECDH public key, in URL-safe base64.
    pub public_key: String,

    /// The authentication secret, in URL-safe base64.
    pub auth_secret: String,
}

/// REGISTER_PUSH_DEVICE is the creation id RegisterPush gives a record it
/// creates, which the response reports it under.
pub const REGISTER_PUSH_DEVICE: &str = "device";

/// RegisterPush asks the server to post to a URL when something changes,
/// which is how a client that cannot hold a connection open — an app on a
/// phone, say — hears about changes at all. The subscription is not live
/// yet: the server pushes a verification code to the URL first, and
/// ConfirmPush writes it back.
///
/// It makes one PushSubscription/set call in a single request, so that the
/// server is asked once. It returns the response to the PushSubscription/set
/// call.
pub async fn register_push<T: Transport>(
    client: &Client<T>,
    p: RegisterPushParams,
) -> Result<PushSubscriptionSetResponse, Error> {
    let req = Request {
        using: vec!["urn:ietf:params:jmap:core".to_string()],
        method_calls: vec![
            // There is no accountId here. A subscription belongs to the
            // credentials that made it, not to an account, so it hears about
            // every account those credentials can see.
            Invocation(
                "PushSubscription/set".to_string(),
                json!({
                    "create": {
                        "device": {
                            "deviceClientId": p.device_client_id,
                            "url": p.url,
                            "keys": {
                                "p256dh": p.public_key,
                                "auth": p.auth_secret,
                            },
                            "types": ["Email","EmailDelivery"],
                        },
                    },
                }),
                "register".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<PushSubscriptionSetResponse>(&req, &res, "register") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "PushSubscription/set",
        "register",
        &[
            ("notCreated", out.not_created.as_ref()),
            ("notUpdated", out.not_updated.as_ref()),
            ("notDestroyed", out.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
