// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchEmails.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{EmailAddress, EmailQueryResponse, Id, UtcDate};

/// SearchEmailsParams holds the values SearchEmails leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchEmailsParams {
    /// Matches emails where this text appears in the body, subject, or any
    /// address header field.
    pub phrase: String,

    /// Matches emails in this mailbox.
    pub first_mailbox_id: Id,

    /// Matches emails in this mailbox.
    pub second_mailbox_id: Id,

    /// The zero-based index of the first result to return. A negative value
    /// counts back from the end.
    pub position: i64,
}

/// SearchEmailsEmail holds the properties of Email that the Email/get call in
/// SearchEmails asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchEmailsEmail {
    /// The id of the email.
    pub id: Id,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,
}

/// SearchEmailsFetchResponse holds the response to the Email/get call in
/// SearchEmails.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchEmailsFetchResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<SearchEmailsEmail>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// SearchEmailsResult holds the response to each method call SearchEmails
/// makes.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchEmailsResult {
    /// The response to the Email/query call, made as "search".
    pub search: EmailQueryResponse,

    /// The response to the Email/get call, made as "fetch".
    pub fetch: SearchEmailsFetchResponse,
}

/// SearchEmails finds emails matching a phrase in one of two mailboxes, and
/// returns both the ids that matched and the emails themselves.
///
/// It makes Email/query and Email/get calls in a single request, so that 2
/// dependent calls cost one round trip.
///
/// The query does not say which account to use, so the session's primary
/// account for urn:ietf:params:jmap:mail is used, which costs a session
/// lookup on first use.
pub async fn search_emails<T: Transport>(
    client: &Client<T>,
    p: SearchEmailsParams,
) -> Result<SearchEmailsResult, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Email/query".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "filter": {
                        "operator": "AND",
                        "conditions": [
                            {
                                "text": p.phrase,
                            },
                            {
                                "operator": "OR",
                                "conditions": [
                                    {
                                        "inMailbox": p.first_mailbox_id,
                                    },
                                    {
                                        "inMailbox": p.second_mailbox_id,
                                    },
                                ],
                            },
                            {"hasAttachment":true},
                        ],
                    },
                    "sort": [{"property":"receivedAt","isAscending":false}],
                    "collapseThreads": true,
                    "position": p.position,
                    "limit": 50,
                    "calculateTotal": true,
                }),
                "search".to_string(),
            ),
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "#ids": {"resultOf": "search", "name": "Email/query", "path": "/ids"},
                    "properties": ["id","subject","from","receivedAt"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let mut out = SearchEmailsResult::default();
    match decode::<EmailQueryResponse>(&req, &res, "search") {
        Ok(v) => out.search = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    match decode::<SearchEmailsFetchResponse>(&req, &res, "fetch") {
        Ok(v) => out.fetch = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    Ok(out)
}

/// SearchEmailsPages walks the whole of what search_emails returns one part
/// of, calling it again for each part until none is left.
///
/// An empty window ends the walk instead of being returned, so every part it
/// returns holds at least one record; where the call asked for the total, the
/// walk ends without requesting a window past it.
pub struct SearchEmailsPages {
    params: SearchEmailsParams,
    start: i64,
    done: bool,
}

/// search_emails_pages starts a walk from the position the parameters carry.
/// Nothing is sent until the first call to next.
pub fn search_emails_pages(p: SearchEmailsParams) -> SearchEmailsPages {
    SearchEmailsPages {
        start: p.position.clone(),
        params: p,
        done: false,
    }
}

impl SearchEmailsPages {
    /// next asks for the part after the one before, and answers with None
    /// where there is none left.
    pub async fn next<T: Transport>(
        &mut self,
        client: &Client<T>,
    ) -> Result<Option<SearchEmailsResult>, Error> {
        if self.done {
            return Ok(None);
        }
        self.params.position = self.start.clone();
        let res = search_emails(client, self.params.clone()).await?;
        let window = &res.search;
        if window.ids.is_empty() {
            self.done = true;
            return Ok(None);
        }
        self.start = window.position as i64 + window.ids.len() as i64;
        if window.total > 0 && self.start as u64 >= window.total {
            self.done = true;
        }
        Ok(Some(res))
    }
}
