// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchContacts.jmap.json

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{
    ContactCardQueryResponse, ContactEmailAddress, ContactName, ContactOrganization, ContactPhone,
    Id,
};

/// SearchContactsParams holds the values SearchContacts leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchContactsParams {
    /// Matches cards in this address book.
    pub address_book_id: Id,

    /// Matches cards where this text appears in any of the properties the
    /// other conditions search individually.
    pub phrase: String,

    /// The maximum number of ids to return.
    pub limit: u64,
}

/// SearchContactsAddressBook holds the properties of AddressBook that the
/// AddressBook/get call in SearchContacts asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchContactsAddressBook {
    /// The id of the address book.
    pub id: Id,

    /// The user-visible name of the address book, at most 255 octets of
    /// UTF-8.
    pub name: String,

    /// Whether this is the address book a card goes into when the client does
    /// not say. Exactly one address book in an account has this set.
    pub is_default: bool,
}

/// SearchContactsContactCard holds the properties of ContactCard that the
/// ContactCard/get call in SearchContacts asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchContactsContactCard {
    /// The id of the card.
    pub id: Id,

    /// A globally unique identifier for the entity, which survives being
    /// copied between address books.
    pub uid: String,

    /// The name of the entity.
    pub name: ContactName,

    /// The addresses the entity receives mail at, keyed by an id local to the
    /// card.
    #[serde(default)]
    pub emails: BTreeMap<Id, ContactEmailAddress>,

    /// The numbers the entity can be reached on, keyed by an id local to the
    /// card.
    #[serde(default)]
    pub phones: BTreeMap<Id, ContactPhone>,

    /// The organizations the entity belongs to, keyed by an id local to the
    /// card.
    #[serde(default)]
    pub organizations: BTreeMap<Id, ContactOrganization>,
}

/// SearchContactsAddressBookGetResponse holds the response to the
/// AddressBook/get call in SearchContacts.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchContactsAddressBookGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with AddressBook/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<SearchContactsAddressBook>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// SearchContactsContactCardGetResponse holds the response to the
/// ContactCard/get call in SearchContacts.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchContactsContactCardGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with ContactCard/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<SearchContactsContactCard>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// SearchContactsResult holds the response to each method call SearchContacts
/// makes.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchContactsResult {
    /// The response to the AddressBook/get call, made as "books".
    pub address_book_get: SearchContactsAddressBookGetResponse,

    /// The response to the ContactCard/query call, made as "search".
    pub contact_card_query: ContactCardQueryResponse,

    /// The response to the ContactCard/get call, made as "fetch".
    pub contact_card_get: SearchContactsContactCardGetResponse,
}

/// SearchContacts lists the address books and searches one of them in the
/// same request, so a contact picker can be filled in with one round trip.
///
/// It makes AddressBook/get, ContactCard/query, and ContactCard/get calls in
/// a single request, so that 3 dependent calls cost one round trip.
///
/// The query does not say which account to use, so the session's primary
/// account for urn:ietf:params:jmap:contacts is used, which costs a session
/// lookup on first use.
pub async fn search_contacts<T: Transport>(
    client: &Client<T>,
    p: SearchContactsParams,
) -> Result<SearchContactsResult, Error> {
    let contacts_account_id = client
        .primary_account_id("urn:ietf:params:jmap:contacts")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:contacts".to_string(),
        ],
        method_calls: vec![
            // Which address books exist. A picker needs this whether or not
            // the search finds anything.
            Invocation(
                "AddressBook/get".to_string(),
                json!({
                    "accountId": contacts_account_id,
                    "ids": null,
                    "properties": ["id","name","isDefault"],
                }),
                "books".to_string(),
            ),
            // The cards matching the phrase, surname first.
            Invocation(
                "ContactCard/query".to_string(),
                json!({
                    "accountId": contacts_account_id,
                    "filter": {
                        "operator": "AND",
                        "conditions": [
                            {
                                "inAddressBook": p.address_book_id,
                            },
                            {
                                "text": p.phrase,
                            },
                            {"kind":"individual"},
                        ],
                    },
                    "sort": [{"property":"name/surname"},{"property":"name/given"}],
                    "limit": p.limit,
                }),
                "search".to_string(),
            ),
            // Only the parts a list view shows. A card holds far more than
            // this.
            Invocation(
                "ContactCard/get".to_string(),
                json!({
                    "accountId": contacts_account_id,
                    "#ids": {"resultOf": "search", "name": "ContactCard/query", "path": "/ids"},
                    "properties": ["id","uid","name","emails","phones","organizations"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let mut out = SearchContactsResult::default();
    match decode::<SearchContactsAddressBookGetResponse>(&req, &res, "books") {
        Ok(v) => out.address_book_get = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    match decode::<ContactCardQueryResponse>(&req, &res, "search") {
        Ok(v) => out.contact_card_query = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    match decode::<SearchContactsContactCardGetResponse>(&req, &res, "fetch") {
        Ok(v) => out.contact_card_get = v,
        Err(e) if failed.is_none() => return Err(e),
        Err(_) => {}
    }
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    Ok(out)
}
