// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchEmails.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{EmailAddress, EmailQueryResponse, Id, UtcDate};

/// SearchEmailsParams holds the values SearchEmails leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchEmailsParams {
    /// Matches emails where this text appears in the body, subject, or any
    /// address header field.
    pub phrase: String,

    /// Matches emails in this mailbox.
    pub first_mailbox_id: Id,

    /// Matches emails in this mailbox.
    pub second_mailbox_id: Id,
}

/// SearchEmailsEmail holds the properties of Email that the Email/get call in
/// SearchEmails asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchEmailsEmail {
    /// The id of the email.
    pub id: Id,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,
}

/// SearchEmailsEmailGetResponse holds the response to the Email/get call in
/// SearchEmails.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchEmailsEmailGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<SearchEmailsEmail>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// SearchEmailsResult holds the response to each method call SearchEmails
/// makes.
#[derive(Debug, Clone, PartialEq)]
pub struct SearchEmailsResult {
    /// The response to the Email/query call, made as "search".
    pub email_query: EmailQueryResponse,

    /// The response to the Email/get call, made as "fetch".
    pub email_get: SearchEmailsEmailGetResponse,
}

/// SearchEmails finds emails matching a phrase in one of two mailboxes, and
/// returns both the ids that matched and the emails themselves.
///
/// It makes Email/query and Email/get calls in a single request, so that 2
/// dependent calls cost one round trip.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn search_emails<T: Transport>(
    client: &Client<T>,
    p: SearchEmailsParams,
) -> Result<SearchEmailsResult, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Email/query".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "filter": {
                        "operator": "AND",
                        "conditions": [
                            {
                                "text": p.phrase,
                            },
                            {
                                "operator": "OR",
                                "conditions": [
                                    {
                                        "inMailbox": p.first_mailbox_id,
                                    },
                                    {
                                        "inMailbox": p.second_mailbox_id,
                                    },
                                ],
                            },
                            {"hasAttachment":true},
                        ],
                    },
                    "sort": [{"property":"receivedAt","isAscending":false}],
                    "collapseThreads": true,
                    "limit": 50,
                    "calculateTotal": true,
                }),
                "search".to_string(),
            ),
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "#ids": {"resultOf": "search", "name": "Email/query", "path": "/ids"},
                    "properties": ["id","subject","from","receivedAt"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    let out = SearchEmailsResult {
        email_query: decode::<EmailQueryResponse>(&req, &res, "search")?,
        email_get: decode::<SearchEmailsEmailGetResponse>(&req, &res, "fetch")?,
    };

    Ok(out)
}
