// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SendEmail.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{EmailSetResponse, EmailSubmissionSetResponse, Id};

/// SendEmailParams holds the values SendEmail leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SendEmailParams {
    /// The id of the record this entry applies to.
    ///
    /// The mailboxes the email is in, as a set of ids mapped to true.
    pub drafts_mailbox_id: Id,

    /// The addr-spec of the address.
    pub from_address: String,

    /// The addr-spec of the address.
    pub to_address: String,

    /// The Subject header field value.
    pub subject: String,

    /// The decoded content of the body part.
    pub body: String,

    /// The id of the identity to send from.
    pub identity_id: Id,

    /// The id of the record this entry applies to.
    pub sent_mailbox_id: Id,
}

/// SEND_EMAIL_DRAFT is the creation id SendEmail gives a record it creates,
/// which the response reports it under.
pub const SEND_EMAIL_DRAFT: &str = "draft";

/// SEND_EMAIL_SEND is the creation id SendEmail gives a record it creates,
/// which the response reports it under.
pub const SEND_EMAIL_SEND: &str = "send";

/// SendEmail writes a message, hands it to the submission server, and files
/// it under Sent once the send succeeds — all in one request, so the draft
/// can never be left behind in Drafts by a call that failed halfway.
///
/// It makes Email/set and EmailSubmission/set calls in a single request, so
/// that 2 dependent calls cost one round trip. It returns the response to the
/// EmailSubmission/set call.
///
/// The query does not say which account to use, so the session's primary
/// account is used for each of urn:ietf:params:jmap:mail and
/// urn:ietf:params:jmap:submission, which costs a session lookup on first
/// use. They need not be the same account.
pub async fn send_email<T: Transport>(
    client: &Client<T>,
    p: SendEmailParams,
) -> Result<EmailSubmissionSetResponse, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;
    let submission_account_id = client
        .primary_account_id("urn:ietf:params:jmap:submission")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
            "urn:ietf:params:jmap:submission".to_string(),
        ],
        method_calls: vec![
            // Create the message. The creation id "draft" names it for the
            // rest of the request, before the server has assigned it a real
            // one.
            Invocation(
                "Email/set".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "create": {
                        "draft": {
                            "mailboxIds": {
                                (p.drafts_mailbox_id.to_string()): true,
                            },
                            "keywords": {"$draft":true},
                            "from": [
                                {
                                    "email": p.from_address,
                                },
                            ],
                            "to": [
                                {
                                    "email": p.to_address,
                                },
                            ],
                            "subject": p.subject,
                            "bodyStructure": {"partId":"text","type":"text/plain"},
                            "bodyValues": {
                                "text": {
                                    "value": p.body,
                                },
                            },
                        },
                    },
                }),
                "write".to_string(),
            ),
            // Submit it for delivery, referring to the email by its creation
            // id. On success, move it out of Drafts and into Sent and drop
            // the $draft keyword, which the submission server does as part of
            // the same call.
            Invocation(
                "EmailSubmission/set".to_string(),
                json!({
                    "accountId": submission_account_id,
                    "create": {
                        "send": {
                            "emailId": "#draft",
                            "identityId": p.identity_id,
                        },
                    },
                    "onSuccessUpdateEmail": {
                        "#send": {
                            (format!("mailboxIds/{}", p.drafts_mailbox_id)): null,
                            (format!("mailboxIds/{}", p.sent_mailbox_id)): true,
                            "keywords/$draft": null,
                        },
                    },
                }),
                "send".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<EmailSubmissionSetResponse>(&req, &res, "send") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    let refused0 = decode::<EmailSetResponse>(&req, &res, "write")?;
    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "Email/set",
        "write",
        &[
            ("notCreated", refused0.not_created.as_ref()),
            ("notUpdated", refused0.not_updated.as_ref()),
            ("notDestroyed", refused0.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    collect_set_errors(
        "EmailSubmission/set",
        "send",
        &[
            ("notCreated", out.not_created.as_ref()),
            ("notUpdated", out.not_updated.as_ref()),
            ("notDestroyed", out.not_destroyed.as_ref()),
        ],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
