// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SendReadReceipt.jmap.json

use serde_json::json;

use super::client::{
    collect_set_errors, decode, Client, Error, Invocation, Request, SetErrors, SetFailure,
    Transport,
};
use super::types::{Id, MdnSendResponse};

/// SendReadReceiptParams holds the values SendReadReceipt leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SendReadReceiptParams {
    /// The identity to send from, which decides both the sender and the
    /// address the notification is issued for.
    pub identity_id: Id,

    /// The id of the email this is about. It is required when sending, and
    /// may be null in one that was parsed, where the message it refers to may
    /// not be in the account.
    pub email_id: Id,

    /// The Subject header field for the notification itself.
    pub subject: String,

    /// A human-readable explanation, which the notification carries alongside
    /// the machine-readable part.
    pub body: String,
}

/// SendReadReceipt tells the sender of a message that it was displayed, and
/// marks the message so that the receipt is not sent again. Sending one is
/// the recipient's choice: nothing in a message can require it.
///
/// It makes one MDN/send call in a single request, so that the server is
/// asked once. It returns the response to the MDN/send call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn send_read_receipt<T: Transport>(
    client: &Client<T>,
    p: SendReadReceiptParams,
) -> Result<MdnSendResponse, Error> {
    let mdn_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mdn")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mdn".to_string(),
        ],
        method_calls: vec![
            // The disposition says both what became of the message and how
            // much of that the user chose. Here they read it and were asked
            // whether to send the receipt.
            Invocation(
                "MDN/send".to_string(),
                json!({
                    "accountId": mdn_account_id,
                    "identityId": p.identity_id,
                    "send": {
                        "receipt": {
                            "forEmailId": p.email_id,
                            "subject": p.subject,
                            "textBody": p.body,
                            "disposition": {"actionMode":"manual-action","sendingMode":"mdn-sent-manually","type":"displayed"},
                        },
                    },
                    "onSuccessUpdateEmail": {"#receipt":{"keywords/$mdnsent":true}},
                }),
                "send".to_string(),
            ),
        ],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<MdnSendResponse>(&req, &res, "send") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    let mut failures: Vec<SetFailure> = Vec::new();
    collect_set_errors(
        "MDN/send",
        "send",
        &[("notSent", out.not_sent.as_ref())],
        &mut failures,
    );
    if !failures.is_empty() {
        return Err(Error::Set(SetErrors::new(failures, out)));
    }

    Ok(out)
}
