// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SyncEmails.jmap.json

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{EmailChangesResponse, Id, UtcDate};

/// SyncEmailsParams holds the values SyncEmails leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SyncEmailsParams {
    /// The state string the client already has, as returned by an earlier
    /// Email/get or Email/changes.
    pub since_state: String,
}

/// SyncEmailsEmail holds the properties of Email that the Email/get call in
/// SyncEmails asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncEmailsEmail {
    /// The id of the email.
    pub id: Id,

    /// The id of the thread the email belongs to.
    pub thread_id: Id,

    /// The mailboxes the email is in, as a set of ids mapped to true.
    #[serde(default)]
    pub mailbox_ids: BTreeMap<Id, bool>,

    /// The keywords set on the email, such as "$seen" or "$flagged", mapped
    /// to true.
    #[serde(default)]
    pub keywords: BTreeMap<String, bool>,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,
}

/// SyncEmailsEmail2 holds the properties of Email that the Email/get call in
/// SyncEmails asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncEmailsEmail2 {
    /// The id of the email.
    pub id: Id,

    /// The mailboxes the email is in, as a set of ids mapped to true.
    #[serde(default)]
    pub mailbox_ids: BTreeMap<Id, bool>,

    /// The keywords set on the email, such as "$seen" or "$flagged", mapped
    /// to true.
    #[serde(default)]
    pub keywords: BTreeMap<String, bool>,
}

/// SyncEmailsEmailGetResponse holds the response to the Email/get call in
/// SyncEmails.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncEmailsEmailGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<SyncEmailsEmail>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// SyncEmailsEmailGet2Response holds the response to the Email/get call in
/// SyncEmails.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncEmailsEmailGet2Response {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<SyncEmailsEmail2>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// SyncEmailsResult holds the response to each method call SyncEmails makes.
#[derive(Debug, Clone, PartialEq)]
pub struct SyncEmailsResult {
    /// The response to the Email/changes call, made as "changes".
    pub email_changes: EmailChangesResponse,

    /// The response to the Email/get call, made as "created".
    pub email_get: SyncEmailsEmailGetResponse,

    /// The response to the Email/get call, made as "updated".
    pub email_get_2: SyncEmailsEmailGet2Response,
}

/// SyncEmails fetches the emails that have been created since a known state,
/// so a local cache can catch up without refetching everything.
///
/// It makes Email/changes, Email/get, and Email/get calls in a single
/// request, so that 3 dependent calls cost one round trip.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn sync_emails<T: Transport>(
    client: &Client<T>,
    p: SyncEmailsParams,
) -> Result<SyncEmailsResult, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Email/changes".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "sinceState": p.since_state,
                    "maxChanges": 128,
                }),
                "changes".to_string(),
            ),
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "#ids": {"resultOf": "changes", "name": "Email/changes", "path": "/created"},
                    "properties": ["id","threadId","mailboxIds","keywords","subject","receivedAt"],
                }),
                "created".to_string(),
            ),
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "#ids": {"resultOf": "changes", "name": "Email/changes", "path": "/updated"},
                    "properties": ["id","mailboxIds","keywords"],
                }),
                "updated".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    let out = SyncEmailsResult {
        email_changes: decode::<EmailChangesResponse>(&req, &res, "changes")?,
        email_get: decode::<SyncEmailsEmailGetResponse>(&req, &res, "created")?,
        email_get_2: decode::<SyncEmailsEmailGet2Response>(&req, &res, "updated")?,
    };

    Ok(out)
}
