// Code generated by jmapc. DO NOT EDIT.
// Source: queries/VerifiedSignatures.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{EmailAddress, Id, UtcDate};

/// VerifiedSignaturesParams holds the values VerifiedSignatures leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VerifiedSignaturesParams {
    /// Matches emails in this mailbox.
    pub mailbox_id: Id,

    /// The maximum number of ids to return.
    pub limit: u64,
}

/// VerifiedSignaturesEmail holds the properties of Email that the Email/get
/// call in VerifiedSignatures asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerifiedSignaturesEmail {
    /// The id of the email.
    pub id: Id,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,

    /// What the server made of the message's signature when it last looked:
    /// "unknown", "signed", "signed/verified", "signed/failed",
    /// "encrypted+signed/verified", or "encrypted+signed/failed". Null for a
    /// message with no signature.
    #[serde(default)]
    pub smime_status: Option<String>,

    /// What the server made of the signature when the message arrived, taking
    /// the same values as smimeStatus: "unknown", "signed",
    /// "signed/verified", "signed/failed", "encrypted+signed/verified", or
    /// "encrypted+signed/failed". It can differ from smimeStatus: a
    /// certificate valid on delivery may have expired since, and it is the
    /// state at delivery that says whether the message was trustworthy when
    /// it was sent.
    #[serde(default)]
    pub smime_status_at_delivery: Option<String>,

    /// What went wrong with the verification, in terms meant for a person to
    /// read.
    #[serde(default)]
    pub smime_errors: Option<Vec<String>>,

    /// When the server last checked the signature.
    #[serde(default)]
    pub smime_verified_at: Option<UtcDate>,
}

/// VerifiedSignaturesEmailGetResponse holds the response to the Email/get
/// call in VerifiedSignatures.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerifiedSignaturesEmailGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A string encoding the current state of the type on the server, for use
    /// with Email/changes.
    pub state: String,

    /// The records that were found, in an undefined order.
    #[serde(default)]
    pub list: Vec<VerifiedSignaturesEmail>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// VerifiedSignatures finds signed messages in a mailbox and reports what
/// became of each signature. The server does the cryptography: the signature
/// covers the raw message, which a client never sees once the server has
/// taken it apart.
///
/// It makes Email/query and Email/get calls in a single request, so that 2
/// dependent calls cost one round trip. It returns the response to the
/// Email/get call.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn verified_signatures<T: Transport>(
    client: &Client<T>,
    p: VerifiedSignaturesParams,
) -> Result<VerifiedSignaturesEmailGetResponse, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
            "urn:ietf:params:jmap:smimeverify".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Email/query".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "filter": {
                        "operator": "AND",
                        "conditions": [
                            {
                                "inMailbox": p.mailbox_id,
                            },
                            {"hasSmime":true},
                        ],
                    },
                    "sort": [{"property":"receivedAt","isAscending":false}],
                    "limit": p.limit,
                }),
                "search".to_string(),
            ),
            Invocation(
                "Email/get".to_string(),
                json!({
                    "accountId": mail_account_id,
                    "#ids": {"resultOf": "search", "name": "Email/query", "path": "/ids"},
                    "properties": ["id","subject","from","receivedAt","smimeStatus","smimeStatusAtDelivery","smimeErrors","smimeVerifiedAt"],
                }),
                "fetch".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    decode::<VerifiedSignaturesEmailGetResponse>(&req, &res, "fetch")
}
