// Code generated by jmapc. DO NOT EDIT.
// Source: queries/WhatUsesBlob.jmap.json

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{BlobLookupResponse, Id};

/// WhatUsesBlobParams holds the values WhatUsesBlob leaves open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct WhatUsesBlobParams {
    /// The ids of the blobs to look for.
    pub blob_id: Id,
}

/// WhatUsesBlobBlobData holds the properties of BlobData that the Blob/get
/// call in WhatUsesBlob asks for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WhatUsesBlobBlobData {
    /// The id of the blob.
    pub id: Id,

    /// The octets as text, or null where they are not valid UTF-8.
    #[serde(rename = "data:asText", default)]
    pub data_as_text: Option<String>,

    /// The size of the whole blob in octets, whatever range was asked for.
    pub size: u64,

    /// The digest of the blob under the sha-256 algorithm, as base64.
    #[serde(rename = "digest:sha-256", default)]
    pub digest_sha_256: serde_json::Value,
}

/// WhatUsesBlobBlobGetResponse holds the response to the Blob/get call in
/// WhatUsesBlob.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WhatUsesBlobBlobGetResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// The blobs that were found.
    #[serde(default)]
    pub list: Vec<WhatUsesBlobBlobData>,

    /// The ids that were requested but do not exist.
    #[serde(default)]
    pub not_found: Vec<Id>,
}

/// WhatUsesBlobResult holds the response to each method call WhatUsesBlob
/// makes.
#[derive(Debug, Clone, PartialEq)]
pub struct WhatUsesBlobResult {
    /// The response to the Blob/lookup call, made as "uses".
    pub blob_lookup: BlobLookupResponse,

    /// The response to the Blob/get call, made as "peek".
    pub blob_get: WhatUsesBlobBlobGetResponse,
}

/// WhatUsesBlob reports which records refer to a blob and reads a little of
/// it, which is how a client answers whether deleting a message would take an
/// attachment with it.
///
/// It makes Blob/lookup and Blob/get calls in a single request, so that 2
/// dependent calls cost one round trip.
///
/// The query does not say which account to use, so the primary account of the
/// session is used, which costs a session lookup on first use.
pub async fn what_uses_blob<T: Transport>(
    client: &Client<T>,
    p: WhatUsesBlobParams,
) -> Result<WhatUsesBlobResult, Error> {
    let blob_account_id = client
        .primary_account_id("urn:ietf:params:jmap:blob")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:blob".to_string(),
        ],
        method_calls: vec![
            Invocation(
                "Blob/lookup".to_string(),
                json!({
                    "accountId": blob_account_id,
                    "typeNames": ["Email","Mailbox"],
                    "ids": [
                        p.blob_id,
                    ],
                }),
                "uses".to_string(),
            ),
            Invocation(
                "Blob/get".to_string(),
                json!({
                    "accountId": blob_account_id,
                    "ids": [
                        p.blob_id,
                    ],
                    "properties": ["data:asText","size","digest:sha-256"],
                    "length": 4096,
                }),
                "peek".to_string(),
            ),
        ],
        created_ids: None,
    };

    let res = client.request(&req).await?;

    let out = WhatUsesBlobResult {
        blob_lookup: decode::<BlobLookupResponse>(&req, &res, "uses")?,
        blob_get: decode::<WhatUsesBlobBlobGetResponse>(&req, &res, "peek")?,
    };

    Ok(out)
}
