// Code generated by jmapc. DO NOT EDIT.
// Source: requests/properties.json

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use super::types::{EmailAddress, Id, UtcDate};

/// EmailSummary is what a list of messages shows: enough to draw a row and to
/// group the rows into threads, and none of the body.
///
/// EmailSummary holds the properties of Email that a call asking for
/// @EmailSummary receives.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmailSummary {
    /// The id of the email.
    pub id: Id,

    /// The id of the thread the email belongs to.
    pub thread_id: Id,

    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// When the email was received, which is what the mailbox sorts on by
    /// default.
    pub received_at: UtcDate,

    /// A short plain-text excerpt of the message body.
    pub preview: String,

    /// Whether the message has at least one part the server considers an
    /// attachment.
    pub has_attachment: bool,
}

/// EmailWithFlags is a summary and where the message sits: which mailboxes
/// hold it, and which keywords it carries. A cache catching up needs both.
///
/// EmailWithFlags holds the properties of Email that a call asking for
/// @EmailWithFlags receives.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmailWithFlags {
    /// The properties of EmailSummary, which this set adds to.
    #[serde(flatten)]
    pub email_summary: EmailSummary,

    /// The mailboxes the email is in, as a set of ids mapped to true.
    #[serde(default)]
    pub mailbox_ids: BTreeMap<Id, bool>,

    /// The keywords set on the email, such as "$seen" or "$flagged", mapped
    /// to true.
    #[serde(default)]
    pub keywords: BTreeMap<String, bool>,
}
