// Code generated by jmapc. DO NOT EDIT.
// Source: requests/ReadAttachedMessage.jmap.json

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::client::{decode, Client, Error, Invocation, Request, Transport};
use super::types::{Date, EmailAddress, EmailBodyValue, Id};

/// ReadAttachedMessageParams holds the values ReadAttachedMessage leaves
/// open.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ReadAttachedMessageParams {
    /// One of the ids in the list.
    ///
    /// The ids of the blobs to parse as messages.
    pub blob_id: Id,
}

/// ReadAttachedMessageParseEmailBodyPart holds the properties of
/// EmailBodyPart that the Email/parse call in ReadAttachedMessage asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadAttachedMessageParseEmailBodyPart {
    /// Identifies the part's content within the bodyValues map, or null if
    /// the part has no body of its own.
    #[serde(default)]
    pub part_id: Option<String>,

    /// The media type of the part.
    pub r#type: String,

    /// The size of the decoded content in octets.
    pub size: u64,
}

/// ReadAttachedMessageParseEmail holds the properties of Email that the
/// Email/parse call in ReadAttachedMessage asks for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadAttachedMessageParseEmail {
    /// The Subject header field value.
    #[serde(default)]
    pub subject: Option<String>,

    /// The From header field value.
    #[serde(default)]
    pub from: Option<Vec<EmailAddress>>,

    /// The Date header field value.
    #[serde(default)]
    pub sent_at: Option<Date>,

    /// The parts to display as the plain-text body of the message.
    #[serde(default)]
    pub text_body: Vec<ReadAttachedMessageParseEmailBodyPart>,

    /// The decoded content of the body parts that were fetched, keyed by
    /// partId.
    #[serde(default)]
    pub body_values: BTreeMap<String, EmailBodyValue>,
}

/// ReadAttachedMessageParseResponse holds the response to the Email/parse
/// call in ReadAttachedMessage.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadAttachedMessageParseResponse {
    /// The id of the account to operate on.
    pub account_id: Id,

    /// A map of blob id to the email parsed from it. The email has no id,
    /// mailboxIds, keywords, or receivedAt, because it is not a record in the
    /// account.
    #[serde(default)]
    pub parsed: Option<BTreeMap<Id, ReadAttachedMessageParseEmail>>,

    /// The ids of the blobs that exist but do not hold a message the server
    /// could parse.
    #[serde(default)]
    pub not_parsable: Option<Vec<Id>>,

    /// The ids of the blobs that do not exist.
    #[serde(default)]
    pub not_found: Option<Vec<Id>>,
}

/// ReadAttachedMessage reads a message sent as an attachment, for display,
/// without filing it in the account. The parsed messages come back keyed by
/// the blob they were read from, each typed down to the properties asked for.
///
/// It makes one Email/parse call in a single request, so that the server is
/// asked once. It returns the response to the Email/parse call.
///
/// The request does not say which account to use, so the session's primary
/// account for urn:ietf:params:jmap:mail is used, which costs a session
/// lookup on first use.
pub async fn read_attached_message<T: Transport>(
    client: &Client<T>,
    p: ReadAttachedMessageParams,
) -> Result<ReadAttachedMessageParseResponse, Error> {
    let mail_account_id = client
        .primary_account_id("urn:ietf:params:jmap:mail")
        .await?;

    let req = Request {
        using: vec![
            "urn:ietf:params:jmap:core".to_string(),
            "urn:ietf:params:jmap:mail".to_string(),
        ],
        method_calls: vec![Invocation(
            "Email/parse".to_string(),
            json!({
                "accountId": mail_account_id,
                "blobIds": [
                    p.blob_id,
                ],
                "properties": ["subject","from","sentAt","textBody","bodyValues"],
                "bodyProperties": ["partId","type","size"],
                "fetchTextBodyValues": true,
            }),
            "parse".to_string(),
        )],
        created_ids: None,
    };

    let (res, failed) = match client.request(&req).await {
        Ok(res) => (res, None),
        Err(Error::Method(errs)) => (errs.response.clone(), Some(errs)),
        Err(e) => return Err(e),
    };

    let out = match decode::<ReadAttachedMessageParseResponse>(&req, &res, "parse") {
        Ok(out) => out,
        Err(e) => return Err(failed.map(Error::Method).unwrap_or(e)),
    };
    if let Some(errs) = failed {
        return Err(Error::Method(errs.with_result(out)));
    }

    Ok(out)
}
