// Code generated by jmapc. DO NOT EDIT.
// Source: requests

use super::client::{Client, Error, RequestNeeds, Transport};

/// verify checks every request in this directory against the session, and
/// fails with Error::Verify holding everything that would stop one of them
/// from being sent. Call it as the program starts, to learn then rather than
/// when a request is first sent. See Client::verify for what it checks.
pub async fn verify<T: Transport>(client: &Client<T>) -> Result<(), Error> {
    client.verify(&NEEDS).await
}

/// What each request in this directory needs of the server.
const NEEDS: [RequestNeeds; 25] = [
    RequestNeeds {
        name: "Agenda",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:calendars",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:calendars"],
    },
    RequestNeeds {
        name: "AttachNote",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:blob",
            "urn:ietf:params:jmap:mail",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "CheckSieveScript",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:blob",
            "urn:ietf:params:jmap:sieve",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    },
    RequestNeeds {
        name: "ConfirmPush",
        using: &["urn:ietf:params:jmap:core"],
        calls: 1,
        primary_accounts: &[],
    },
    RequestNeeds {
        name: "CreateContact",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:contacts"],
    },
    RequestNeeds {
        name: "CreateEvent",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:calendars",
        ],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:calendars"],
    },
    RequestNeeds {
        name: "CreateMailbox",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "FileIntoNewMailbox",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "FindPeople",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:principals",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:principals"],
    },
    RequestNeeds {
        name: "InstallSieveScript",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:blob",
            "urn:ietf:params:jmap:sieve",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:blob", "urn:ietf:params:jmap:sieve"],
    },
    RequestNeeds {
        name: "ListInboxEmails",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "MailQuota",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:quota"],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:quota"],
    },
    RequestNeeds {
        name: "MarkEmailRead",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "ReadMessage",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "RecentlyShared",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:principals",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:principals"],
    },
    RequestNeeds {
        name: "RegisterPush",
        using: &["urn:ietf:params:jmap:core"],
        calls: 1,
        primary_accounts: &[],
    },
    RequestNeeds {
        name: "RescheduleOccurrence",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:calendars",
        ],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:calendars"],
    },
    RequestNeeds {
        name: "SearchContacts",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
        calls: 3,
        primary_accounts: &["urn:ietf:params:jmap:contacts"],
    },
    RequestNeeds {
        name: "SearchEmails",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "SendEmail",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:mail",
            "urn:ietf:params:jmap:submission",
        ],
        calls: 2,
        primary_accounts: &[
            "urn:ietf:params:jmap:mail",
            "urn:ietf:params:jmap:submission",
        ],
    },
    RequestNeeds {
        name: "SendReadReceipt",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mdn"],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:mdn"],
    },
    RequestNeeds {
        name: "SyncEmails",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
        calls: 3,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "UpdateContactEmail",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:contacts"],
        calls: 1,
        primary_accounts: &["urn:ietf:params:jmap:contacts"],
    },
    RequestNeeds {
        name: "VerifiedSignatures",
        using: &[
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:mail",
            "urn:ietf:params:jmap:smimeverify",
        ],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:mail"],
    },
    RequestNeeds {
        name: "WhatUsesBlob",
        using: &["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:blob"],
        calls: 2,
        primary_accounts: &["urn:ietf:params:jmap:blob"],
    },
];
