// Code generated by jmapc. DO NOT EDIT.
// Source: queries/Agenda.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// AgendaParams holds the values Agenda leaves open.
type AgendaParams struct {
	// Matches events in this calendar.
	CalendarID jmapc.ID

	// Matches events that end at or after this time.
	From jmapc.LocalDateTime

	// Matches events that start before this time.
	Until jmapc.LocalDateTime

	// The time zone to interpret a floating event's times in when expanding
	// recurrences.
	TimeZone jmapc.TimeZoneID
}

// AgendaCalendarEvent holds the properties of CalendarEvent that the
// CalendarEvent/get call in Agenda asks for.
type AgendaCalendarEvent struct {
	// The id of the event.
	ID jmapc.ID `json:"id"`

	// For an occurrence returned by an expanded query, the id of the recurring
	// event it belongs to.
	BaseEventID *jmapc.ID `json:"baseEventId"`

	// A short summary of the event.
	Title string `json:"title"`

	// When the event starts, in the event's own time zone.
	Start jmapc.LocalDateTime `json:"start"`

	// How long the event lasts.
	Duration jmapc.Duration `json:"duration"`

	// The time zone the start is in. Null means the event is floating, and
	// happens at that local time wherever the user is.
	TimeZone *jmapc.TimeZoneID `json:"timeZone"`

	// Whether the event is going ahead: "confirmed", "cancelled", or
	// "tentative".
	Status string `json:"status"`

	// Where the event happens, keyed by an id local to the event.
	Locations map[jmapc.ID]jmapc.EventLocation `json:"locations"`

	// Who is taking part, keyed by an id local to the event.
	Participants map[jmapc.ID]jmapc.EventParticipant `json:"participants"`
}

// AgendaCalendarEventGetResponse holds the response to the CalendarEvent/get
// call in Agenda.
type AgendaCalendarEventGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with CalendarEvent/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []AgendaCalendarEvent `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// Agenda lists what is happening in a window of time, expanding recurring
// events so that each occurrence comes back as its own entry.
//
// It makes CalendarEvent/query and CalendarEvent/get calls in a single
// request, so that 2 dependent calls cost one round trip. It returns the
// response to the CalendarEvent/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func Agenda(ctx context.Context, c *jmapc.Client, p AgendaParams) (*AgendaCalendarEventGetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	calendarsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityCalendars)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityCalendars},
		MethodCalls: []jmapc.Invocation{
			// Without expandRecurrences a weekly meeting is one event; with it, one
			// entry per occurrence, which is what a day view needs.
			{Name: "CalendarEvent/query", CallID: "search", Args: map[string]any{
				"accountId": calendarsAccountID,
				"filter": map[string]any{
					"operator": "AND",
					"conditions": []any{
						map[string]any{
							"inCalendar": p.CalendarID,
						},
						map[string]any{
							"after": p.From,
						},
						map[string]any{
							"before": p.Until,
						},
					},
				},
				"sort":              json.RawMessage(`[{"property":"start"}]`),
				"expandRecurrences": true,
				"timeZone":          p.TimeZone,
			}},
			// reduceParticipants keeps a meeting with two hundred people from
			// returning two hundred participants, of which a list view needs none but
			// the organiser and the user.
			{Name: "CalendarEvent/get", CallID: "fetch", Args: map[string]any{
				"accountId":          calendarsAccountID,
				"#ids":               jmapc.ResultReference{ResultOf: "search", Name: "CalendarEvent/query", Path: "/ids"},
				"properties":         json.RawMessage(`["id","baseEventId","title","start","duration","timeZone","status","locations","participants"]`),
				"reduceParticipants": true,
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out AgendaCalendarEventGetResponse
	if err := resp.Decode("fetch", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
