// Code generated by jmapc. DO NOT EDIT.
// Source: queries/AttachNote.jmap.json

package jmapq

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/linyows/jmapc"
)

// AttachNoteParams holds the values AttachNote leaves open.
type AttachNoteParams struct {
	// The octets as text, which the server encodes as UTF-8.
	Note string

	// The id of the record this entry applies to.
	//
	// The mailboxes the email is in, as a set of ids mapped to true.
	DraftsMailboxID jmapc.ID

	// The Subject header field value.
	Subject string
}

// AttachNoteResult holds the response to each method call AttachNote makes.
type AttachNoteResult struct {
	// The response to the Blob/upload call, made as "upload".
	BlobUpload jmapc.BlobUploadResponse

	// The response to the Email/set call, made as "draft".
	EmailSet jmapc.EmailSetResponse
}

// AttachNote writes a note into a blob and attaches it to a draft in the same
// request. The upload endpoint of RFC 8620 cannot do this: it is a separate
// HTTP call, so the blob id has to come back to the client before the draft
// can refer to it.
//
// It makes Blob/upload and Email/set calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func AttachNote(ctx context.Context, c *jmapc.Client, p AttachNoteParams) (*AttachNoteResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	blobAccountID, err := session.PrimaryAccountID(jmapc.CapabilityBlob)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityBlob, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Blob/upload", CallID: "upload", Args: map[string]any{
				"accountId": blobAccountID,
				"create": map[string]any{
					"note": map[string]any{
						"data": []any{
							map[string]any{
								"data:asText": p.Note,
							},
						},
						"type": "text/plain",
					},
				},
			}},
			// "#note" is the blob the call above creates, before the server has given
			// it an id.
			{Name: "Email/set", CallID: "draft", Args: map[string]any{
				"accountId": mailAccountID,
				"create": map[string]any{
					"draft": map[string]any{
						"mailboxIds": map[string]any{
							string(p.DraftsMailboxID): true,
						},
						"keywords":    json.RawMessage(`{"$draft":true}`),
						"subject":     p.Subject,
						"attachments": json.RawMessage(`[{"blobId":"#note","type":"text/plain","name":"note.txt","disposition":"attachment"}]`),
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out AttachNoteResult
	if e := resp.Decode("upload", &out.BlobUpload); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("draft", &out.EmailSet); e != nil && err == nil {
		return nil, e
	}

	var failures jmapc.SetErrors
	failures.Collect("Blob/upload", "upload", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated": out.BlobUpload.NotCreated,
	})
	failures.Collect("Email/set", "draft", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.EmailSet.NotCreated,
		"notUpdated":   out.EmailSet.NotUpdated,
		"notDestroyed": out.EmailSet.NotDestroyed,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
