// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ConfirmPush.jmap.json

package jmapq

import (
	"context"

	"github.com/linyows/jmapc"
)

// ConfirmPushParams holds the values ConfirmPush leaves open.
type ConfirmPushParams struct {
	// The id of the record this entry applies to.
	//
	// Patches to apply, keyed by subscription id. This is how the verification
	// code is written back and how the expiry is extended; the url and keys
	// cannot be changed, only replaced by destroying the subscription and
	// creating another.
	SubscriptionID jmapc.ID

	// The code proving the client controls the URL. It must be null when the
	// subscription is created; the server then pushes a code to the URL, and the
	// client writes it back here. Until that happens the server makes no further
	// requests to the URL, which is what stops a subscription being used to
	// attack a third party.
	VerificationCode string

	// When the subscription lapses. The server may impose one where the client
	// gives none, or shorten the one it gives, and a client extends the lifetime
	// by writing a later time here.
	Expires jmapc.UTCDate
}

// ConfirmPush writes back the code the server pushed to the subscription's
// URL. Until this happens the server sends nothing else, which is what keeps
// a subscription from being pointed at a third party and used to flood them.
//
// It makes one PushSubscription/set call in a single request, so that the
// server is asked once. It returns the response to the PushSubscription/set
// call.
func ConfirmPush(ctx context.Context, c *jmapc.Client, p ConfirmPushParams) (*jmapc.PushSubscriptionSetResponse, error) {
	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore},
		MethodCalls: []jmapc.Invocation{
			{Name: "PushSubscription/set", CallID: "confirm", Args: map[string]any{
				"update": map[string]any{
					string(p.SubscriptionID): map[string]any{
						"verificationCode": p.VerificationCode,
						"expires":          p.Expires,
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.PushSubscriptionSetResponse
	if err := resp.Decode("confirm", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
