// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateEvent.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// CreateEventParams holds the values CreateEvent leaves open.
type CreateEventParams struct {
	// A globally unique identifier for the event, shared by every copy of it.
	UID string

	// The id of the record this entry applies to.
	//
	// The calendars the event is in, as a set of ids mapped to true.
	CalendarID jmapc.ID

	// A short summary of the event.
	Title string

	// When the event starts, in the event's own time zone.
	Start jmapc.LocalDateTime

	// How long the event lasts.
	Duration jmapc.Duration

	// The time zone the start is in. Null means the event is floating, and
	// happens at that local time wherever the user is.
	TimeZone jmapc.TimeZoneID

	// The participant's email address.
	OrganiserAddress string

	// Where to send scheduling messages, keyed by method, such as "imip" mapped
	// to a mailto: URI.
	OrganiserSendTo string
}

// CreateEvent puts a weekly meeting in a calendar, with a reminder a quarter
// of an hour beforehand. An event's time is local, and the time zone is a
// property of its own, so that the meeting stays at nine when the clocks
// change.
//
// It makes one CalendarEvent/set call in a single request, so that the server
// is asked once. It returns the response to the CalendarEvent/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func CreateEvent(ctx context.Context, c *jmapc.Client, p CreateEventParams) (*jmapc.CalendarEventSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	calendarsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityCalendars)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityCalendars},
		MethodCalls: []jmapc.Invocation{
			{Name: "CalendarEvent/set", CallID: "create", Args: map[string]any{
				"accountId": calendarsAccountID,
				"create": map[string]any{
					"meeting": map[string]any{
						"@type": "Event",
						"uid":   p.UID,
						"calendarIds": map[string]any{
							string(p.CalendarID): true,
						},
						"title":           p.Title,
						"start":           p.Start,
						"duration":        p.Duration,
						"timeZone":        p.TimeZone,
						"recurrenceRules": json.RawMessage(`[{"frequency":"weekly","byDay":[{"day":"mo"}]}]`),
						"alerts":          json.RawMessage(`{"reminder":{"trigger":{"@type":"OffsetTrigger","offset":"-PT15M"},"action":"display"}}`),
						"participants": map[string]any{
							"organiser": map[string]any{
								"email":               p.OrganiserAddress,
								"roles":               json.RawMessage(`{"owner":true,"attendee":true}`),
								"participationStatus": "accepted",
								"sendTo": map[string]any{
									"imip": p.OrganiserSendTo,
								},
							},
						},
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.CalendarEventSetResponse
	if err := resp.Decode("create", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
