// Code generated by jmapc. DO NOT EDIT.
// Source: queries/CreateContact.jmap.json

package jmapq

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/linyows/jmapc"
)

// CreateContactParams holds the values CreateContact leaves open.
type CreateContactParams struct {
	// A globally unique identifier for the entity, which survives being copied
	// between address books.
	UID string

	// The id of the record this entry applies to.
	//
	// The address books the card is in, as a set of ids mapped to true.
	AddressBookID jmapc.ID

	// The value of this part of the name.
	GivenName string

	// The value of this part of the name.
	Surname string

	// The address itself, as an addr-spec.
	EmailAddress string

	// The number, either as a URI or as free text.
	PhoneNumber string

	// The name of the organization.
	Organization string
}

// CreateContact adds a person to an address book. A contact card is a
// JSContact object, so a name is a list of parts rather than a string, and
// each address or number is an entry the card can refer to later.
//
// It makes one ContactCard/set call in a single request, so that the server
// is asked once. It returns the response to the ContactCard/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func CreateContact(ctx context.Context, c *jmapc.Client, p CreateContactParams) (*jmapc.ContactCardSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	contactsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityContacts)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityContacts},
		MethodCalls: []jmapc.Invocation{
			{Name: "ContactCard/set", CallID: "create", Args: map[string]any{
				"accountId": contactsAccountID,
				"create": map[string]any{
					"card": map[string]any{
						"@type":   "Card",
						"version": "1.0",
						"uid":     p.UID,
						"kind":    "individual",
						"addressBookIds": map[string]any{
							string(p.AddressBookID): true,
						},
						"name": map[string]any{
							"isOrdered": true,
							"components": []any{
								map[string]any{
									"kind":  "given",
									"value": p.GivenName,
								},
								map[string]any{
									"kind":  "surname",
									"value": p.Surname,
								},
							},
						},
						"emails": map[string]any{
							"work": map[string]any{
								"address":  p.EmailAddress,
								"contexts": json.RawMessage(`{"work":true}`),
								"pref":     1,
							},
						},
						"phones": map[string]any{
							"mobile": map[string]any{
								"number":   p.PhoneNumber,
								"features": json.RawMessage(`{"mobile":true,"voice":true}`),
								"contexts": json.RawMessage(`{"work":true}`),
							},
						},
						"organizations": map[string]any{
							"employer": map[string]any{
								"name": p.Organization,
							},
						},
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out jmapc.ContactCardSetResponse
	if e := resp.Decode("create", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}

	var failures jmapc.SetErrors
	failures.Collect("ContactCard/set", "create", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.NotCreated,
		"notUpdated":   out.NotUpdated,
		"notDestroyed": out.NotDestroyed,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
