// Code generated by jmapc. DO NOT EDIT.
// Source: queries/FileIntoNewMailbox.jmap.json

package jmapq

import (
	"context"
	"errors"

	"github.com/linyows/jmapc"
)

// FileIntoNewMailboxParams holds the values FileIntoNewMailbox leaves open.
type FileIntoNewMailboxParams struct {
	// The user-visible name of the mailbox, unique among its siblings.
	Name string

	// The id of the record this entry applies to.
	//
	// A map of record id to the patch to apply to it.
	EmailID jmapc.ID

	// The id of the record this entry applies to.
	FromMailboxID jmapc.ID
}

// FileIntoNewMailboxResult holds the response to each method call
// FileIntoNewMailbox makes.
type FileIntoNewMailboxResult struct {
	// The response to the Mailbox/set call, made as "make".
	MailboxSet jmapc.MailboxSetResponse

	// The response to the Email/set call, made as "file".
	EmailSet jmapc.EmailSetResponse

	// The creation ids of everything created by this request, together with
	// those carried in. Pass it to the next request so that a reference to any
	// of them still resolves.
	CreatedIDs map[jmapc.ID]jmapc.ID
}

// FileIntoNewMailbox creates a mailbox and moves a message into it, referring
// to the mailbox by its creation id before the server has assigned a real
// one. Carrying the creation ids in and out lets a proxy split this across
// servers, or a client continue in a second request, with the reference still
// resolving.
//
// It makes Mailbox/set and Email/set calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
//
// It takes the creation ids of an earlier request and reports its own, so
// that a reference to something created there still resolves here. Pass nil
// where there is no earlier request.
func FileIntoNewMailbox(ctx context.Context, c *jmapc.Client, p FileIntoNewMailboxParams, createdIDs map[jmapc.ID]jmapc.ID) (*FileIntoNewMailboxResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Mailbox/set", CallID: "make", Args: map[string]any{
				"accountId": mailAccountID,
				"create": map[string]any{
					"box": map[string]any{
						"name":     p.Name,
						"parentId": nil,
					},
				},
			}},
			// "#box" is the mailbox above. Had it been created by an earlier request
			// instead, the creation ids passed in would resolve it just the same.
			{Name: "Email/set", CallID: "file", Args: map[string]any{
				"accountId": mailAccountID,
				"update": map[string]any{
					string(p.EmailID): map[string]any{
						"mailboxIds/#box":                       true,
						"mailboxIds/" + string(p.FromMailboxID): nil,
					},
				},
			}},
		},
		CreatedIDs: createdIDs,
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out FileIntoNewMailboxResult
	if e := resp.Decode("make", &out.MailboxSet); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("file", &out.EmailSet); e != nil && err == nil {
		return nil, e
	}
	out.CreatedIDs = resp.CreatedIDs

	var failures jmapc.SetErrors
	failures.Collect("Mailbox/set", "make", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.MailboxSet.NotCreated,
		"notUpdated":   out.MailboxSet.NotUpdated,
		"notDestroyed": out.MailboxSet.NotDestroyed,
	})
	failures.Collect("Email/set", "file", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.EmailSet.NotCreated,
		"notUpdated":   out.EmailSet.NotUpdated,
		"notDestroyed": out.EmailSet.NotDestroyed,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
