// Code generated by jmapc. DO NOT EDIT.
// Source: queries/FindPeople.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// FindPeopleParams holds the values FindPeople leaves open.
type FindPeopleParams struct {
	// Matches principals where this text appears in the name, email, or
	// description.
	Phrase string

	// The maximum number of ids to return.
	Limit *jmapc.UnsignedInt
}

// FindPeoplePrincipal holds the properties of Principal that the
// Principal/get call in FindPeople asks for.
type FindPeoplePrincipal struct {
	// The id of the principal.
	ID jmapc.ID `json:"id"`

	// What the principal is: "individual", "group", "resource", "location", or
	// "other".
	Type string `json:"type"`

	// The user-visible name of the principal.
	Name string `json:"name"`

	// An email address for the principal, or null for one that has none.
	Email *string `json:"email"`

	// The time zone the principal is normally in, named as in the IANA Time Zone
	// Database.
	TimeZone *string `json:"timeZone"`
}

// FindPeoplePrincipalGetResponse holds the response to the Principal/get call
// in FindPeople.
type FindPeoplePrincipalGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Principal/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []FindPeoplePrincipal `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// FindPeople looks for the people and things an account can be shared with,
// which is what a sharing dialogue needs before it can offer anything. The
// limit may be left out, and the server then decides how many to answer with.
//
// It makes Principal/query and Principal/get calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// Principal/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func FindPeople(ctx context.Context, c *jmapc.Client, p FindPeopleParams) (*FindPeoplePrincipalGetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	principalsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityPrincipals)
	if err != nil {
		return nil, err
	}

	principalQueryArgs := map[string]any{
		"accountId": principalsAccountID,
		"filter": map[string]any{
			"operator": "AND",
			"conditions": []any{
				map[string]any{
					"text": p.Phrase,
				},
				json.RawMessage(`{"type":"individual"}`),
			},
		},
	}
	if p.Limit != nil {
		principalQueryArgs["limit"] = *p.Limit
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityPrincipals},
		MethodCalls: []jmapc.Invocation{
			{Name: "Principal/query", CallID: "search", Args: principalQueryArgs},
			{Name: "Principal/get", CallID: "fetch", Args: map[string]any{
				"accountId":  principalsAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "Principal/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","type","name","email","timeZone"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out FindPeoplePrincipalGetResponse
	if e := resp.Decode("fetch", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}
	return &out, err
}
