// Code generated by jmapc. DO NOT EDIT.
// Source: queries/ListInboxEmails.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// ListInboxEmailsParams holds the values ListInboxEmails leaves open.
type ListInboxEmailsParams struct {
	// Matches emails in this mailbox.
	MailboxID jmapc.ID

	// The maximum number of ids to return.
	Limit jmapc.UnsignedInt
}

// ListInboxEmailsEmail holds the properties of Email that the Email/get call
// in ListInboxEmails asks for.
type ListInboxEmailsEmail struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The id of the thread the email belongs to.
	ThreadID jmapc.ID `json:"threadId"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// The From header field value.
	From []jmapc.EmailAddress `json:"from"`

	// When the email was received, which is what the mailbox sorts on by
	// default.
	ReceivedAt jmapc.UTCDate `json:"receivedAt"`

	// A short plain-text excerpt of the message body.
	Preview string `json:"preview"`

	// Whether the message has at least one part the server considers an
	// attachment.
	HasAttachment bool `json:"hasAttachment"`
}

// ListInboxEmailsEmailGetResponse holds the response to the Email/get call in
// ListInboxEmails.
type ListInboxEmailsEmailGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []ListInboxEmailsEmail `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// ListInboxEmails returns the most recent emails in one mailbox, newest
// first.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Email/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func ListInboxEmails(ctx context.Context, c *jmapc.Client, p ListInboxEmailsParams) (*ListInboxEmailsEmailGetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/query", CallID: "search", Args: map[string]any{
				"accountId": mailAccountID,
				"filter": map[string]any{
					"inMailbox": p.MailboxID,
				},
				"sort":  json.RawMessage(`[{"property":"receivedAt","isAscending":false}]`),
				"limit": p.Limit,
			}},
			{Name: "Email/get", CallID: "fetch", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "Email/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","threadId","subject","from","receivedAt","preview","hasAttachment"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out ListInboxEmailsEmailGetResponse
	if err := resp.Decode("fetch", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
