// Code generated by jmapc. DO NOT EDIT.
// Source: queries/MarkEmailRead.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// MarkEmailReadParams holds the values MarkEmailRead leaves open.
type MarkEmailReadParams struct {
	// The id of the record this entry applies to.
	EmailID jmapc.ID
}

// MarkEmailRead sets the $seen keyword on one email.
//
// It makes one Email/set call in a single request, so that the server is
// asked once. It returns the response to the Email/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func MarkEmailRead(ctx context.Context, c *jmapc.Client, p MarkEmailReadParams) (*jmapc.EmailSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/set", CallID: "mark", Args: map[string]any{
				"accountId": mailAccountID,
				"update": map[string]any{
					string(p.EmailID): json.RawMessage(`{"keywords/$seen":true}`),
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.EmailSetResponse
	if err := resp.Decode("mark", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
