// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RecentlyShared.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// RecentlySharedParams holds the values RecentlyShared leaves open.
type RecentlySharedParams struct {
	// Matches notifications created at or after this time.
	Since jmapc.UTCDate

	// The maximum number of ids to return.
	Limit jmapc.UnsignedInt
}

// RecentlyShared reports what other people have shared with the user since a
// known point. Nothing else tells them: a shared mailbox simply appears in an
// account they can see, with no message to say so.
//
// It makes ShareNotification/query and ShareNotification/get calls in a
// single request, so that 2 dependent calls cost one round trip. It returns
// the response to the ShareNotification/get call.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:principals is used, which costs a session
// lookup on first use.
func RecentlyShared(ctx context.Context, c *jmapc.Client, p RecentlySharedParams) (*jmapc.ShareNotificationGetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	principalsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityPrincipals)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityPrincipals},
		MethodCalls: []jmapc.Invocation{
			{Name: "ShareNotification/query", CallID: "search", Args: map[string]any{
				"accountId": principalsAccountID,
				"filter": map[string]any{
					"after": p.Since,
				},
				"sort":  json.RawMessage(`[{"property":"created","isAscending":false}]`),
				"limit": p.Limit,
			}},
			{Name: "ShareNotification/get", CallID: "fetch", Args: map[string]any{
				"accountId": principalsAccountID,
				"#ids":      jmapc.ResultReference{ResultOf: "search", Name: "ShareNotification/query", Path: "/ids"},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out jmapc.ShareNotificationGetResponse
	if e := resp.Decode("fetch", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}
	return &out, err
}
