// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RegisterPush.jmap.json

package jmapq

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/linyows/jmapc"
)

// RegisterPushParams holds the values RegisterPush leaves open.
type RegisterPushParams struct {
	// An id identifying the client and the device it runs on, so that a client
	// which has lost its local state can still find the subscriptions it made.
	// It must not carry an unobfuscated device id: the recommendation is a hash
	// of the device's identifier together with the vendor's own.
	DeviceClientID string

	// The absolute URL the server posts to, which must begin with "https://". A
	// /get never returns it, since it may be private to one device.
	URL string

	// The P-256 ECDH public key, in URL-safe base64.
	PublicKey string

	// The authentication secret, in URL-safe base64.
	AuthSecret string
}

// RegisterPushDevice is the creation id RegisterPush gives a record it
// creates, which the response reports it under.
const RegisterPushDevice jmapc.ID = "device"

// RegisterPush asks the server to post to a URL when something changes, which
// is how a client that cannot hold a connection open — an app on a phone,
// say — hears about changes at all. The subscription is not live yet: the
// server pushes a verification code to the URL first, and ConfirmPush writes
// it back.
//
// It makes one PushSubscription/set call in a single request, so that the
// server is asked once. It returns the response to the PushSubscription/set
// call.
func RegisterPush(ctx context.Context, c *jmapc.Client, p RegisterPushParams) (*jmapc.PushSubscriptionSetResponse, error) {
	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore},
		MethodCalls: []jmapc.Invocation{
			// There is no accountId here. A subscription belongs to the credentials
			// that made it, not to an account, so it hears about every account those
			// credentials can see.
			{Name: "PushSubscription/set", CallID: "register", Args: map[string]any{
				"create": map[string]any{
					"device": map[string]any{
						"deviceClientId": p.DeviceClientID,
						"url":            p.URL,
						"keys": map[string]any{
							"p256dh": p.PublicKey,
							"auth":   p.AuthSecret,
						},
						"types": json.RawMessage(`["Email","EmailDelivery"]`),
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out jmapc.PushSubscriptionSetResponse
	if e := resp.Decode("register", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}

	var failures jmapc.SetErrors
	failures.Collect("PushSubscription/set", "register", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.NotCreated,
		"notUpdated":   out.NotUpdated,
		"notDestroyed": out.NotDestroyed,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
