// Code generated by jmapc. DO NOT EDIT.
// Source: queries/RescheduleOccurrence.jmap.json

package jmapq

import (
	"context"

	"github.com/linyows/jmapc"
)

// RescheduleOccurrenceParams holds the values RescheduleOccurrence leaves
// open.
type RescheduleOccurrenceParams struct {
	// The id of the record this entry applies to.
	//
	// A map of record id to the patch to apply to it.
	EventID jmapc.ID

	// The key this entry is stored under.
	Occurrence jmapc.LocalDateTime

	// When the event starts, in the event's own time zone.
	NewStart jmapc.LocalDateTime

	// A short summary of the event.
	NewTitle string
}

// RescheduleOccurrence moves one occurrence of a recurring event without
// touching the rest of the series. The override is keyed by the start the
// recurrence rules gave that occurrence, and its value is a patch to the
// event.
//
// It makes one CalendarEvent/set call in a single request, so that the server
// is asked once. It returns the response to the CalendarEvent/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func RescheduleOccurrence(ctx context.Context, c *jmapc.Client, p RescheduleOccurrenceParams) (*jmapc.CalendarEventSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	calendarsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityCalendars)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityCalendars},
		MethodCalls: []jmapc.Invocation{
			{Name: "CalendarEvent/set", CallID: "reschedule", Args: map[string]any{
				"accountId": calendarsAccountID,
				"update": map[string]any{
					string(p.EventID): map[string]any{
						"recurrenceOverrides/" + string(p.Occurrence) + "/start": p.NewStart,
						"recurrenceOverrides/" + string(p.Occurrence) + "/title": p.NewTitle,
					},
				},
				"sendSchedulingMessages": true,
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.CalendarEventSetResponse
	if err := resp.Decode("reschedule", &out); err != nil {
		return nil, err
	}

	var failures jmapc.SetErrors
	failures.Collect("CalendarEvent/set", "reschedule", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.NotCreated,
		"notUpdated":   out.NotUpdated,
		"notDestroyed": out.NotDestroyed,
	})
	if err := failures.Err(); err != nil {
		return &out, err
	}
	return &out, nil
}
