// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchEmails.jmap.json

package jmapq

import (
	"context"
	"encoding/json"
	"iter"

	"github.com/linyows/jmapc"
)

// SearchEmailsParams holds the values SearchEmails leaves open.
type SearchEmailsParams struct {
	// Matches emails where this text appears in the body, subject, or any
	// address header field.
	Phrase string

	// Matches emails in this mailbox.
	FirstMailboxID jmapc.ID

	// Matches emails in this mailbox.
	SecondMailboxID jmapc.ID

	// The zero-based index of the first result to return. A negative value
	// counts back from the end.
	Position jmapc.Int
}

// SearchEmailsEmail holds the properties of Email that the Email/get call in
// SearchEmails asks for.
type SearchEmailsEmail struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// The From header field value.
	From []jmapc.EmailAddress `json:"from"`

	// When the email was received, which is what the mailbox sorts on by
	// default.
	ReceivedAt jmapc.UTCDate `json:"receivedAt"`
}

// SearchEmailsEmailGetResponse holds the response to the Email/get call in
// SearchEmails.
type SearchEmailsEmailGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []SearchEmailsEmail `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// SearchEmailsResult holds the response to each method call SearchEmails
// makes.
type SearchEmailsResult struct {
	// The response to the Email/query call, made as "search".
	EmailQuery jmapc.EmailQueryResponse

	// The response to the Email/get call, made as "fetch".
	EmailGet SearchEmailsEmailGetResponse
}

// SearchEmails finds emails matching a phrase in one of two mailboxes, and
// returns both the ids that matched and the emails themselves.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func SearchEmails(ctx context.Context, c *jmapc.Client, p SearchEmailsParams) (*SearchEmailsResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/query", CallID: "search", Args: map[string]any{
				"accountId": mailAccountID,
				"filter": map[string]any{
					"operator": "AND",
					"conditions": []any{
						map[string]any{
							"text": p.Phrase,
						},
						map[string]any{
							"operator": "OR",
							"conditions": []any{
								map[string]any{
									"inMailbox": p.FirstMailboxID,
								},
								map[string]any{
									"inMailbox": p.SecondMailboxID,
								},
							},
						},
						json.RawMessage(`{"hasAttachment":true}`),
					},
				},
				"sort":            json.RawMessage(`[{"property":"receivedAt","isAscending":false}]`),
				"collapseThreads": true,
				"position":        p.Position,
				"limit":           50,
				"calculateTotal":  true,
			}},
			{Name: "Email/get", CallID: "fetch", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "Email/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","subject","from","receivedAt"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out SearchEmailsResult
	if e := resp.Decode("search", &out.EmailQuery); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("fetch", &out.EmailGet); e != nil && err == nil {
		return nil, e
	}
	return &out, err
}

// SearchEmailsPages walks the whole of what SearchEmails returns one part of,
// calling it again for each part until there is none left.
//
// It starts from the position the parameters carry and works the next one out
// from each answer. A window with nothing in it ends the walk rather than
// being handed back, so every result yielded holds something; where the call
// asked for the total, the walk ends without asking for a window that is not
// there.
//
// An error ends the walk and is yielded with a nil result, so a range over it
// checks the error each time round. Breaking out of the range stops it, and
// sends no further request.
func SearchEmailsPages(ctx context.Context, c *jmapc.Client, p SearchEmailsParams) iter.Seq2[*SearchEmailsResult, error] {
	return func(yield func(*SearchEmailsResult, error) bool) {
		start := p.Position
		for {
			p.Position = start
			res, err := SearchEmails(ctx, c, p)
			if err != nil {
				yield(nil, err)
				return
			}
			window := &res.EmailQuery
			if len(window.IDs) == 0 {
				return
			}
			if !yield(res, nil) {
				return
			}
			start = jmapc.Int(window.Position) + jmapc.Int(len(window.IDs))
			if window.Total > 0 && jmapc.UnsignedInt(start) >= window.Total {
				return
			}
		}
	}
}
