// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SearchContacts.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// SearchContactsParams holds the values SearchContacts leaves open.
type SearchContactsParams struct {
	// Matches cards in this address book.
	AddressBookID jmapc.ID

	// Matches cards where this text appears in any of the properties the other
	// conditions search individually.
	Phrase string

	// The maximum number of ids to return.
	Limit jmapc.UnsignedInt
}

// SearchContactsAddressBook holds the properties of AddressBook that the
// AddressBook/get call in SearchContacts asks for.
type SearchContactsAddressBook struct {
	// The id of the address book.
	ID jmapc.ID `json:"id"`

	// The user-visible name of the address book, at most 255 octets of UTF-8.
	Name string `json:"name"`

	// Whether this is the address book a card goes into when the client does not
	// say. Exactly one address book in an account has this set.
	IsDefault bool `json:"isDefault"`
}

// SearchContactsContactCard holds the properties of ContactCard that the
// ContactCard/get call in SearchContacts asks for.
type SearchContactsContactCard struct {
	// The id of the card.
	ID jmapc.ID `json:"id"`

	// A globally unique identifier for the entity, which survives being copied
	// between address books.
	UID string `json:"uid"`

	// The name of the entity.
	Name jmapc.ContactName `json:"name"`

	// The addresses the entity receives mail at, keyed by an id local to the
	// card.
	Emails map[jmapc.ID]jmapc.ContactEmailAddress `json:"emails"`

	// The numbers the entity can be reached on, keyed by an id local to the
	// card.
	Phones map[jmapc.ID]jmapc.ContactPhone `json:"phones"`

	// The organizations the entity belongs to, keyed by an id local to the card.
	Organizations map[jmapc.ID]jmapc.ContactOrganization `json:"organizations"`
}

// SearchContactsAddressBookGetResponse holds the response to the
// AddressBook/get call in SearchContacts.
type SearchContactsAddressBookGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with AddressBook/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []SearchContactsAddressBook `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// SearchContactsContactCardGetResponse holds the response to the
// ContactCard/get call in SearchContacts.
type SearchContactsContactCardGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with ContactCard/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []SearchContactsContactCard `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// SearchContactsResult holds the response to each method call SearchContacts
// makes.
type SearchContactsResult struct {
	// The response to the AddressBook/get call, made as "books".
	AddressBookGet SearchContactsAddressBookGetResponse

	// The response to the ContactCard/query call, made as "search".
	ContactCardQuery jmapc.ContactCardQueryResponse

	// The response to the ContactCard/get call, made as "fetch".
	ContactCardGet SearchContactsContactCardGetResponse
}

// SearchContacts lists the address books and searches one of them in the same
// request, so a contact picker can be filled in with one round trip.
//
// It makes AddressBook/get, ContactCard/query, and ContactCard/get calls in a
// single request, so that 3 dependent calls cost one round trip.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func SearchContacts(ctx context.Context, c *jmapc.Client, p SearchContactsParams) (*SearchContactsResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	contactsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityContacts)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityContacts},
		MethodCalls: []jmapc.Invocation{
			{Name: "AddressBook/get", CallID: "books", Args: map[string]any{
				"accountId":  contactsAccountID,
				"ids":        nil,
				"properties": json.RawMessage(`["id","name","isDefault"]`),
			}},
			{Name: "ContactCard/query", CallID: "search", Args: map[string]any{
				"accountId": contactsAccountID,
				"filter": map[string]any{
					"operator": "AND",
					"conditions": []any{
						map[string]any{
							"inAddressBook": p.AddressBookID,
						},
						map[string]any{
							"text": p.Phrase,
						},
						json.RawMessage(`{"kind":"individual"}`),
					},
				},
				"sort":  json.RawMessage(`[{"property":"name/surname"},{"property":"name/given"}]`),
				"limit": p.Limit,
			}},
			{Name: "ContactCard/get", CallID: "fetch", Args: map[string]any{
				"accountId":  contactsAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "ContactCard/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","uid","name","emails","phones","organizations"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out SearchContactsResult
	if err := resp.Decode("books", &out.AddressBookGet); err != nil {
		return nil, err
	}
	if err := resp.Decode("search", &out.ContactCardQuery); err != nil {
		return nil, err
	}
	if err := resp.Decode("fetch", &out.ContactCardGet); err != nil {
		return nil, err
	}
	return &out, nil
}
