// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SendEmail.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// SendEmailParams holds the values SendEmail leaves open.
type SendEmailParams struct {
	// The id of the record this entry applies to.
	//
	// The mailboxes the email is in, as a set of ids mapped to true.
	DraftsMailboxID jmapc.ID

	// The addr-spec of the address.
	FromAddress string

	// The addr-spec of the address.
	ToAddress string

	// The Subject header field value.
	Subject string

	// The decoded content of the body part.
	Body string

	// The id of the identity to send from.
	IdentityID jmapc.ID

	// The id of the record this entry applies to.
	SentMailboxID jmapc.ID
}

// SendEmail writes a message, hands it to the submission server, and files it
// under Sent once the send succeeds — all in one request, so the draft can
// never be left behind in Drafts by a call that failed halfway.
//
// It makes Email/set and EmailSubmission/set calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// EmailSubmission/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func SendEmail(ctx context.Context, c *jmapc.Client, p SendEmailParams) (*jmapc.EmailSubmissionSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}
	submissionAccountID, err := session.PrimaryAccountID(jmapc.CapabilitySubmission)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail, jmapc.CapabilitySubmission},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/set", CallID: "write", Args: map[string]any{
				"accountId": mailAccountID,
				"create": map[string]any{
					"draft": map[string]any{
						"mailboxIds": map[string]any{
							string(p.DraftsMailboxID): true,
						},
						"keywords": json.RawMessage(`{"$draft":true}`),
						"from": []any{
							map[string]any{
								"email": p.FromAddress,
							},
						},
						"to": []any{
							map[string]any{
								"email": p.ToAddress,
							},
						},
						"subject":       p.Subject,
						"bodyStructure": json.RawMessage(`{"partId":"text","type":"text/plain"}`),
						"bodyValues": map[string]any{
							"text": map[string]any{
								"value": p.Body,
							},
						},
					},
				},
			}},
			{Name: "EmailSubmission/set", CallID: "send", Args: map[string]any{
				"accountId": submissionAccountID,
				"create": map[string]any{
					"send": map[string]any{
						"emailId":    "#draft",
						"identityId": p.IdentityID,
					},
				},
				"onSuccessUpdateEmail": map[string]any{
					"#send": map[string]any{
						"mailboxIds/" + string(p.DraftsMailboxID): nil,
						"mailboxIds/" + string(p.SentMailboxID):   true,
						"keywords/$draft":                         nil,
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.EmailSubmissionSetResponse
	if err := resp.Decode("send", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
