// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SendEmail.jmap.json

package jmapq

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/linyows/jmapc"
)

// SendEmailParams holds the values SendEmail leaves open.
type SendEmailParams struct {
	// The id of the record this entry applies to.
	//
	// The mailboxes the email is in, as a set of ids mapped to true.
	DraftsMailboxID jmapc.ID

	// The addr-spec of the address.
	FromAddress string

	// The addr-spec of the address.
	ToAddress string

	// The Subject header field value.
	Subject string

	// The decoded content of the body part.
	Body string

	// The id of the identity to send from.
	IdentityID jmapc.ID

	// The id of the record this entry applies to.
	SentMailboxID jmapc.ID
}

// SendEmailDraft is the creation id SendEmail gives a record it creates,
// which the response reports it under.
const SendEmailDraft jmapc.ID = "draft"

// SendEmailSend is the creation id SendEmail gives a record it creates, which
// the response reports it under.
const SendEmailSend jmapc.ID = "send"

// SendEmail writes a message, hands it to the submission server, and files it
// under Sent once the send succeeds — all in one request, so the draft can
// never be left behind in Drafts by a call that failed halfway.
//
// It makes Email/set and EmailSubmission/set calls in a single request, so
// that 2 dependent calls cost one round trip. It returns the response to the
// EmailSubmission/set call.
//
// The query does not say which account to use, so the session's primary
// account is used for each of urn:ietf:params:jmap:mail and
// urn:ietf:params:jmap:submission, which costs a session lookup on first use.
// They need not be the same account.
func SendEmail(ctx context.Context, c *jmapc.Client, p SendEmailParams) (*jmapc.EmailSubmissionSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}
	submissionAccountID, err := session.PrimaryAccountID(jmapc.CapabilitySubmission)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail, jmapc.CapabilitySubmission},
		MethodCalls: []jmapc.Invocation{
			// Create the message. The creation id "draft" names it for the rest of the
			// request, before the server has assigned it a real one.
			{Name: "Email/set", CallID: "write", Args: map[string]any{
				"accountId": mailAccountID,
				"create": map[string]any{
					"draft": map[string]any{
						"mailboxIds": map[string]any{
							string(p.DraftsMailboxID): true,
						},
						"keywords": json.RawMessage(`{"$draft":true}`),
						"from": []any{
							map[string]any{
								"email": p.FromAddress,
							},
						},
						"to": []any{
							map[string]any{
								"email": p.ToAddress,
							},
						},
						"subject":       p.Subject,
						"bodyStructure": json.RawMessage(`{"partId":"text","type":"text/plain"}`),
						"bodyValues": map[string]any{
							"text": map[string]any{
								"value": p.Body,
							},
						},
					},
				},
			}},
			// Submit it for delivery, referring to the email by its creation id. On
			// success, move it out of Drafts and into Sent and drop the $draft
			// keyword, which the submission server does as part of the same call.
			{Name: "EmailSubmission/set", CallID: "send", Args: map[string]any{
				"accountId": submissionAccountID,
				"create": map[string]any{
					"send": map[string]any{
						"emailId":    "#draft",
						"identityId": p.IdentityID,
					},
				},
				"onSuccessUpdateEmail": map[string]any{
					"#send": map[string]any{
						"mailboxIds/" + string(p.DraftsMailboxID): nil,
						"mailboxIds/" + string(p.SentMailboxID):   true,
						"keywords/$draft":                         nil,
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out jmapc.EmailSubmissionSetResponse
	if e := resp.Decode("send", &out); e != nil {
		if err != nil {
			return nil, err
		}
		return nil, e
	}

	var refused0 jmapc.EmailSetResponse
	if err := resp.Decode("write", &refused0); err != nil {
		return nil, err
	}
	var failures jmapc.SetErrors
	failures.Collect("Email/set", "write", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   refused0.NotCreated,
		"notUpdated":   refused0.NotUpdated,
		"notDestroyed": refused0.NotDestroyed,
	})
	failures.Collect("EmailSubmission/set", "send", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.NotCreated,
		"notUpdated":   out.NotUpdated,
		"notDestroyed": out.NotDestroyed,
	})
	if e := failures.Err(); e != nil {
		return &out, errors.Join(err, e)
	}
	return &out, err
}
