// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SendReadReceipt.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// SendReadReceiptParams holds the values SendReadReceipt leaves open.
type SendReadReceiptParams struct {
	// The identity to send from, which decides both the sender and the address
	// the notification is issued for.
	IdentityID jmapc.ID

	// The id of the email this is about. It is required when sending, and may be
	// null in one that was parsed, where the message it refers to may not be in
	// the account.
	EmailID jmapc.ID

	// The Subject header field for the notification itself.
	Subject string

	// A human-readable explanation, which the notification carries alongside the
	// machine-readable part.
	Body string
}

// SendReadReceipt tells the sender of a message that it was displayed, and
// marks the message so that the receipt is not sent again. Sending one is the
// recipient's choice: nothing in a message can require it.
//
// It makes one MDN/send call in a single request, so that the server is asked
// once. It returns the response to the MDN/send call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func SendReadReceipt(ctx context.Context, c *jmapc.Client, p SendReadReceiptParams) (*jmapc.MDNSendResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mdnAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMDN)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMDN},
		MethodCalls: []jmapc.Invocation{
			// The disposition says both what became of the message and how much of
			// that the user chose. Here they read it and were asked whether to send
			// the receipt.
			{Name: "MDN/send", CallID: "send", Args: map[string]any{
				"accountId":  mdnAccountID,
				"identityId": p.IdentityID,
				"send": map[string]any{
					"receipt": map[string]any{
						"forEmailId":  p.EmailID,
						"subject":     p.Subject,
						"textBody":    p.Body,
						"disposition": json.RawMessage(`{"actionMode":"manual-action","sendingMode":"mdn-sent-manually","type":"displayed"}`),
					},
				},
				"onSuccessUpdateEmail": json.RawMessage(`{"#receipt":{"keywords/$mdnsent":true}}`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.MDNSendResponse
	if err := resp.Decode("send", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
