// Code generated by jmapc. DO NOT EDIT.
// Source: queries/SyncEmails.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// SyncEmailsParams holds the values SyncEmails leaves open.
type SyncEmailsParams struct {
	// The state string the client already has, as returned by an earlier
	// Email/get or Email/changes.
	SinceState string
}

// SyncEmailsEmail holds the properties of Email that the Email/get call in
// SyncEmails asks for.
type SyncEmailsEmail struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The id of the thread the email belongs to.
	ThreadID jmapc.ID `json:"threadId"`

	// The mailboxes the email is in, as a set of ids mapped to true.
	MailboxIDs map[jmapc.ID]bool `json:"mailboxIds"`

	// The keywords set on the email, such as "$seen" or "$flagged", mapped to
	// true.
	Keywords map[string]bool `json:"keywords"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// When the email was received, which is what the mailbox sorts on by
	// default.
	ReceivedAt jmapc.UTCDate `json:"receivedAt"`
}

// SyncEmailsEmail2 holds the properties of Email that the Email/get call in
// SyncEmails asks for.
type SyncEmailsEmail2 struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The mailboxes the email is in, as a set of ids mapped to true.
	MailboxIDs map[jmapc.ID]bool `json:"mailboxIds"`

	// The keywords set on the email, such as "$seen" or "$flagged", mapped to
	// true.
	Keywords map[string]bool `json:"keywords"`
}

// SyncEmailsEmailGetResponse holds the response to the Email/get call in
// SyncEmails.
type SyncEmailsEmailGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []SyncEmailsEmail `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// SyncEmailsEmailGet2Response holds the response to the Email/get call in
// SyncEmails.
type SyncEmailsEmailGet2Response struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []SyncEmailsEmail2 `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// SyncEmailsResult holds the response to each method call SyncEmails makes.
type SyncEmailsResult struct {
	// The response to the Email/changes call, made as "changes".
	EmailChanges jmapc.EmailChangesResponse

	// The response to the Email/get call, made as "created".
	EmailGet SyncEmailsEmailGetResponse

	// The response to the Email/get call, made as "updated".
	EmailGet2 SyncEmailsEmailGet2Response
}

// SyncEmails fetches the emails that have changed since a known state, so a
// local cache can catch up without refetching everything.
//
// It makes Email/changes, Email/get, and Email/get calls in a single request,
// so that 3 dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:mail is used, which costs a session lookup
// on first use.
func SyncEmails(ctx context.Context, c *jmapc.Client, p SyncEmailsParams) (*SyncEmailsResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/changes", CallID: "changes", Args: map[string]any{
				"accountId":  mailAccountID,
				"sinceState": p.SinceState,
				"maxChanges": 128,
			}},
			{Name: "Email/get", CallID: "created", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "changes", Name: "Email/changes", Path: "/created"},
				"properties": json.RawMessage(`["id","threadId","mailboxIds","keywords","subject","receivedAt"]`),
			}},
			{Name: "Email/get", CallID: "updated", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "changes", Name: "Email/changes", Path: "/updated"},
				"properties": json.RawMessage(`["id","mailboxIds","keywords"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out SyncEmailsResult
	if e := resp.Decode("changes", &out.EmailChanges); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("created", &out.EmailGet); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("updated", &out.EmailGet2); e != nil && err == nil {
		return nil, e
	}
	return &out, err
}

// SyncEmailsWatch follows the changes to Email, calling SyncEmails whenever
// the server says there are any and passing the result to fn.
//
// It starts from the sinceState the parameters carry, which is the state a
// previous answer left the caller at, and it goes on from the state each
// answer reports. A server that answers with only part of what changed is
// asked again until it says there is no more.
//
// It runs until the context ends, which is the error it returns; an error
// from fn stops it and comes back as it was. A dropped connection is not an
// error: the loop opens another, resuming where it left off, and asks what it
// missed while there was none.
func SyncEmailsWatch(ctx context.Context, c *jmapc.Client, p SyncEmailsParams, fn func(context.Context, *SyncEmailsResult) error, opts ...jmapc.WatchOption) error {
	session, err := c.Session(ctx)
	if err != nil {
		return err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return err
	}

	return c.Watch(ctx, mailAccountID, "Email", p.SinceState, func(ctx context.Context, sinceState string) (string, bool, error) {
		p.SinceState = sinceState
		res, err := SyncEmails(ctx, c, p)
		if err != nil {
			return "", false, err
		}
		if err := fn(ctx, res); err != nil {
			return "", false, err
		}
		return res.EmailChanges.NewState, res.EmailChanges.HasMoreChanges, nil
	}, opts...)
}
