// Code generated by jmapc. DO NOT EDIT.
// Source: queries/UpdateContactEmail.jmap.json

package jmapq

import (
	"context"

	"github.com/linyows/jmapc"
)

// UpdateContactEmailParams holds the values UpdateContactEmail leaves open.
type UpdateContactEmailParams struct {
	// The id of the record this entry applies to.
	//
	// A map of record id to the patch to apply to it.
	CardID jmapc.ID

	// The id of the record this entry applies to.
	EmailKey jmapc.ID

	// The address itself, as an addr-spec.
	Address string
}

// UpdateContactEmail changes one address on a card and makes it the preferred
// one, sending the two values that changed rather than the whole card.
//
// It makes one ContactCard/set call in a single request, so that the server
// is asked once. It returns the response to the ContactCard/set call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func UpdateContactEmail(ctx context.Context, c *jmapc.Client, p UpdateContactEmailParams) (*jmapc.ContactCardSetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	contactsAccountID, err := session.PrimaryAccountID(jmapc.CapabilityContacts)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityContacts},
		MethodCalls: []jmapc.Invocation{
			{Name: "ContactCard/set", CallID: "update", Args: map[string]any{
				"accountId": contactsAccountID,
				"update": map[string]any{
					string(p.CardID): map[string]any{
						"emails/" + string(p.EmailKey) + "/address": p.Address,
						"emails/" + string(p.EmailKey) + "/pref":    1,
					},
				},
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out jmapc.ContactCardSetResponse
	if err := resp.Decode("update", &out); err != nil {
		return nil, err
	}

	var failures jmapc.SetErrors
	failures.Collect("ContactCard/set", "update", map[string]map[jmapc.ID]jmapc.SetError{
		"notCreated":   out.NotCreated,
		"notUpdated":   out.NotUpdated,
		"notDestroyed": out.NotDestroyed,
	})
	if err := failures.Err(); err != nil {
		return &out, err
	}
	return &out, nil
}
