// Code generated by jmapc. DO NOT EDIT.
// Source: queries/VerifiedSignatures.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// VerifiedSignaturesParams holds the values VerifiedSignatures leaves open.
type VerifiedSignaturesParams struct {
	// Matches emails in this mailbox.
	MailboxID jmapc.ID

	// The maximum number of ids to return.
	Limit jmapc.UnsignedInt
}

// VerifiedSignaturesEmail holds the properties of Email that the Email/get
// call in VerifiedSignatures asks for.
type VerifiedSignaturesEmail struct {
	// The id of the email.
	ID jmapc.ID `json:"id"`

	// The Subject header field value.
	Subject *string `json:"subject"`

	// The From header field value.
	From []jmapc.EmailAddress `json:"from"`

	// When the email was received, which is what the mailbox sorts on by
	// default.
	ReceivedAt jmapc.UTCDate `json:"receivedAt"`

	// What the server made of the message's signature when it last looked:
	// "unknown", "signed", "signed/verified", "signed/failed",
	// "encrypted+signed/verified", or "encrypted+signed/failed". Null for a
	// message with no signature.
	SMIMEStatus *string `json:"smimeStatus"`

	// What the server made of the signature when the message arrived, taking the
	// same values as smimeStatus: "unknown", "signed", "signed/verified",
	// "signed/failed", "encrypted+signed/verified", or
	// "encrypted+signed/failed". It can differ from smimeStatus: a certificate
	// valid on delivery may have expired since, and it is the state at delivery
	// that says whether the message was trustworthy when it was sent.
	SMIMEStatusAtDelivery *string `json:"smimeStatusAtDelivery"`

	// What went wrong with the verification, in terms meant for a person to
	// read.
	SMIMEErrors []string `json:"smimeErrors"`

	// When the server last checked the signature.
	SMIMEVerifiedAt *jmapc.UTCDate `json:"smimeVerifiedAt"`
}

// VerifiedSignaturesEmailGetResponse holds the response to the Email/get call
// in VerifiedSignatures.
type VerifiedSignaturesEmailGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// A string encoding the current state of the type on the server, for use
	// with Email/changes.
	State string `json:"state"`

	// The records that were found, in an undefined order.
	List []VerifiedSignaturesEmail `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// VerifiedSignatures finds signed messages in a mailbox and reports what
// became of each signature. The server does the cryptography: the signature
// covers the raw message, which a client never sees once the server has taken
// it apart.
//
// It makes Email/query and Email/get calls in a single request, so that 2
// dependent calls cost one round trip. It returns the response to the
// Email/get call.
//
// The query does not say which account to use, so the primary account of the
// session is used, which costs a session lookup on first use.
func VerifiedSignatures(ctx context.Context, c *jmapc.Client, p VerifiedSignaturesParams) (*VerifiedSignaturesEmailGetResponse, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	mailAccountID, err := session.PrimaryAccountID(jmapc.CapabilityMail)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityMail, jmapc.CapabilitySMIMEVerify},
		MethodCalls: []jmapc.Invocation{
			{Name: "Email/query", CallID: "search", Args: map[string]any{
				"accountId": mailAccountID,
				"filter": map[string]any{
					"operator": "AND",
					"conditions": []any{
						map[string]any{
							"inMailbox": p.MailboxID,
						},
						json.RawMessage(`{"hasSmime":true}`),
					},
				},
				"sort":  json.RawMessage(`[{"property":"receivedAt","isAscending":false}]`),
				"limit": p.Limit,
			}},
			{Name: "Email/get", CallID: "fetch", Args: map[string]any{
				"accountId":  mailAccountID,
				"#ids":       jmapc.ResultReference{ResultOf: "search", Name: "Email/query", Path: "/ids"},
				"properties": json.RawMessage(`["id","subject","from","receivedAt","smimeStatus","smimeStatusAtDelivery","smimeErrors","smimeVerifiedAt"]`),
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if err != nil {
		return nil, err
	}

	var out VerifiedSignaturesEmailGetResponse
	if err := resp.Decode("fetch", &out); err != nil {
		return nil, err
	}
	return &out, nil
}
