// Code generated by jmapc. DO NOT EDIT.
// Source: queries/WhatUsesBlob.jmap.json

package jmapq

import (
	"context"
	"encoding/json"

	"github.com/linyows/jmapc"
)

// WhatUsesBlobParams holds the values WhatUsesBlob leaves open.
type WhatUsesBlobParams struct {
	// One of the ids in the list.
	//
	// The ids of the blobs to look for.
	BlobID jmapc.ID
}

// WhatUsesBlobBlobData holds the properties of BlobData that the Blob/get
// call in WhatUsesBlob asks for.
type WhatUsesBlobBlobData struct {
	// The id of the blob.
	ID jmapc.ID `json:"id"`

	// The octets as text, or null where they are not valid UTF-8.
	DataAsText *string `json:"data:asText"`

	// The size of the whole blob in octets, whatever range was asked for.
	Size jmapc.UnsignedInt `json:"size"`

	// The digest of the blob under the sha-256 algorithm, as base64.
	DigestSha256 json.RawMessage `json:"digest:sha-256"`
}

// WhatUsesBlobBlobGetResponse holds the response to the Blob/get call in
// WhatUsesBlob.
type WhatUsesBlobBlobGetResponse struct {
	// The id of the account to operate on.
	AccountID jmapc.ID `json:"accountId"`

	// The blobs that were found.
	List []WhatUsesBlobBlobData `json:"list"`

	// The ids that were requested but do not exist.
	NotFound []jmapc.ID `json:"notFound"`
}

// WhatUsesBlobResult holds the response to each method call WhatUsesBlob
// makes.
type WhatUsesBlobResult struct {
	// The response to the Blob/lookup call, made as "uses".
	BlobLookup jmapc.BlobLookupResponse

	// The response to the Blob/get call, made as "peek".
	BlobGet WhatUsesBlobBlobGetResponse
}

// WhatUsesBlob reports which records refer to a blob and reads a little of
// it, which is how a client answers whether deleting a message would take an
// attachment with it.
//
// It makes Blob/lookup and Blob/get calls in a single request, so that 2
// dependent calls cost one round trip.
//
// The query does not say which account to use, so the session's primary
// account for urn:ietf:params:jmap:blob is used, which costs a session lookup
// on first use.
func WhatUsesBlob(ctx context.Context, c *jmapc.Client, p WhatUsesBlobParams) (*WhatUsesBlobResult, error) {
	session, err := c.Session(ctx)
	if err != nil {
		return nil, err
	}
	blobAccountID, err := session.PrimaryAccountID(jmapc.CapabilityBlob)
	if err != nil {
		return nil, err
	}

	req := &jmapc.Request{
		Using: []string{jmapc.CapabilityCore, jmapc.CapabilityBlob},
		MethodCalls: []jmapc.Invocation{
			{Name: "Blob/lookup", CallID: "uses", Args: map[string]any{
				"accountId": blobAccountID,
				"typeNames": json.RawMessage(`["Email","Mailbox"]`),
				"ids": []any{
					p.BlobID,
				},
			}},
			{Name: "Blob/get", CallID: "peek", Args: map[string]any{
				"accountId": blobAccountID,
				"ids": []any{
					p.BlobID,
				},
				"properties": json.RawMessage(`["data:asText","size","digest:sha-256"]`),
				"length":     4096,
			}},
		},
	}

	resp, err := c.Do(ctx, req)
	if resp == nil {
		return nil, err
	}

	var out WhatUsesBlobResult
	if e := resp.Decode("uses", &out.BlobLookup); e != nil && err == nil {
		return nil, e
	}
	if e := resp.Decode("peek", &out.BlobGet); e != nil && err == nil {
		return nil, e
	}
	return &out, err
}
